
extern zend_class_entry *phalcon_flash_exceptions_flashmessagenotstringorarray_ce;

ZEPHIR_INIT_CLASS(Phalcon_Flash_Exceptions_FlashMessageNotStringOrArray);

PHP_METHOD(Phalcon_Flash_Exceptions_FlashMessageNotStringOrArray, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_flash_exceptions_flashmessagenotstringorarray___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_flash_exceptions_flashmessagenotstringorarray_method_entry) {
PHP_ME(Phalcon_Flash_Exceptions_FlashMessageNotStringOrArray, __construct, arginfo_phalcon_flash_exceptions_flashmessagenotstringorarray___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
