
extern zend_class_entry *phalcon_flash_exceptions_sessionserviceunavailable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Flash_Exceptions_SessionServiceUnavailable);

PHP_METHOD(Phalcon_Flash_Exceptions_SessionServiceUnavailable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_flash_exceptions_sessionserviceunavailable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_flash_exceptions_sessionserviceunavailable_method_entry) {
PHP_ME(Phalcon_Flash_Exceptions_SessionServiceUnavailable, __construct, arginfo_phalcon_flash_exceptions_sessionserviceunavailable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
