
extern zend_class_entry *phalcon_encryption_security_jwt_exceptions_invalidexpirationtime_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_JWT_Exceptions_InvalidExpirationTime);

PHP_METHOD(Phalcon_Encryption_Security_JWT_Exceptions_InvalidExpirationTime, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_security_jwt_exceptions_invalidexpirationtime___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_jwt_exceptions_invalidexpirationtime_method_entry) {
PHP_ME(Phalcon_Encryption_Security_JWT_Exceptions_InvalidExpirationTime, __construct, arginfo_phalcon_encryption_security_jwt_exceptions_invalidexpirationtime___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
