
extern zend_class_entry *phalcon_encryption_security_jwt_exceptions_invalidaudiencetype_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_JWT_Exceptions_InvalidAudienceType);

PHP_METHOD(Phalcon_Encryption_Security_JWT_Exceptions_InvalidAudienceType, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_security_jwt_exceptions_invalidaudiencetype___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_jwt_exceptions_invalidaudiencetype_method_entry) {
PHP_ME(Phalcon_Encryption_Security_JWT_Exceptions_InvalidAudienceType, __construct, arginfo_phalcon_encryption_security_jwt_exceptions_invalidaudiencetype___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
