#!/bin/sh

rm -f parser.o
rm -f parser.lo
rm -f scanner.o
rm -f scanner.lo

if [ ! -f $(pwd)/lemon ]; then
	gcc -g lemon.c -o ./lemon
    chmod +x ./lemon
fi

re2c --no-generation-date -o scanner.c scanner.re

./lemon -s volt.lemon

echo '#include "php_phalcon.h"' > parser.c
cat volt.c >> parser.c
cat base.c >> parser.c

sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
sed s/"define TOKEN"/"define VTOKEN"/g parser.c > xx && mv -f xx parser.c

sed s/YY/VV/g scanner.c > xx && mv -f xx scanner.c
sed s/yy/vv/g scanner.c > xx && mv -f xx scanner.c
sed s/YY/VV/g parser.c > xx && mv -f xx parser.c
sed s/yy/vv/g parser.c > xx && mv -f xx parser.c
