
extern zend_class_entry *phalcon_events_exceptions_invalidsubscriberconfiguration_ce;

ZEPHIR_INIT_CLASS(Phalcon_Events_Exceptions_InvalidSubscriberConfiguration);

PHP_METHOD(Phalcon_Events_Exceptions_InvalidSubscriberConfiguration, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_events_exceptions_invalidsubscriberconfiguration___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, eventName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_events_exceptions_invalidsubscriberconfiguration_method_entry) {
	PHP_ME(Phalcon_Events_Exceptions_InvalidSubscriberConfiguration, __construct, arginfo_phalcon_events_exceptions_invalidsubscriberconfiguration___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
