
extern zend_class_entry *phalcon_html_exceptions_friendlytitleconversionfailed_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Exceptions_FriendlyTitleConversionFailed);

PHP_METHOD(Phalcon_Html_Exceptions_FriendlyTitleConversionFailed, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_html_exceptions_friendlytitleconversionfailed___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, message, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_exceptions_friendlytitleconversionfailed_method_entry) {
	PHP_ME(Phalcon_Html_Exceptions_FriendlyTitleConversionFailed, __construct, arginfo_phalcon_html_exceptions_friendlytitleconversionfailed___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
