
extern zend_class_entry *phalcon_html_exceptions_invalidresultsetvalue_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Exceptions_InvalidResultsetValue);

PHP_METHOD(Phalcon_Html_Exceptions_InvalidResultsetValue, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_html_exceptions_invalidresultsetvalue___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_exceptions_invalidresultsetvalue_method_entry) {
PHP_ME(Phalcon_Html_Exceptions_InvalidResultsetValue, __construct, arginfo_phalcon_html_exceptions_invalidresultsetvalue___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
