
extern zend_class_entry *phalcon_html_exceptions_usingrequirestwovalues_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Exceptions_UsingRequiresTwoValues);

PHP_METHOD(Phalcon_Html_Exceptions_UsingRequiresTwoValues, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_html_exceptions_usingrequirestwovalues___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_exceptions_usingrequirestwovalues_method_entry) {
PHP_ME(Phalcon_Html_Exceptions_UsingRequiresTwoValues, __construct, arginfo_phalcon_html_exceptions_usingrequirestwovalues___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
