name: 'Phalcon PHP extension build action'
description: 'Build Phalcon Framework for Linux according to various PHP versions.'

inputs:
  php-version:
    description: 'PHP version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build Phalcon for Linux
      shell: bash
      working-directory: ${{ github.workspace }}/build/phalcon
      run: |
        export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
        echo "::group::Build Phalcon with phpize"
        phpize
        ./configure --enable-phalcon
        make
        echo "::endgroup::"

    - name: Check Extension
      shell: bash
      run: php -d extension=${{ github.workspace }}/build/phalcon/modules/phalcon.so --ri phalcon