
extern zend_class_entry *phalcon_mvc_model_query_exceptions_builder_noprimarykey_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_Query_Exceptions_Builder_NoPrimaryKey);

PHP_METHOD(Phalcon_Mvc_Model_Query_Exceptions_Builder_NoPrimaryKey, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_model_query_exceptions_builder_noprimarykey___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_query_exceptions_builder_noprimarykey_method_entry) {
PHP_ME(Phalcon_Mvc_Model_Query_Exceptions_Builder_NoPrimaryKey, __construct, arginfo_phalcon_mvc_model_query_exceptions_builder_noprimarykey___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
