
extern zend_class_entry *phalcon_auth_guard_guardlocator_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_Guard_GuardLocator);

PHP_METHOD(Phalcon_Auth_Guard_GuardLocator, getExceptionClass);
PHP_METHOD(Phalcon_Auth_Guard_GuardLocator, getInterfaceClass);
PHP_METHOD(Phalcon_Auth_Guard_GuardLocator, getServices);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_guard_guardlocator_getexceptionclass, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_guard_guardlocator_getinterfaceclass, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_guard_guardlocator_getservices, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_guard_guardlocator_method_entry) {
	PHP_ME(Phalcon_Auth_Guard_GuardLocator, getExceptionClass, arginfo_phalcon_auth_guard_guardlocator_getexceptionclass, ZEND_ACC_PROTECTED)
	PHP_ME(Phalcon_Auth_Guard_GuardLocator, getInterfaceClass, arginfo_phalcon_auth_guard_guardlocator_getinterfaceclass, ZEND_ACC_PROTECTED)
	PHP_ME(Phalcon_Auth_Guard_GuardLocator, getServices, arginfo_phalcon_auth_guard_guardlocator_getservices, ZEND_ACC_PROTECTED)
	PHP_FE_END
};
