
extern zend_class_entry *phalcon_support_helper_str_exceptions_syntaxerror_ce;

ZEPHIR_INIT_CLASS(Phalcon_Support_Helper_Str_Exceptions_SyntaxError);

PHP_METHOD(Phalcon_Support_Helper_Str_Exceptions_SyntaxError, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_support_helper_str_exceptions_syntaxerror___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_support_helper_str_exceptions_syntaxerror_method_entry) {
	PHP_ME(Phalcon_Support_Helper_Str_Exceptions_SyntaxError, __construct, arginfo_phalcon_support_helper_str_exceptions_syntaxerror___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
