
extern zend_class_entry *phalcon_filter_exceptions_filternotregistered_ce;

ZEPHIR_INIT_CLASS(Phalcon_Filter_Exceptions_FilterNotRegistered);

PHP_METHOD(Phalcon_Filter_Exceptions_FilterNotRegistered, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_filter_exceptions_filternotregistered___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_filter_exceptions_filternotregistered_method_entry) {
	PHP_ME(Phalcon_Filter_Exceptions_FilterNotRegistered, __construct, arginfo_phalcon_filter_exceptions_filternotregistered___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
