
extern zend_class_entry *phalcon_di_initializationawareinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Di_InitializationAwareInterface);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_di_initializationawareinterface_initialize, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_di_initializationawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Di_InitializationAwareInterface, initialize, arginfo_phalcon_di_initializationawareinterface_initialize)
	PHP_FE_END
};
