#define PHQL_BETWEEN                         1
#define PHQL_EQUALS                          2
#define PHQL_NOTEQUALS                       3
#define PHQL_LESS                            4
#define PHQL_GREATER                         5
#define PHQL_GREATEREQUAL                    6
#define PHQL_LESSEQUAL                       7
#define PHQL_AND                             8
#define PHQL_OR                              9
#define PHQL_LIKE                           10
#define PHQL_DIVIDE                         11
#define PHQL_TIMES                          12
#define PHQL_MOD                            13
#define PHQL_PLUS                           14
#define PHQL_MINUS                          15
#define PHQL_IS                             16
#define PHQL_IN                             17
#define PHQL_DISTINCT                       18
#define PHQL_NOT                            19
#define PHQL_SELECT                         20
#define PHQL_FROM                           21
#define PHQL_COMMA                          22
#define PHQL_IDENTIFIER                     23
#define PHQL_DOT                            24
#define PHQL_AS                             25
#define PHQL_JOIN                           26
#define PHQL_INNER                          27
#define PHQL_CROSS                          28
#define PHQL_LEFT                           29
#define PHQL_OUTER                          30
#define PHQL_RIGHT                          31
#define PHQL_FULL                           32
#define PHQL_ON                             33
#define PHQL_INSERT                         34
#define PHQL_INTO                           35
#define PHQL_VALUES                         36
#define PHQL_BRACKET_OPEN                   37
#define PHQL_BRACKET_CLOSE                  38
#define PHQL_UPDATE                         39
#define PHQL_SET                            40
#define PHQL_DELETE                         41
#define PHQL_WHERE                          42
#define PHQL_ORDER                          43
#define PHQL_BY                             44
#define PHQL_ASC                            45
#define PHQL_DESC                           46
#define PHQL_INTEGER                        47
#define PHQL_GROUP                          48
#define PHQL_HAVING                         49
#define PHQL_LIMIT                          50
#define PHQL_OFFSET                         51
#define PHQL_NULL                           52
#define PHQL_STRING                         53
#define PHQL_DOUBLE                         54
#define PHQL_NPLACEHOLDER                   55
#define PHQL_SPLACEHOLDER                   56
