#define PHQL_EQUALS                          1
#define PHQL_NOTEQUALS                       2
#define PHQL_LESS                            3
#define PHQL_GREATER                         4
#define PHQL_GREATEREQUAL                    5
#define PHQL_LESSEQUAL                       6
#define PHQL_AND                             7
#define PHQL_OR                              8
#define PHQL_LIKE                            9
#define PHQL_DIVIDE                         10
#define PHQL_TIMES                          11
#define PHQL_MOD                            12
#define PHQL_PLUS                           13
#define PHQL_MINUS                          14
#define PHQL_IS                             15
#define PHQL_IN                             16
#define PHQL_NOT                            17
#define PHQL_SELECT                         18
#define PHQL_FROM                           19
#define PHQL_COMMA                          20
#define PHQL_IDENTIFIER                     21
#define PHQL_DOT                            22
#define PHQL_AS                             23
#define PHQL_JOIN                           24
#define PHQL_ON                             25
#define PHQL_INNER                          26
#define PHQL_CROSS                          27
#define PHQL_LEFT                           28
#define PHQL_OUTER                          29
#define PHQL_RIGHT                          30
#define PHQL_FULL                           31
#define PHQL_INSERT                         32
#define PHQL_INTO                           33
#define PHQL_VALUES                         34
#define PHQL_BRACKET_OPEN                   35
#define PHQL_BRACKET_CLOSE                  36
#define PHQL_UPDATE                         37
#define PHQL_SET                            38
#define PHQL_DELETE                         39
#define PHQL_WHERE                          40
#define PHQL_ORDER                          41
#define PHQL_BY                             42
#define PHQL_ASC                            43
#define PHQL_DESC                           44
#define PHQL_INTEGER                        45
#define PHQL_GROUP                          46
#define PHQL_HAVING                         47
#define PHQL_LIMIT                          48
#define PHQL_OFFSET                         49
#define PHQL_NULL                           50
#define PHQL_STRING                         51
#define PHQL_DOUBLE                         52
#define PHQL_NPLACEHOLDER                   53
#define PHQL_SPLACEHOLDER                   54
