#define PHQL_AGAINST                         1
#define PHQL_BETWEEN                         2
#define PHQL_EQUALS                          3
#define PHQL_NOTEQUALS                       4
#define PHQL_LESS                            5
#define PHQL_GREATER                         6
#define PHQL_GREATEREQUAL                    7
#define PHQL_LESSEQUAL                       8
#define PHQL_AND                             9
#define PHQL_OR                             10
#define PHQL_LIKE                           11
#define PHQL_ILIKE                          12
#define PHQL_BITWISE_AND                    13
#define PHQL_BITWISE_OR                     14
#define PHQL_DIVIDE                         15
#define PHQL_TIMES                          16
#define PHQL_MOD                            17
#define PHQL_PLUS                           18
#define PHQL_MINUS                          19
#define PHQL_IS                             20
#define PHQL_IN                             21
#define PHQL_DISTINCT                       22
#define PHQL_NOT                            23
#define PHQL_SELECT                         24
#define PHQL_FROM                           25
#define PHQL_COMMA                          26
#define PHQL_IDENTIFIER                     27
#define PHQL_DOT                            28
#define PHQL_AS                             29
#define PHQL_JOIN                           30
#define PHQL_INNER                          31
#define PHQL_CROSS                          32
#define PHQL_LEFT                           33
#define PHQL_OUTER                          34
#define PHQL_RIGHT                          35
#define PHQL_FULL                           36
#define PHQL_ON                             37
#define PHQL_INSERT                         38
#define PHQL_INTO                           39
#define PHQL_VALUES                         40
#define PHQL_BRACKET_OPEN                   41
#define PHQL_BRACKET_CLOSE                  42
#define PHQL_UPDATE                         43
#define PHQL_SET                            44
#define PHQL_DELETE                         45
#define PHQL_WHERE                          46
#define PHQL_ORDER                          47
#define PHQL_BY                             48
#define PHQL_ASC                            49
#define PHQL_DESC                           50
#define PHQL_GROUP                          51
#define PHQL_INTEGER                        52
#define PHQL_HAVING                         53
#define PHQL_LIMIT                          54
#define PHQL_OFFSET                         55
#define PHQL_NULL                           56
#define PHQL_STRING                         57
#define PHQL_DOUBLE                         58
#define PHQL_NPLACEHOLDER                   59
#define PHQL_SPLACEHOLDER                   60
