/* Generated by re2c 0.13.5 on Sat Jan 11 18:45:50 2014 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "mvc/model/query/scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 40 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  48,  48,  48,  48,  48,  48,  48, 
				 48,  52,  52,  48,  48,  52,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 52,  48,  16,  48,  48,  48,  48,  32, 
				 48,  48,  48,  48,  48, 112,  48,  48, 
				248, 248, 248, 248, 248, 248, 248, 248, 
				248, 248,  48,  48,  48,  48,  48,  48, 
				 48, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120,  48,   8,  48,  48, 120, 
				 48, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
			};

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy68;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy66;
			case '!':	goto yy50;
			case '"':	goto yy29;
			case '%':	goto yy42;
			case '&':	goto yy62;
			case '\'':	goto yy30;
			case '(':	goto yy46;
			case ')':	goto yy48;
			case '*':	goto yy38;
			case '+':	goto yy34;
			case ',':	goto yy44;
			case '-':	goto yy36;
			case '.':	goto yy4;
			case '/':	goto yy40;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy2;
			case ':':	goto yy8;
			case '<':	goto yy52;
			case '=':	goto yy56;
			case '>':	goto yy54;
			case '?':	goto yy6;
			case 'A':
			case 'a':	goto yy15;
			case 'B':
			case 'b':	goto yy20;
			case 'C':
			case 'c':	goto yy27;
			case 'D':
			case 'd':	goto yy13;
			case 'E':
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'e':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy32;
			case 'F':
			case 'f':	goto yy14;
			case 'G':
			case 'g':	goto yy21;
			case 'H':
			case 'h':	goto yy22;
			case 'I':
			case 'i':	goto yy16;
			case 'J':
			case 'j':	goto yy25;
			case 'L':
			case 'l':	goto yy23;
			case 'N':
			case 'n':	goto yy24;
			case 'O':
			case 'o':	goto yy19;
			case 'R':
			case 'r':	goto yy26;
			case 'S':
			case 's':	goto yy12;
			case 'T':
			case 't':	goto yy28;
			case 'U':
			case 'u':	goto yy10;
			case 'V':
			case 'v':	goto yy17;
			case 'W':
			case 'w':	goto yy18;
			case '[':	goto yy33;
			case '\\':	goto yy31;
			case '^':	goto yy60;
			case '|':	goto yy64;
			case '~':	goto yy58;
			default:	goto yy70;
			}
yy2:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '.') goto yy291;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy293;
yy3:
/* #line 41 "scanner.re" */
			{
			token->opcode = PHQL_T_INTEGER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 188 "scanner.c" */
yy4:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy5;
			if (yych <= '9') goto yy288;
yy5:
/* #line 353 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 199 "scanner.c" */
yy6:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 128) {
				goto yy285;
			}
yy7:
/* #line 448 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 211 "scanner.c" */
yy8:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 64) {
				goto yy281;
			}
yy9:
/* #line 358 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 224 "scanner.c" */
yy10:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'S') {
				if (yych == 'P') goto yy270;
				if (yych <= 'R') goto yy87;
				goto yy271;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy87;
					goto yy270;
				} else {
					if (yych == 's') goto yy271;
					goto yy87;
				}
			}
yy11:
/* #line 301 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 259 "scanner.c" */
yy12:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy262;
			if (yych == 'e') goto yy262;
			goto yy87;
yy13:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy245;
				if (yych <= 'H') goto yy87;
				goto yy246;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy87;
					goto yy245;
				} else {
					if (yych == 'i') goto yy246;
					goto yy87;
				}
			}
yy14:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'Q') {
					if (yych == 'A') goto yy232;
					goto yy87;
				} else {
					if (yych <= 'R') goto yy233;
					if (yych <= 'T') goto yy87;
					goto yy234;
				}
			} else {
				if (yych <= 'q') {
					if (yych == 'a') goto yy232;
					goto yy87;
				} else {
					if (yych <= 'r') goto yy233;
					if (yych == 'u') goto yy234;
					goto yy87;
				}
			}
yy15:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'L') {
					if (yych == 'G') goto yy215;
					if (yych <= 'K') goto yy87;
					goto yy216;
				} else {
					if (yych == 'N') goto yy217;
					if (yych <= 'R') goto yy87;
					goto yy218;
				}
			} else {
				if (yych <= 'l') {
					if (yych == 'g') goto yy215;
					if (yych <= 'k') goto yy87;
					goto yy216;
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy87;
						goto yy217;
					} else {
						if (yych == 's') goto yy218;
						goto yy87;
					}
				}
			}
yy16:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy194;
					goto yy87;
				} else {
					if (yych <= 'N') goto yy195;
					if (yych <= 'R') goto yy87;
					goto yy197;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy194;
					goto yy87;
				} else {
					if (yych <= 'n') goto yy195;
					if (yych == 's') goto yy197;
					goto yy87;
				}
			}
yy17:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy188;
			if (yych == 'a') goto yy188;
			goto yy87;
yy18:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy183;
			if (yych == 'h') goto yy183;
			goto yy87;
yy19:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy164;
					if (yych <= 'M') goto yy87;
					goto yy165;
				} else {
					if (yych == 'R') goto yy167;
					if (yych <= 'T') goto yy87;
					goto yy169;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy164;
					if (yych <= 'm') goto yy87;
					goto yy165;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy87;
						goto yy167;
					} else {
						if (yych == 'u') goto yy169;
						goto yy87;
					}
				}
			}
yy20:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy155;
				if (yych <= 'X') goto yy87;
				goto yy156;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy87;
					goto yy155;
				} else {
					if (yych == 'y') goto yy156;
					goto yy87;
				}
			}
yy21:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy150;
			if (yych == 'r') goto yy150;
			goto yy87;
yy22:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy144;
			if (yych == 'a') goto yy144;
			goto yy87;
yy23:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy132;
				if (yych <= 'H') goto yy87;
				goto yy133;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy87;
					goto yy132;
				} else {
					if (yych == 'i') goto yy133;
					goto yy87;
				}
			}
yy24:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy125;
				if (yych <= 'T') goto yy87;
				goto yy126;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy87;
					goto yy125;
				} else {
					if (yych == 'u') goto yy126;
					goto yy87;
				}
			}
yy25:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy121;
			if (yych == 'o') goto yy121;
			goto yy87;
yy26:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy116;
			if (yych == 'i') goto yy116;
			goto yy87;
yy27:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy100;
					goto yy87;
				} else {
					if (yych <= 'O') goto yy101;
					if (yych <= 'Q') goto yy87;
					goto yy102;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy100;
					goto yy87;
				} else {
					if (yych <= 'o') goto yy101;
					if (yych == 'r') goto yy102;
					goto yy87;
				}
			}
yy28:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy96;
			if (yych == 'r') goto yy96;
			goto yy87;
yy29:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy7;
			goto yy94;
yy30:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy7;
			goto yy89;
yy31:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy7;
				if (yych <= 'Z') goto yy86;
				goto yy7;
			} else {
				if (yych == '`') goto yy7;
				if (yych <= 'z') goto yy86;
				goto yy7;
			}
yy32:
			yych = *++YYCURSOR;
			goto yy87;
yy33:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy7;
				if (yych == '[') goto yy7;
				goto yy81;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy7;
					goto yy81;
				} else {
					if (yych <= '`') goto yy7;
					if (yych <= 'z') goto yy81;
					goto yy7;
				}
			}
yy34:
			++YYCURSOR;
/* #line 328 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 525 "scanner.c" */
yy36:
			++YYCURSOR;
/* #line 333 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 533 "scanner.c" */
yy38:
			++YYCURSOR;
/* #line 338 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 541 "scanner.c" */
yy40:
			++YYCURSOR;
/* #line 343 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 549 "scanner.c" */
yy42:
			++YYCURSOR;
/* #line 348 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 557 "scanner.c" */
yy44:
			++YYCURSOR;
/* #line 363 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 565 "scanner.c" */
yy46:
			++YYCURSOR;
/* #line 368 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 573 "scanner.c" */
yy48:
			++YYCURSOR;
/* #line 373 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 581 "scanner.c" */
yy50:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy79;
/* #line 413 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 590 "scanner.c" */
yy52:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy53;
			if (yych <= '=') goto yy75;
			if (yych <= '>') goto yy77;
yy53:
/* #line 398 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 602 "scanner.c" */
yy54:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy73;
/* #line 403 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 611 "scanner.c" */
yy56:
			++YYCURSOR;
/* #line 408 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 619 "scanner.c" */
yy58:
			++YYCURSOR;
/* #line 418 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 627 "scanner.c" */
yy60:
			++YYCURSOR;
/* #line 423 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 635 "scanner.c" */
yy62:
			++YYCURSOR;
/* #line 428 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 643 "scanner.c" */
yy64:
			++YYCURSOR;
/* #line 433 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 651 "scanner.c" */
yy66:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy72;
yy67:
/* #line 438 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 662 "scanner.c" */
yy68:
			++YYCURSOR;
/* #line 443 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 670 "scanner.c" */
yy70:
			yych = *++YYCURSOR;
			goto yy7;
yy71:
			++YYCURSOR;
			yych = *YYCURSOR;
yy72:
			if (yybm[0+yych] & 4) {
				goto yy71;
			}
			goto yy67;
yy73:
			++YYCURSOR;
/* #line 393 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 689 "scanner.c" */
yy75:
			++YYCURSOR;
/* #line 388 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 697 "scanner.c" */
yy77:
			++YYCURSOR;
/* #line 383 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 705 "scanner.c" */
yy79:
			++YYCURSOR;
/* #line 378 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 713 "scanner.c" */
yy81:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 8) {
				goto yy81;
			}
			if (yych == ']') goto yy84;
yy83:
			YYCURSOR = YYMARKER;
			if (yyaccept <= 0) {
				goto yy9;
			} else {
				goto yy7;
			}
yy84:
			++YYCURSOR;
/* #line 320 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 738 "scanner.c" */
yy86:
			++YYCURSOR;
			yych = *YYCURSOR;
yy87:
			if (yych <= '[') {
				if (yych <= '9') {
					if (yych <= '/') goto yy11;
					goto yy86;
				} else {
					if (yych <= '@') goto yy11;
					if (yych <= 'Z') goto yy86;
					goto yy11;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych <= '^') goto yy11;
					goto yy86;
				} else {
					if (yych <= '`') goto yy11;
					if (yych <= 'z') goto yy86;
					goto yy11;
				}
			}
yy88:
			++YYCURSOR;
			yych = *YYCURSOR;
yy89:
			if (yybm[0+yych] & 16) {
				goto yy88;
			}
			if (yych <= 0x00) goto yy83;
			if (yych <= '[') goto yy91;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy83;
			goto yy88;
yy91:
			++YYCURSOR;
/* #line 292 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 786 "scanner.c" */
yy93:
			++YYCURSOR;
			yych = *YYCURSOR;
yy94:
			if (yybm[0+yych] & 32) {
				goto yy93;
			}
			if (yych <= 0x00) goto yy83;
			if (yych <= '[') goto yy91;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy83;
			goto yy93;
yy96:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy97;
			if (yych != 'u') goto yy87;
yy97:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy98;
			if (yych != 'e') goto yy87;
yy98:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy99;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy99;
					if (yych <= 'z') goto yy86;
				}
			}
yy99:
/* #line 281 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 832 "scanner.c" */
yy100:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy113;
			if (yych == 's') goto yy113;
			goto yy87;
yy101:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy107;
			if (yych == 'n') goto yy107;
			goto yy87;
yy102:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy103;
			if (yych != 'o') goto yy87;
yy103:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy104;
			if (yych != 's') goto yy87;
yy104:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy105;
			if (yych != 's') goto yy87;
yy105:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy106;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy106;
					if (yych <= 'z') goto yy86;
				}
			}
yy106:
/* #line 226 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 879 "scanner.c" */
yy107:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy108;
			if (yych != 'v') goto yy87;
yy108:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy109;
			if (yych != 'e') goto yy87;
yy109:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy110;
			if (yych != 'r') goto yy87;
yy110:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy111;
			if (yych != 't') goto yy87;
yy111:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy112;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy112;
					if (yych <= 'z') goto yy86;
				}
			}
yy112:
/* #line 271 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 920 "scanner.c" */
yy113:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy114;
			if (yych != 't') goto yy87;
yy114:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy115;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy115;
					if (yych <= 'z') goto yy86;
				}
			}
yy115:
/* #line 266 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 949 "scanner.c" */
yy116:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy117;
			if (yych != 'g') goto yy87;
yy117:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy118;
			if (yych != 'h') goto yy87;
yy118:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy119;
			if (yych != 't') goto yy87;
yy119:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy120;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy120;
					if (yych <= 'z') goto yy86;
				}
			}
yy120:
/* #line 221 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 986 "scanner.c" */
yy121:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy122;
			if (yych != 'i') goto yy87;
yy122:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy123;
			if (yych != 'n') goto yy87;
yy123:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy124;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy124;
					if (yych <= 'z') goto yy86;
				}
			}
yy124:
/* #line 206 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1019 "scanner.c" */
yy125:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy130;
			if (yych == 't') goto yy130;
			goto yy87;
yy126:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy127;
			if (yych != 'l') goto yy87;
yy127:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy128;
			if (yych != 'l') goto yy87;
yy128:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy129;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy129;
					if (yych <= 'z') goto yy86;
				}
			}
yy129:
/* #line 246 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1057 "scanner.c" */
yy130:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy131;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy131;
					if (yych <= 'z') goto yy86;
				}
			}
yy131:
/* #line 166 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1082 "scanner.c" */
yy132:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy141;
			if (yych == 'f') goto yy141;
			goto yy87;
yy133:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy135;
				if (yych <= 'L') goto yy87;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy87;
					goto yy135;
				} else {
					if (yych != 'm') goto yy87;
				}
			}
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy138;
			if (yych == 'i') goto yy138;
			goto yy87;
yy135:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy136;
			if (yych != 'e') goto yy87;
yy136:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy137;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy137;
					if (yych <= 'z') goto yy86;
				}
			}
yy137:
/* #line 181 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1133 "scanner.c" */
yy138:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy139;
			if (yych != 't') goto yy87;
yy139:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy140;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy140;
					if (yych <= 'z') goto yy86;
				}
			}
yy140:
/* #line 156 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 1162 "scanner.c" */
yy141:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy142;
			if (yych != 't') goto yy87;
yy142:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy143;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy143;
					if (yych <= 'z') goto yy86;
				}
			}
yy143:
/* #line 216 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1191 "scanner.c" */
yy144:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy145;
			if (yych != 'v') goto yy87;
yy145:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy146;
			if (yych != 'i') goto yy87;
yy146:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy147;
			if (yych != 'n') goto yy87;
yy147:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy148;
			if (yych != 'g') goto yy87;
yy148:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy149;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy149;
					if (yych <= 'z') goto yy86;
				}
			}
yy149:
/* #line 151 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 1232 "scanner.c" */
yy150:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy151;
			if (yych != 'o') goto yy87;
yy151:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy152;
			if (yych != 'u') goto yy87;
yy152:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy153;
			if (yych != 'p') goto yy87;
yy153:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy154;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy154;
					if (yych <= 'z') goto yy86;
				}
			}
yy154:
/* #line 146 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1269 "scanner.c" */
yy155:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy158;
			if (yych == 't') goto yy158;
			goto yy87;
yy156:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy157;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy157;
					if (yych <= 'z') goto yy86;
				}
			}
yy157:
/* #line 131 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 1299 "scanner.c" */
yy158:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy159;
			if (yych != 'w') goto yy87;
yy159:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy160;
			if (yych != 'e') goto yy87;
yy160:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy161;
			if (yych != 'e') goto yy87;
yy161:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy162;
			if (yych != 'n') goto yy87;
yy162:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy163;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy163;
					if (yych <= 'z') goto yy86;
				}
			}
yy163:
/* #line 261 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 1340 "scanner.c" */
yy164:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy178;
			if (yych == 'f') goto yy178;
			goto yy87;
yy165:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy166;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy166;
					if (yych <= 'z') goto yy86;
				}
			}
yy166:
/* #line 201 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1370 "scanner.c" */
yy167:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy168;
					if (yych <= '9') goto yy86;
				} else {
					if (yych == 'D') goto yy174;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy86;
					if (yych == '_') goto yy86;
				} else {
					if (yych == 'd') goto yy174;
					if (yych <= 'z') goto yy86;
				}
			}
yy168:
/* #line 176 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1396 "scanner.c" */
yy169:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy170;
			if (yych != 't') goto yy87;
yy170:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy171;
			if (yych != 'e') goto yy87;
yy171:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy172;
			if (yych != 'r') goto yy87;
yy172:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy173;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy173;
					if (yych <= 'z') goto yy86;
				}
			}
yy173:
/* #line 231 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 1433 "scanner.c" */
yy174:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy175;
			if (yych != 'e') goto yy87;
yy175:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy176;
			if (yych != 'r') goto yy87;
yy176:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy177;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy177;
					if (yych <= 'z') goto yy86;
				}
			}
yy177:
/* #line 126 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 1466 "scanner.c" */
yy178:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy179;
			if (yych != 's') goto yy87;
yy179:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy180;
			if (yych != 'e') goto yy87;
yy180:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy181;
			if (yych != 't') goto yy87;
yy181:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy182;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy182;
					if (yych <= 'z') goto yy86;
				}
			}
yy182:
/* #line 161 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 1503 "scanner.c" */
yy183:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy184;
			if (yych != 'e') goto yy87;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy185;
			if (yych != 'r') goto yy87;
yy185:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy186;
			if (yych != 'e') goto yy87;
yy186:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy187;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy187;
					if (yych <= 'z') goto yy86;
				}
			}
yy187:
/* #line 116 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 1540 "scanner.c" */
yy188:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy189;
			if (yych != 'l') goto yy87;
yy189:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy190;
			if (yych != 'u') goto yy87;
yy190:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy191;
			if (yych != 'e') goto yy87;
yy191:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy192;
			if (yych != 's') goto yy87;
yy192:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy193;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy193;
					if (yych <= 'z') goto yy86;
				}
			}
yy193:
/* #line 111 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 1581 "scanner.c" */
yy194:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy211;
			if (yych == 'i') goto yy211;
			goto yy87;
yy195:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= '9') {
						if (yych >= '0') goto yy86;
					} else {
						if (yych <= '@') goto yy196;
						if (yych <= 'M') goto yy86;
						goto yy201;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy86;
						goto yy199;
					} else {
						if (yych <= 'T') goto yy200;
						if (yych <= 'Z') goto yy86;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy86;
					} else {
						if (yych != '`') goto yy86;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy201;
						if (yych <= 'r') goto yy86;
						goto yy199;
					} else {
						if (yych <= 't') goto yy200;
						if (yych <= 'z') goto yy86;
					}
				}
			}
yy196:
/* #line 196 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1631 "scanner.c" */
yy197:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy198;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy198;
					if (yych <= 'z') goto yy86;
				}
			}
yy198:
/* #line 241 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1656 "scanner.c" */
yy199:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy207;
			if (yych == 'e') goto yy207;
			goto yy87;
yy200:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy205;
			if (yych == 'o') goto yy205;
			goto yy87;
yy201:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy202;
			if (yych != 'e') goto yy87;
yy202:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy203;
			if (yych != 'r') goto yy87;
yy203:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy204;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy204;
					if (yych <= 'z') goto yy86;
				}
			}
yy204:
/* #line 211 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 1699 "scanner.c" */
yy205:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy206;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy206;
					if (yych <= 'z') goto yy86;
				}
			}
yy206:
/* #line 106 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1724 "scanner.c" */
yy207:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy208;
			if (yych != 'r') goto yy87;
yy208:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy209;
			if (yych != 't') goto yy87;
yy209:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy210;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy210;
					if (yych <= 'z') goto yy86;
				}
			}
yy210:
/* #line 101 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 1757 "scanner.c" */
yy211:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy212;
			if (yych != 'k') goto yy87;
yy212:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy213;
			if (yych != 'e') goto yy87;
yy213:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy214;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy214;
					if (yych <= 'z') goto yy86;
				}
			}
yy214:
/* #line 186 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 1790 "scanner.c" */
yy215:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy226;
			if (yych == 'a') goto yy226;
			goto yy87;
yy216:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy224;
			if (yych == 'l') goto yy224;
			goto yy87;
yy217:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy222;
			if (yych == 'd') goto yy222;
			goto yy87;
yy218:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy219;
					if (yych <= '9') goto yy86;
				} else {
					if (yych == 'C') goto yy220;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy86;
					if (yych == '_') goto yy86;
				} else {
					if (yych == 'c') goto yy220;
					if (yych <= 'z') goto yy86;
				}
			}
yy219:
/* #line 96 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 1831 "scanner.c" */
yy220:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy221;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy221;
					if (yych <= 'z') goto yy86;
				}
			}
yy221:
/* #line 136 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 1856 "scanner.c" */
yy222:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy223;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy223;
					if (yych <= 'z') goto yy86;
				}
			}
yy223:
/* #line 171 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 1881 "scanner.c" */
yy224:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy225;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy225;
					if (yych <= 'z') goto yy86;
				}
			}
yy225:
/* #line 256 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 1906 "scanner.c" */
yy226:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy227;
			if (yych != 'i') goto yy87;
yy227:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy228;
			if (yych != 'n') goto yy87;
yy228:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy229;
			if (yych != 's') goto yy87;
yy229:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy230;
			if (yych != 't') goto yy87;
yy230:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy231;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy231;
					if (yych <= 'z') goto yy86;
				}
			}
yy231:
/* #line 191 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 1947 "scanner.c" */
yy232:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy241;
			if (yych == 'l') goto yy241;
			goto yy87;
yy233:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy238;
			if (yych == 'o') goto yy238;
			goto yy87;
yy234:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy235;
			if (yych != 'l') goto yy87;
yy235:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy236;
			if (yych != 'l') goto yy87;
yy236:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy237;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy237;
					if (yych <= 'z') goto yy86;
				}
			}
yy237:
/* #line 236 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 1990 "scanner.c" */
yy238:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy239;
			if (yych != 'm') goto yy87;
yy239:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy240;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy240;
					if (yych <= 'z') goto yy86;
				}
			}
yy240:
/* #line 91 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 2019 "scanner.c" */
yy241:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy242;
			if (yych != 's') goto yy87;
yy242:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy243;
			if (yych != 'e') goto yy87;
yy243:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy244;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy244;
					if (yych <= 'z') goto yy86;
				}
			}
yy244:
/* #line 286 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2052 "scanner.c" */
yy245:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy254;
				if (yych <= 'R') goto yy87;
				goto yy255;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy87;
					goto yy254;
				} else {
					if (yych == 's') goto yy255;
					goto yy87;
				}
			}
yy246:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy247;
			if (yych != 's') goto yy87;
yy247:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy248;
			if (yych != 't') goto yy87;
yy248:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy249;
			if (yych != 'i') goto yy87;
yy249:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy250;
			if (yych != 'n') goto yy87;
yy250:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy251;
			if (yych != 'c') goto yy87;
yy251:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy252;
			if (yych != 't') goto yy87;
yy252:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy253;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy253;
					if (yych <= 'z') goto yy86;
				}
			}
yy253:
/* #line 251 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2116 "scanner.c" */
yy254:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy258;
			if (yych == 'e') goto yy258;
			goto yy87;
yy255:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy256;
			if (yych != 'c') goto yy87;
yy256:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy257;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy257;
					if (yych <= 'z') goto yy86;
				}
			}
yy257:
/* #line 141 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 2150 "scanner.c" */
yy258:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy259;
			if (yych != 't') goto yy87;
yy259:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy260;
			if (yych != 'e') goto yy87;
yy260:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy261;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy261;
					if (yych <= 'z') goto yy86;
				}
			}
yy261:
/* #line 86 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2183 "scanner.c" */
yy262:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy265;
				if (yych <= 'S') goto yy87;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy87;
					goto yy265;
				} else {
					if (yych != 't') goto yy87;
				}
			}
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy264;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy264;
					if (yych <= 'z') goto yy86;
				}
			}
yy264:
/* #line 81 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 2220 "scanner.c" */
yy265:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy266;
			if (yych != 'e') goto yy87;
yy266:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy267;
			if (yych != 'c') goto yy87;
yy267:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy268;
			if (yych != 't') goto yy87;
yy268:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy269;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy269;
					if (yych <= 'z') goto yy86;
				}
			}
yy269:
/* #line 121 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 2257 "scanner.c" */
yy270:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy276;
			if (yych == 'd') goto yy276;
			goto yy87;
yy271:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy272;
			if (yych != 'i') goto yy87;
yy272:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy273;
			if (yych != 'n') goto yy87;
yy273:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy274;
			if (yych != 'g') goto yy87;
yy274:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy275;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy275;
					if (yych <= 'z') goto yy86;
				}
			}
yy275:
/* #line 276 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 2299 "scanner.c" */
yy276:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy277;
			if (yych != 'a') goto yy87;
yy277:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy278;
			if (yych != 't') goto yy87;
yy278:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy279;
			if (yych != 'e') goto yy87;
yy279:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy86;
				} else {
					if (yych <= '@') goto yy280;
					if (yych <= 'Z') goto yy86;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy86;
					if (yych >= '_') goto yy86;
				} else {
					if (yych <= '`') goto yy280;
					if (yych <= 'z') goto yy86;
				}
			}
yy280:
/* #line 76 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 2336 "scanner.c" */
yy281:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy281;
			}
			if (yych != ':') goto yy83;
			++YYCURSOR;
/* #line 68 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2353 "scanner.c" */
yy285:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy285;
			}
/* #line 59 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2368 "scanner.c" */
yy288:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy290;
			if (yych <= '9') goto yy288;
yy290:
/* #line 50 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2383 "scanner.c" */
yy291:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy290;
			if (yych <= '9') goto yy291;
			goto yy290;
yy293:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '.') goto yy291;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy293;
			goto yy3;
		}
/* #line 453 "scanner.re" */

	}

	return status;
}
