/* Generated by re2c 0.13.5 on Tue Dec 23 09:32:08 2014 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "mvc/model/query/scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 40 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  48,  48,  48,  48,  48,  48,  48, 
				 48,  52,  52,  48,  48,  52,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 52,  48,  16,  48,  48,  48,  48,  32, 
				 48,  48,  48,  48,  48, 112,  48,  48, 
				248, 248, 248, 248, 248, 248, 248, 248, 
				248, 248,  48,  48,  48,  48,  48,  48, 
				 48, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120,  48,   8,  48,  48, 120, 
				 48, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120, 120, 120, 120, 120, 120, 
				120, 120, 120,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
			};

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy69;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy67;
			case '!':	goto yy50;
			case '"':	goto yy29;
			case '%':	goto yy42;
			case '&':	goto yy61;
			case '\'':	goto yy30;
			case '(':	goto yy46;
			case ')':	goto yy48;
			case '*':	goto yy38;
			case '+':	goto yy34;
			case ',':	goto yy44;
			case '-':	goto yy36;
			case '.':	goto yy4;
			case '/':	goto yy40;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy2;
			case ':':	goto yy8;
			case '<':	goto yy52;
			case '=':	goto yy56;
			case '>':	goto yy54;
			case '?':	goto yy6;
			case '@':	goto yy58;
			case 'A':
			case 'a':	goto yy15;
			case 'B':
			case 'b':	goto yy20;
			case 'C':
			case 'c':	goto yy27;
			case 'D':
			case 'd':	goto yy13;
			case 'E':
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'e':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy32;
			case 'F':
			case 'f':	goto yy14;
			case 'G':
			case 'g':	goto yy21;
			case 'H':
			case 'h':	goto yy22;
			case 'I':
			case 'i':	goto yy16;
			case 'J':
			case 'j':	goto yy25;
			case 'L':
			case 'l':	goto yy23;
			case 'N':
			case 'n':	goto yy24;
			case 'O':
			case 'o':	goto yy19;
			case 'R':
			case 'r':	goto yy26;
			case 'S':
			case 's':	goto yy12;
			case 'T':
			case 't':	goto yy28;
			case 'U':
			case 'u':	goto yy10;
			case 'V':
			case 'v':	goto yy17;
			case 'W':
			case 'w':	goto yy18;
			case '[':	goto yy33;
			case '\\':	goto yy31;
			case '^':	goto yy65;
			case '|':	goto yy59;
			case '~':	goto yy63;
			default:	goto yy71;
			}
yy2:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '.') goto yy302;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy304;
yy3:
/* #line 41 "scanner.re" */
			{
			token->opcode = PHQL_T_INTEGER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 189 "scanner.c" */
yy4:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy5;
			if (yych <= '9') goto yy299;
yy5:
/* #line 353 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 200 "scanner.c" */
yy6:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 128) {
				goto yy296;
			}
yy7:
/* #line 478 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 212 "scanner.c" */
yy8:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 64) {
				goto yy292;
			}
yy9:
/* #line 358 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 225 "scanner.c" */
yy10:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'S') {
				if (yych == 'P') goto yy281;
				if (yych <= 'R') goto yy98;
				goto yy282;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy98;
					goto yy281;
				} else {
					if (yych == 's') goto yy282;
					goto yy98;
				}
			}
yy11:
/* #line 301 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 260 "scanner.c" */
yy12:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy273;
			if (yych == 'e') goto yy273;
			goto yy98;
yy13:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy256;
				if (yych <= 'H') goto yy98;
				goto yy257;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy98;
					goto yy256;
				} else {
					if (yych == 'i') goto yy257;
					goto yy98;
				}
			}
yy14:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'Q') {
					if (yych == 'A') goto yy243;
					goto yy98;
				} else {
					if (yych <= 'R') goto yy244;
					if (yych <= 'T') goto yy98;
					goto yy245;
				}
			} else {
				if (yych <= 'q') {
					if (yych == 'a') goto yy243;
					goto yy98;
				} else {
					if (yych <= 'r') goto yy244;
					if (yych == 'u') goto yy245;
					goto yy98;
				}
			}
yy15:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'L') {
					if (yych == 'G') goto yy226;
					if (yych <= 'K') goto yy98;
					goto yy227;
				} else {
					if (yych == 'N') goto yy228;
					if (yych <= 'R') goto yy98;
					goto yy229;
				}
			} else {
				if (yych <= 'l') {
					if (yych == 'g') goto yy226;
					if (yych <= 'k') goto yy98;
					goto yy227;
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy98;
						goto yy228;
					} else {
						if (yych == 's') goto yy229;
						goto yy98;
					}
				}
			}
yy16:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy205;
					goto yy98;
				} else {
					if (yych <= 'N') goto yy206;
					if (yych <= 'R') goto yy98;
					goto yy208;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy205;
					goto yy98;
				} else {
					if (yych <= 'n') goto yy206;
					if (yych == 's') goto yy208;
					goto yy98;
				}
			}
yy17:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy199;
			if (yych == 'a') goto yy199;
			goto yy98;
yy18:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy194;
			if (yych == 'h') goto yy194;
			goto yy98;
yy19:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy175;
					if (yych <= 'M') goto yy98;
					goto yy176;
				} else {
					if (yych == 'R') goto yy178;
					if (yych <= 'T') goto yy98;
					goto yy180;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy175;
					if (yych <= 'm') goto yy98;
					goto yy176;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy98;
						goto yy178;
					} else {
						if (yych == 'u') goto yy180;
						goto yy98;
					}
				}
			}
yy20:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy166;
				if (yych <= 'X') goto yy98;
				goto yy167;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy98;
					goto yy166;
				} else {
					if (yych == 'y') goto yy167;
					goto yy98;
				}
			}
yy21:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy161;
			if (yych == 'r') goto yy161;
			goto yy98;
yy22:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy155;
			if (yych == 'a') goto yy155;
			goto yy98;
yy23:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy143;
				if (yych <= 'H') goto yy98;
				goto yy144;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy98;
					goto yy143;
				} else {
					if (yych == 'i') goto yy144;
					goto yy98;
				}
			}
yy24:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy136;
				if (yych <= 'T') goto yy98;
				goto yy137;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy98;
					goto yy136;
				} else {
					if (yych == 'u') goto yy137;
					goto yy98;
				}
			}
yy25:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy132;
			if (yych == 'o') goto yy132;
			goto yy98;
yy26:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy127;
			if (yych == 'i') goto yy127;
			goto yy98;
yy27:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy111;
					goto yy98;
				} else {
					if (yych <= 'O') goto yy112;
					if (yych <= 'Q') goto yy98;
					goto yy113;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy111;
					goto yy98;
				} else {
					if (yych <= 'o') goto yy112;
					if (yych == 'r') goto yy113;
					goto yy98;
				}
			}
yy28:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy107;
			if (yych == 'r') goto yy107;
			goto yy98;
yy29:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy7;
			goto yy105;
yy30:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy7;
			goto yy100;
yy31:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy7;
				if (yych <= 'Z') goto yy97;
				goto yy7;
			} else {
				if (yych == '`') goto yy7;
				if (yych <= 'z') goto yy97;
				goto yy7;
			}
yy32:
			yych = *++YYCURSOR;
			goto yy98;
yy33:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy7;
				if (yych == '[') goto yy7;
				goto yy92;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy7;
					goto yy92;
				} else {
					if (yych <= '`') goto yy7;
					if (yych <= 'z') goto yy92;
					goto yy7;
				}
			}
yy34:
			++YYCURSOR;
/* #line 328 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 526 "scanner.c" */
yy36:
			++YYCURSOR;
/* #line 333 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 534 "scanner.c" */
yy38:
			++YYCURSOR;
/* #line 338 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 542 "scanner.c" */
yy40:
			++YYCURSOR;
/* #line 343 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 550 "scanner.c" */
yy42:
			++YYCURSOR;
/* #line 348 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 558 "scanner.c" */
yy44:
			++YYCURSOR;
/* #line 363 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 566 "scanner.c" */
yy46:
			++YYCURSOR;
/* #line 368 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 574 "scanner.c" */
yy48:
			++YYCURSOR;
/* #line 373 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 582 "scanner.c" */
yy50:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy88;
			if (yych == '=') goto yy90;
/* #line 443 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 592 "scanner.c" */
yy52:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy53;
			if (yych <= '=') goto yy84;
			if (yych <= '>') goto yy86;
yy53:
/* #line 398 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 604 "scanner.c" */
yy54:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy82;
/* #line 403 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 613 "scanner.c" */
yy56:
			++YYCURSOR;
/* #line 408 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 621 "scanner.c" */
yy58:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy78;
			if (yych == '@') goto yy80;
			goto yy7;
yy59:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy76;
/* #line 463 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 635 "scanner.c" */
yy61:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy74;
/* #line 458 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 644 "scanner.c" */
yy63:
			++YYCURSOR;
/* #line 448 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 652 "scanner.c" */
yy65:
			++YYCURSOR;
/* #line 453 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 660 "scanner.c" */
yy67:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy73;
yy68:
/* #line 468 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 671 "scanner.c" */
yy69:
			++YYCURSOR;
/* #line 473 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 679 "scanner.c" */
yy71:
			yych = *++YYCURSOR;
			goto yy7;
yy72:
			++YYCURSOR;
			yych = *YYCURSOR;
yy73:
			if (yybm[0+yych] & 4) {
				goto yy72;
			}
			goto yy68;
yy74:
			++YYCURSOR;
/* #line 423 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 698 "scanner.c" */
yy76:
			++YYCURSOR;
/* #line 418 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 706 "scanner.c" */
yy78:
			++YYCURSOR;
/* #line 433 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 714 "scanner.c" */
yy80:
			++YYCURSOR;
/* #line 413 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 722 "scanner.c" */
yy82:
			++YYCURSOR;
/* #line 393 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 730 "scanner.c" */
yy84:
			++YYCURSOR;
/* #line 388 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 738 "scanner.c" */
yy86:
			++YYCURSOR;
/* #line 383 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 746 "scanner.c" */
yy88:
			++YYCURSOR;
/* #line 428 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 754 "scanner.c" */
yy90:
			++YYCURSOR;
/* #line 378 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 762 "scanner.c" */
yy92:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 8) {
				goto yy92;
			}
			if (yych == ']') goto yy95;
yy94:
			YYCURSOR = YYMARKER;
			if (yyaccept <= 0) {
				goto yy9;
			} else {
				goto yy7;
			}
yy95:
			++YYCURSOR;
/* #line 320 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 787 "scanner.c" */
yy97:
			++YYCURSOR;
			yych = *YYCURSOR;
yy98:
			if (yych <= '[') {
				if (yych <= '9') {
					if (yych <= '/') goto yy11;
					goto yy97;
				} else {
					if (yych <= '@') goto yy11;
					if (yych <= 'Z') goto yy97;
					goto yy11;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych <= '^') goto yy11;
					goto yy97;
				} else {
					if (yych <= '`') goto yy11;
					if (yych <= 'z') goto yy97;
					goto yy11;
				}
			}
yy99:
			++YYCURSOR;
			yych = *YYCURSOR;
yy100:
			if (yybm[0+yych] & 16) {
				goto yy99;
			}
			if (yych <= 0x00) goto yy94;
			if (yych <= '[') goto yy102;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy94;
			goto yy99;
yy102:
			++YYCURSOR;
/* #line 292 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 835 "scanner.c" */
yy104:
			++YYCURSOR;
			yych = *YYCURSOR;
yy105:
			if (yybm[0+yych] & 32) {
				goto yy104;
			}
			if (yych <= 0x00) goto yy94;
			if (yych <= '[') goto yy102;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy94;
			goto yy104;
yy107:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy108;
			if (yych != 'u') goto yy98;
yy108:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy109;
			if (yych != 'e') goto yy98;
yy109:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy110;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy110;
					if (yych <= 'z') goto yy97;
				}
			}
yy110:
/* #line 281 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 881 "scanner.c" */
yy111:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy124;
			if (yych == 's') goto yy124;
			goto yy98;
yy112:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy118;
			if (yych == 'n') goto yy118;
			goto yy98;
yy113:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy114;
			if (yych != 'o') goto yy98;
yy114:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy115;
			if (yych != 's') goto yy98;
yy115:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy116;
			if (yych != 's') goto yy98;
yy116:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy117;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy117;
					if (yych <= 'z') goto yy97;
				}
			}
yy117:
/* #line 226 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 928 "scanner.c" */
yy118:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy119;
			if (yych != 'v') goto yy98;
yy119:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy120;
			if (yych != 'e') goto yy98;
yy120:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy121;
			if (yych != 'r') goto yy98;
yy121:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy122;
			if (yych != 't') goto yy98;
yy122:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy123;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy123;
					if (yych <= 'z') goto yy97;
				}
			}
yy123:
/* #line 271 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 969 "scanner.c" */
yy124:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy125;
			if (yych != 't') goto yy98;
yy125:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy126;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy126;
					if (yych <= 'z') goto yy97;
				}
			}
yy126:
/* #line 266 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 998 "scanner.c" */
yy127:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy128;
			if (yych != 'g') goto yy98;
yy128:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy129;
			if (yych != 'h') goto yy98;
yy129:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy130;
			if (yych != 't') goto yy98;
yy130:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy131;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy131;
					if (yych <= 'z') goto yy97;
				}
			}
yy131:
/* #line 221 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 1035 "scanner.c" */
yy132:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy133;
			if (yych != 'i') goto yy98;
yy133:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy134;
			if (yych != 'n') goto yy98;
yy134:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy135;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy135;
					if (yych <= 'z') goto yy97;
				}
			}
yy135:
/* #line 206 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1068 "scanner.c" */
yy136:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy141;
			if (yych == 't') goto yy141;
			goto yy98;
yy137:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy138;
			if (yych != 'l') goto yy98;
yy138:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy139;
			if (yych != 'l') goto yy98;
yy139:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy140;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy140;
					if (yych <= 'z') goto yy97;
				}
			}
yy140:
/* #line 246 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1106 "scanner.c" */
yy141:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy142;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy142;
					if (yych <= 'z') goto yy97;
				}
			}
yy142:
/* #line 166 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1131 "scanner.c" */
yy143:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy152;
			if (yych == 'f') goto yy152;
			goto yy98;
yy144:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy146;
				if (yych <= 'L') goto yy98;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy98;
					goto yy146;
				} else {
					if (yych != 'm') goto yy98;
				}
			}
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy149;
			if (yych == 'i') goto yy149;
			goto yy98;
yy146:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy147;
			if (yych != 'e') goto yy98;
yy147:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy148;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy148;
					if (yych <= 'z') goto yy97;
				}
			}
yy148:
/* #line 181 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1182 "scanner.c" */
yy149:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy150;
			if (yych != 't') goto yy98;
yy150:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy151;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy151;
					if (yych <= 'z') goto yy97;
				}
			}
yy151:
/* #line 156 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 1211 "scanner.c" */
yy152:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy153;
			if (yych != 't') goto yy98;
yy153:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy154;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy154;
					if (yych <= 'z') goto yy97;
				}
			}
yy154:
/* #line 216 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1240 "scanner.c" */
yy155:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy156;
			if (yych != 'v') goto yy98;
yy156:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy157;
			if (yych != 'i') goto yy98;
yy157:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy158;
			if (yych != 'n') goto yy98;
yy158:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy159;
			if (yych != 'g') goto yy98;
yy159:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy160;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy160;
					if (yych <= 'z') goto yy97;
				}
			}
yy160:
/* #line 151 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 1281 "scanner.c" */
yy161:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy162;
			if (yych != 'o') goto yy98;
yy162:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy163;
			if (yych != 'u') goto yy98;
yy163:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy164;
			if (yych != 'p') goto yy98;
yy164:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy165;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy165;
					if (yych <= 'z') goto yy97;
				}
			}
yy165:
/* #line 146 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1318 "scanner.c" */
yy166:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy169;
			if (yych == 't') goto yy169;
			goto yy98;
yy167:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy168;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy168;
					if (yych <= 'z') goto yy97;
				}
			}
yy168:
/* #line 131 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 1348 "scanner.c" */
yy169:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy170;
			if (yych != 'w') goto yy98;
yy170:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy171;
			if (yych != 'e') goto yy98;
yy171:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy172;
			if (yych != 'e') goto yy98;
yy172:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy173;
			if (yych != 'n') goto yy98;
yy173:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy174;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy174;
					if (yych <= 'z') goto yy97;
				}
			}
yy174:
/* #line 261 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 1389 "scanner.c" */
yy175:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy189;
			if (yych == 'f') goto yy189;
			goto yy98;
yy176:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy177;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy177;
					if (yych <= 'z') goto yy97;
				}
			}
yy177:
/* #line 201 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1419 "scanner.c" */
yy178:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy179;
					if (yych <= '9') goto yy97;
				} else {
					if (yych == 'D') goto yy185;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy97;
					if (yych == '_') goto yy97;
				} else {
					if (yych == 'd') goto yy185;
					if (yych <= 'z') goto yy97;
				}
			}
yy179:
/* #line 176 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1445 "scanner.c" */
yy180:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy181;
			if (yych != 't') goto yy98;
yy181:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy182;
			if (yych != 'e') goto yy98;
yy182:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy183;
			if (yych != 'r') goto yy98;
yy183:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy184;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy184;
					if (yych <= 'z') goto yy97;
				}
			}
yy184:
/* #line 231 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 1482 "scanner.c" */
yy185:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy186;
			if (yych != 'e') goto yy98;
yy186:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy187;
			if (yych != 'r') goto yy98;
yy187:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy188;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy188;
					if (yych <= 'z') goto yy97;
				}
			}
yy188:
/* #line 126 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 1515 "scanner.c" */
yy189:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy190;
			if (yych != 's') goto yy98;
yy190:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy191;
			if (yych != 'e') goto yy98;
yy191:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy192;
			if (yych != 't') goto yy98;
yy192:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy193;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy193;
					if (yych <= 'z') goto yy97;
				}
			}
yy193:
/* #line 161 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 1552 "scanner.c" */
yy194:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy195;
			if (yych != 'e') goto yy98;
yy195:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy196;
			if (yych != 'r') goto yy98;
yy196:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy197;
			if (yych != 'e') goto yy98;
yy197:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy198;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy198;
					if (yych <= 'z') goto yy97;
				}
			}
yy198:
/* #line 116 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 1589 "scanner.c" */
yy199:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy200;
			if (yych != 'l') goto yy98;
yy200:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy201;
			if (yych != 'u') goto yy98;
yy201:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy202;
			if (yych != 'e') goto yy98;
yy202:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy203;
			if (yych != 's') goto yy98;
yy203:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy204;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy204;
					if (yych <= 'z') goto yy97;
				}
			}
yy204:
/* #line 111 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 1630 "scanner.c" */
yy205:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy222;
			if (yych == 'i') goto yy222;
			goto yy98;
yy206:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= '9') {
						if (yych >= '0') goto yy97;
					} else {
						if (yych <= '@') goto yy207;
						if (yych <= 'M') goto yy97;
						goto yy212;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy97;
						goto yy210;
					} else {
						if (yych <= 'T') goto yy211;
						if (yych <= 'Z') goto yy97;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy97;
					} else {
						if (yych != '`') goto yy97;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy212;
						if (yych <= 'r') goto yy97;
						goto yy210;
					} else {
						if (yych <= 't') goto yy211;
						if (yych <= 'z') goto yy97;
					}
				}
			}
yy207:
/* #line 196 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1680 "scanner.c" */
yy208:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy209;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy209;
					if (yych <= 'z') goto yy97;
				}
			}
yy209:
/* #line 241 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1705 "scanner.c" */
yy210:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy218;
			if (yych == 'e') goto yy218;
			goto yy98;
yy211:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy216;
			if (yych == 'o') goto yy216;
			goto yy98;
yy212:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy213;
			if (yych != 'e') goto yy98;
yy213:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy214;
			if (yych != 'r') goto yy98;
yy214:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy215;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy215;
					if (yych <= 'z') goto yy97;
				}
			}
yy215:
/* #line 211 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 1748 "scanner.c" */
yy216:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy217;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy217;
					if (yych <= 'z') goto yy97;
				}
			}
yy217:
/* #line 106 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1773 "scanner.c" */
yy218:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy219;
			if (yych != 'r') goto yy98;
yy219:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy220;
			if (yych != 't') goto yy98;
yy220:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy221;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy221;
					if (yych <= 'z') goto yy97;
				}
			}
yy221:
/* #line 101 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 1806 "scanner.c" */
yy222:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy223;
			if (yych != 'k') goto yy98;
yy223:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy224;
			if (yych != 'e') goto yy98;
yy224:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy225;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy225;
					if (yych <= 'z') goto yy97;
				}
			}
yy225:
/* #line 186 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 1839 "scanner.c" */
yy226:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy237;
			if (yych == 'a') goto yy237;
			goto yy98;
yy227:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy235;
			if (yych == 'l') goto yy235;
			goto yy98;
yy228:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy233;
			if (yych == 'd') goto yy233;
			goto yy98;
yy229:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy230;
					if (yych <= '9') goto yy97;
				} else {
					if (yych == 'C') goto yy231;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy97;
					if (yych == '_') goto yy97;
				} else {
					if (yych == 'c') goto yy231;
					if (yych <= 'z') goto yy97;
				}
			}
yy230:
/* #line 96 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 1880 "scanner.c" */
yy231:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy232;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy232;
					if (yych <= 'z') goto yy97;
				}
			}
yy232:
/* #line 136 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 1905 "scanner.c" */
yy233:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy234;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy234;
					if (yych <= 'z') goto yy97;
				}
			}
yy234:
/* #line 171 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 1930 "scanner.c" */
yy235:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy236;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy236;
					if (yych <= 'z') goto yy97;
				}
			}
yy236:
/* #line 256 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 1955 "scanner.c" */
yy237:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy238;
			if (yych != 'i') goto yy98;
yy238:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy239;
			if (yych != 'n') goto yy98;
yy239:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy240;
			if (yych != 's') goto yy98;
yy240:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy241;
			if (yych != 't') goto yy98;
yy241:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy242;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy242;
					if (yych <= 'z') goto yy97;
				}
			}
yy242:
/* #line 191 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 1996 "scanner.c" */
yy243:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy252;
			if (yych == 'l') goto yy252;
			goto yy98;
yy244:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy249;
			if (yych == 'o') goto yy249;
			goto yy98;
yy245:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy246;
			if (yych != 'l') goto yy98;
yy246:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy247;
			if (yych != 'l') goto yy98;
yy247:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy248;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy248;
					if (yych <= 'z') goto yy97;
				}
			}
yy248:
/* #line 236 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 2039 "scanner.c" */
yy249:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy250;
			if (yych != 'm') goto yy98;
yy250:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy251;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy251;
					if (yych <= 'z') goto yy97;
				}
			}
yy251:
/* #line 91 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 2068 "scanner.c" */
yy252:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy253;
			if (yych != 's') goto yy98;
yy253:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy254;
			if (yych != 'e') goto yy98;
yy254:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy255;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy255;
					if (yych <= 'z') goto yy97;
				}
			}
yy255:
/* #line 286 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2101 "scanner.c" */
yy256:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy265;
				if (yych <= 'R') goto yy98;
				goto yy266;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy98;
					goto yy265;
				} else {
					if (yych == 's') goto yy266;
					goto yy98;
				}
			}
yy257:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy258;
			if (yych != 's') goto yy98;
yy258:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy259;
			if (yych != 't') goto yy98;
yy259:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy260;
			if (yych != 'i') goto yy98;
yy260:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy261;
			if (yych != 'n') goto yy98;
yy261:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy262;
			if (yych != 'c') goto yy98;
yy262:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy263;
			if (yych != 't') goto yy98;
yy263:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy264;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy264;
					if (yych <= 'z') goto yy97;
				}
			}
yy264:
/* #line 251 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2165 "scanner.c" */
yy265:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy269;
			if (yych == 'e') goto yy269;
			goto yy98;
yy266:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy267;
			if (yych != 'c') goto yy98;
yy267:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy268;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy268;
					if (yych <= 'z') goto yy97;
				}
			}
yy268:
/* #line 141 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 2199 "scanner.c" */
yy269:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy270;
			if (yych != 't') goto yy98;
yy270:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy271;
			if (yych != 'e') goto yy98;
yy271:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy272;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy272;
					if (yych <= 'z') goto yy97;
				}
			}
yy272:
/* #line 86 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2232 "scanner.c" */
yy273:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy276;
				if (yych <= 'S') goto yy98;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy98;
					goto yy276;
				} else {
					if (yych != 't') goto yy98;
				}
			}
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy275;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy275;
					if (yych <= 'z') goto yy97;
				}
			}
yy275:
/* #line 81 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 2269 "scanner.c" */
yy276:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy277;
			if (yych != 'e') goto yy98;
yy277:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy278;
			if (yych != 'c') goto yy98;
yy278:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy279;
			if (yych != 't') goto yy98;
yy279:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy280;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy280;
					if (yych <= 'z') goto yy97;
				}
			}
yy280:
/* #line 121 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 2306 "scanner.c" */
yy281:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy287;
			if (yych == 'd') goto yy287;
			goto yy98;
yy282:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy283;
			if (yych != 'i') goto yy98;
yy283:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy284;
			if (yych != 'n') goto yy98;
yy284:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy285;
			if (yych != 'g') goto yy98;
yy285:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy286;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy286;
					if (yych <= 'z') goto yy97;
				}
			}
yy286:
/* #line 276 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 2348 "scanner.c" */
yy287:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy288;
			if (yych != 'a') goto yy98;
yy288:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy289;
			if (yych != 't') goto yy98;
yy289:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy290;
			if (yych != 'e') goto yy98;
yy290:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '9') {
					if (yych >= '0') goto yy97;
				} else {
					if (yych <= '@') goto yy291;
					if (yych <= 'Z') goto yy97;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy97;
					if (yych >= '_') goto yy97;
				} else {
					if (yych <= '`') goto yy291;
					if (yych <= 'z') goto yy97;
				}
			}
yy291:
/* #line 76 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 2385 "scanner.c" */
yy292:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy292;
			}
			if (yych != ':') goto yy94;
			++YYCURSOR;
/* #line 68 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2402 "scanner.c" */
yy296:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy296;
			}
/* #line 59 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2417 "scanner.c" */
yy299:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy301;
			if (yych <= '9') goto yy299;
yy301:
/* #line 50 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2432 "scanner.c" */
yy302:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy301;
			if (yych <= '9') goto yy302;
			goto yy301;
yy304:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '.') goto yy302;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy304;
			goto yy3;
		}
/* #line 483 "scanner.re" */

	}

	return status;
}
