
extern zend_class_entry *phalcon_mvc_router_exceptions_emptygroupofroutes_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Router_Exceptions_EmptyGroupOfRoutes);

PHP_METHOD(Phalcon_Mvc_Router_Exceptions_EmptyGroupOfRoutes, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_router_exceptions_emptygroupofroutes___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_router_exceptions_emptygroupofroutes_method_entry) {
PHP_ME(Phalcon_Mvc_Router_Exceptions_EmptyGroupOfRoutes, __construct, arginfo_phalcon_mvc_router_exceptions_emptygroupofroutes___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
