
extern zend_class_entry *phalcon_mvc_router_exceptions_grouproutesmustbearray_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Router_Exceptions_GroupRoutesMustBeArray);

PHP_METHOD(Phalcon_Mvc_Router_Exceptions_GroupRoutesMustBeArray, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_router_exceptions_grouproutesmustbearray___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_router_exceptions_grouproutesmustbearray_method_entry) {
PHP_ME(Phalcon_Mvc_Router_Exceptions_GroupRoutesMustBeArray, __construct, arginfo_phalcon_mvc_router_exceptions_grouproutesmustbearray___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
