
extern zend_class_entry *phalcon_mvc_router_exceptions_missinggrouproutekey_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Router_Exceptions_MissingGroupRouteKey);

PHP_METHOD(Phalcon_Mvc_Router_Exceptions_MissingGroupRouteKey, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_router_exceptions_missinggrouproutekey___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, key, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_router_exceptions_missinggrouproutekey_method_entry) {
	PHP_ME(Phalcon_Mvc_Router_Exceptions_MissingGroupRouteKey, __construct, arginfo_phalcon_mvc_router_exceptions_missinggrouproutekey___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
