
/**
 * This file is part of the Phalcon Framework.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace Phalcon\Mvc\Model;

use Phalcon\Contracts\Mvc\MvcTypes;
use Phalcon\Mvc\ModelInterface;

/**
 * Phalcon\Mvc\Model\QueryInterface
 *
 * Interface for Phalcon\Mvc\Model\Query
 *
 * @phpstan-import-type mvc_model_bind_params from MvcTypes
 * @phpstan-import-type mvc_model_bind_types from MvcTypes
 * @phpstan-import-type mvc_model_cache_options from MvcTypes
 * @phpstan-import-type mvc_query_ir from MvcTypes
 */
interface QueryInterface
{
    /**
     * Sets the cache parameters of the query
     *
     * @phpstan-param mvc_model_cache_options $cacheOptions
     */
    public function cache(array cacheOptions) -> <QueryInterface>;

    /**
     * Executes a parsed PHQL statement
     *
     * @return mixed
     *
     * @phpstan-param mvc_model_bind_params $bindParams
     * @phpstan-param mvc_model_bind_types $bindTypes
     */
    public function execute(array bindParams = [], array bindTypes = []);

    /**
     * Returns default bind params
     *
     * @phpstan-return mvc_model_bind_params
     */
    public function getBindParams() -> array;

    /**
     * Returns default bind types
     *
     * @phpstan-return mvc_model_bind_types
     */
    public function getBindTypes() -> array;

    /**
     * Returns the current cache options
     *
     * @phpstan-return mvc_model_cache_options
     */
    public function getCacheOptions() -> array;

    /**
     * Executes the query returning the first result
     *
     * @phpstan-param mvc_model_bind_params $bindParams
     * @phpstan-param mvc_model_bind_types $bindTypes
     */
    public function getSingleResult(array bindParams = [], array bindTypes = []) -> <ModelInterface>;

    /**
     * Returns the SQL to be generated by the internal PHQL (only works in SELECT statements)
     *
     * @phpstan-return array<string, mixed>
     */
    public function getSql() -> array;

    /**
     * Check if the query is programmed to get only the first row in the resultset
     */
    public function getUniqueRow() -> bool;

    /**
     * Parses the intermediate code produced by Phalcon\Mvc\Model\Query\Lang generating another
     * intermediate representation that could be executed by Phalcon\Mvc\Model\Query
     *
     * @phpstan-return mvc_query_ir
     */
    public function parse() -> array;

    /**
     * Set default bind parameters
     *
     * @phpstan-param mvc_model_bind_params $bindParams
     */
    public function setBindParams( array bindParams, bool merge = false) -> <QueryInterface>;

    /**
     * Set default bind parameters
     *
     * @phpstan-param mvc_model_bind_types $bindTypes
     */
    public function setBindTypes( array bindTypes, bool merge = false) -> <QueryInterface>;

    /**
     * Set SHARED LOCK clause
     */
    public function setSharedLock(bool sharedLock = false) -> <QueryInterface>;

    /**
     * Tells to the query if only the first row in the resultset must be returned
     */
    public function setUniqueRow(bool uniqueRow) -> <QueryInterface>;

    // TODO v7: promote the custom resultset-row-class accessors into this
    // interface. They are implemented on Phalcon\Mvc\Model\Query but are kept
    // out of the contract in 5.x to avoid breaking existing QueryInterface
    // implementations in the wild.
    //
    // public function getResultsetRowClass() -> string;
    // public function setResultsetRowClass(string resultsetRowClass) -> <QueryInterface>;
}
