
extern zend_class_entry *phalcon_db_geometry_abstractgeometry_ce;

ZEPHIR_INIT_CLASS(Phalcon_Db_Geometry_AbstractGeometry);

PHP_METHOD(Phalcon_Db_Geometry_AbstractGeometry, getType);
PHP_METHOD(Phalcon_Db_Geometry_AbstractGeometry, toWkt);
PHP_METHOD(Phalcon_Db_Geometry_AbstractGeometry, getSrid);
PHP_METHOD(Phalcon_Db_Geometry_AbstractGeometry, __toString);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_db_geometry_abstractgeometry_gettype, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_db_geometry_abstractgeometry_towkt, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_db_geometry_abstractgeometry_getsrid, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_db_geometry_abstractgeometry___tostring, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_db_geometry_abstractgeometry_method_entry) {
	PHP_ME(Phalcon_Db_Geometry_AbstractGeometry, getType, arginfo_phalcon_db_geometry_abstractgeometry_gettype, ZEND_ACC_ABSTRACT|ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Db_Geometry_AbstractGeometry, toWkt, arginfo_phalcon_db_geometry_abstractgeometry_towkt, ZEND_ACC_ABSTRACT|ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Db_Geometry_AbstractGeometry, getSrid, arginfo_phalcon_db_geometry_abstractgeometry_getsrid, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Db_Geometry_AbstractGeometry, __toString, arginfo_phalcon_db_geometry_abstractgeometry___tostring, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
