
extern zend_class_entry *phalcon_contracts_events_stoppable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Events_Stoppable);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_events_stoppable_ispropagationstopped, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_events_stoppable_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Events_Stoppable, isPropagationStopped, arginfo_phalcon_contracts_events_stoppable_ispropagationstopped)
	PHP_FE_END
};
