
extern zend_class_entry *phalcon_mvc_model_binder_bindableinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_Binder_BindableInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_model_binder_bindableinterface_getmodelname, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_binder_bindableinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Mvc_Model_Binder_BindableInterface, getModelName, arginfo_phalcon_mvc_model_binder_bindableinterface_getmodelname)
	PHP_FE_END
};
