
extern zend_class_entry *phalcon_auth_adapter_config_modeladapterconfig_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_Adapter_Config_ModelAdapterConfig);

PHP_METHOD(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, __construct);
PHP_METHOD(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, getIdColumn);
PHP_METHOD(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, getModel);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_auth_adapter_config_modeladapterconfig___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, model, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, idColumn, IS_STRING, 0, "'id'")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_adapter_config_modeladapterconfig_getidcolumn, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_adapter_config_modeladapterconfig_getmodel, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_adapter_config_modeladapterconfig_method_entry) {
	PHP_ME(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, __construct, arginfo_phalcon_auth_adapter_config_modeladapterconfig___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, getIdColumn, arginfo_phalcon_auth_adapter_config_modeladapterconfig_getidcolumn, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Auth_Adapter_Config_ModelAdapterConfig, getModel, arginfo_phalcon_auth_adapter_config_modeladapterconfig_getmodel, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
