array(1) {
  [0]=>
  array(5) {
    ["type"]=>
    int(411)
    ["expr"]=>
    array(4) {
      ["type"]=>
      int(265)
      ["value"]=>
      string(3) "foo"
      ["file"]=>
      string(9) "eval code"
      ["line"]=>
      int(1)
    }
    ["case_clauses"]=>
    array(3) {
      [0]=>
      array(4) {
        ["type"]=>
        int(357)
        ["value"]=>
        string(1) " "
        ["file"]=>
        string(9) "eval code"
        ["line"]=>
        int(1)
      }
      [1]=>
      array(3) {
        ["type"]=>
        int(413)
        ["file"]=>
        string(9) "eval code"
        ["line"]=>
        int(1)
      }
      [2]=>
      array(4) {
        ["type"]=>
        int(357)
        ["value"]=>
        string(1) " "
        ["file"]=>
        string(9) "eval code"
        ["line"]=>
        int(1)
      }
    }
    ["file"]=>
    string(9) "eval code"
    ["line"]=>
    int(1)
  }
}