
extern zend_class_entry *phalcon_http_response_exceptions_urlserviceunavailable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Http_Response_Exceptions_UrlServiceUnavailable);

PHP_METHOD(Phalcon_Http_Response_Exceptions_UrlServiceUnavailable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_http_response_exceptions_urlserviceunavailable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_http_response_exceptions_urlserviceunavailable_method_entry) {
PHP_ME(Phalcon_Http_Response_Exceptions_UrlServiceUnavailable, __construct, arginfo_phalcon_http_response_exceptions_urlserviceunavailable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
