
extern zend_class_entry *phalcon_http_traits_encryptionawaretrait_ce;

ZEPHIR_INIT_CLASS(Phalcon_Http_Traits_EncryptionAwareTrait);

PHP_METHOD(Phalcon_Http_Traits_EncryptionAwareTrait, isUsingEncryption);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_http_traits_encryptionawaretrait_isusingencryption, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_http_traits_encryptionawaretrait_method_entry) {
	PHP_ME(Phalcon_Http_Traits_EncryptionAwareTrait, isUsingEncryption, arginfo_phalcon_http_traits_encryptionawaretrait_isusingencryption, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
