
extern zend_class_entry *phalcon_contracts_auth_adapter_adapterconfig_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Auth_Adapter_AdapterConfig);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_auth_adapter_adapterconfig_getmodel, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_auth_adapter_adapterconfig_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Auth_Adapter_AdapterConfig, getModel, arginfo_phalcon_contracts_auth_adapter_adapterconfig_getmodel)
	PHP_FE_END
};
