
extern zend_class_entry *phalcon_mvc_model_validator_inclusionin_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_Validator_InclusionIn);

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_validator_inclusionin_method_entry) {
	PHP_FE_END
};
