name: 'Phalcon PHP extension build action (macOS)'
description: 'Build Phalcon Framework for macOS according to various PHP versions.'

inputs:
  source:
    description: 'Path to extension source directory (build/phalcon)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure macOS Environment
      shell: bash
      run: xcodebuild -version

    - name: Install System Dependencies
      shell: bash
      run: brew install pcre2 re2c

    - name: Build Phalcon Extension
      shell: bash
      working-directory: ${{ inputs.source }}
      run: |
        export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
        export CPPFLAGS="-I$(brew --prefix pcre2)/include ${CPPFLAGS:-}"
        export LDFLAGS="-L$(brew --prefix pcre2)/lib ${LDFLAGS:-}"
        echo "::group::Build Phalcon extension"
        phpize
        ./configure --enable-phalcon
        make
        sudo make install
        echo "::endgroup::"

    - name: Enable extension
      shell: bash
      run: |
        SCAN_DIR=$(php -r 'echo PHP_CONFIG_FILE_SCAN_DIR;')
        sudo mkdir -p "$SCAN_DIR"
        echo "extension=phalcon" | sudo tee "$SCAN_DIR/99-phalcon.ini"

    - name: Check Phalcon Extension
      shell: bash
      run: php --ri phalcon