name: 'Phalcon PHP extension build action (macOS)'
description: 'Build Phalcon Framework for macOS according to various PHP versions.'

inputs:
  source:
    description: 'Path to extension source directory (build/phalcon)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure macOS Environment
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_14.2.app
        xcodebuild -version

    - name: Build Phalcon Extension
      shell: bash
      working-directory: ${{ inputs.source }}
      run: |
        export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
        echo "::group::Build Phalcon extension"
        phpize
        ./configure --enable-phalcon
        make
        sudo make install
        echo "::endgroup::"

    - name: Check Phalcon Extension
      shell: bash
      run: php --ri phalcon