
extern zend_class_entry *phalcon_mvc_model_behavior_exceptions_missingrequiredoption_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_Behavior_Exceptions_MissingRequiredOption);

PHP_METHOD(Phalcon_Mvc_Model_Behavior_Exceptions_MissingRequiredOption, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_model_behavior_exceptions_missingrequiredoption___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, option, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_behavior_exceptions_missingrequiredoption_method_entry) {
	PHP_ME(Phalcon_Mvc_Model_Behavior_Exceptions_MissingRequiredOption, __construct, arginfo_phalcon_mvc_model_behavior_exceptions_missingrequiredoption___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
