
extern zend_class_entry *phalcon_adr_router_traits_hasmiddleware_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Router_Traits_HasMiddleware);

PHP_METHOD(Phalcon_ADR_Router_Traits_HasMiddleware, getMiddleware);
PHP_METHOD(Phalcon_ADR_Router_Traits_HasMiddleware, pushMiddleware);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_adr_router_traits_hasmiddleware_getmiddleware, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_adr_router_traits_hasmiddleware_pushmiddleware, 0, 1, IS_VOID, 0)

	ZEND_ARG_ARRAY_INFO(0, classes, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_router_traits_hasmiddleware_method_entry) {
	PHP_ME(Phalcon_ADR_Router_Traits_HasMiddleware, getMiddleware, arginfo_phalcon_adr_router_traits_hasmiddleware_getmiddleware, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_ADR_Router_Traits_HasMiddleware, pushMiddleware, arginfo_phalcon_adr_router_traits_hasmiddleware_pushmiddleware, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
