
extern zend_class_entry *phalcon_queue_adapter_redis_redistopic_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Redis_RedisTopic);

PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisTopic, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisTopic, getTopicName);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_redis_redistopic___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, topicName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redistopic_gettopicname, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_redis_redistopic_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisTopic, __construct, arginfo_phalcon_queue_adapter_redis_redistopic___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisTopic, getTopicName, arginfo_phalcon_queue_adapter_redis_redistopic_gettopicname, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
