
extern zend_class_entry *phalcon_queue_adapter_redis_redissubscriptionconsumer_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer);

PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, consume);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, subscribe);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, unsubscribe);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, unsubscribeAll);
PHP_METHOD(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, resolveQueueName);
zend_object *zephir_init_properties_Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer(zend_class_entry *class_type);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer___construct, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, context, Phalcon\\Queue\\Adapter\\Redis\\RedisContext, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, pollInterval, IS_LONG, 0, "200")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_consume, 0, 0, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, timeout, IS_LONG, 0, "0")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_subscribe, 0, 2, IS_VOID, 0)

	ZEND_ARG_OBJ_INFO(0, consumer, Phalcon\\Contracts\\Queue\\Consumer, 0)
	ZEND_ARG_INFO(0, callback)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_unsubscribe, 0, 1, IS_VOID, 0)

	ZEND_ARG_OBJ_INFO(0, consumer, Phalcon\\Contracts\\Queue\\Consumer, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_unsubscribeall, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_resolvequeuename, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, consumer)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_zephir_init_properties_phalcon_queue_adapter_redis_redissubscriptionconsumer, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_redis_redissubscriptionconsumer_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, __construct, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, consume, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_consume, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, subscribe, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_subscribe, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, unsubscribe, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_unsubscribe, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, unsubscribeAll, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_unsubscribeall, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Redis_RedisSubscriptionConsumer, resolveQueueName, arginfo_phalcon_queue_adapter_redis_redissubscriptionconsumer_resolvequeuename, ZEND_ACC_PRIVATE)
	PHP_FE_END
};
