
extern zend_class_entry *phalcon_annotations_exceptions_cannotreadannotationdata_ce;

ZEPHIR_INIT_CLASS(Phalcon_Annotations_Exceptions_CannotReadAnnotationData);

PHP_METHOD(Phalcon_Annotations_Exceptions_CannotReadAnnotationData, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_annotations_exceptions_cannotreadannotationdata___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_annotations_exceptions_cannotreadannotationdata_method_entry) {
PHP_ME(Phalcon_Annotations_Exceptions_CannotReadAnnotationData, __construct, arginfo_phalcon_annotations_exceptions_cannotreadannotationdata___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
