
extern zend_class_entry *phalcon_annotations_exceptions_unknownannotationexpression_ce;

ZEPHIR_INIT_CLASS(Phalcon_Annotations_Exceptions_UnknownAnnotationExpression);

PHP_METHOD(Phalcon_Annotations_Exceptions_UnknownAnnotationExpression, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_annotations_exceptions_unknownannotationexpression___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, type, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_annotations_exceptions_unknownannotationexpression_method_entry) {
	PHP_ME(Phalcon_Annotations_Exceptions_UnknownAnnotationExpression, __construct, arginfo_phalcon_annotations_exceptions_unknownannotationexpression___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
