
extern zend_class_entry *phalcon_encryption_crypt_exception_missingopensslextension_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Crypt_Exception_MissingOpensslExtension);

PHP_METHOD(Phalcon_Encryption_Crypt_Exception_MissingOpensslExtension, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_crypt_exception_missingopensslextension___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_crypt_exception_missingopensslextension_method_entry) {
PHP_ME(Phalcon_Encryption_Crypt_Exception_MissingOpensslExtension, __construct, arginfo_phalcon_encryption_crypt_exception_missingopensslextension___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
