
extern zend_class_entry *phalcon_encryption_crypt_exception_unsupportedalgorithm_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Crypt_Exception_UnsupportedAlgorithm);

PHP_METHOD(Phalcon_Encryption_Crypt_Exception_UnsupportedAlgorithm, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_crypt_exception_unsupportedalgorithm___construct, 0, 0, 2)
	ZEND_ARG_TYPE_INFO(0, type, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cipher, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_crypt_exception_unsupportedalgorithm_method_entry) {
	PHP_ME(Phalcon_Encryption_Crypt_Exception_UnsupportedAlgorithm, __construct, arginfo_phalcon_encryption_crypt_exception_unsupportedalgorithm___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
