
extern zend_class_entry *phalcon_auth_guard_config_tokenguardconfig_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_Guard_Config_TokenGuardConfig);

PHP_METHOD(Phalcon_Auth_Guard_Config_TokenGuardConfig, __construct);
PHP_METHOD(Phalcon_Auth_Guard_Config_TokenGuardConfig, getInputKey);
PHP_METHOD(Phalcon_Auth_Guard_Config_TokenGuardConfig, getStorageKey);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_auth_guard_config_tokenguardconfig___construct, 0, 0, 2)
	ZEND_ARG_TYPE_INFO(0, inputKey, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, storageKey, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_guard_config_tokenguardconfig_getinputkey, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_auth_guard_config_tokenguardconfig_getstoragekey, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_guard_config_tokenguardconfig_method_entry) {
	PHP_ME(Phalcon_Auth_Guard_Config_TokenGuardConfig, __construct, arginfo_phalcon_auth_guard_config_tokenguardconfig___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Auth_Guard_Config_TokenGuardConfig, getInputKey, arginfo_phalcon_auth_guard_config_tokenguardconfig_getinputkey, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Auth_Guard_Config_TokenGuardConfig, getStorageKey, arginfo_phalcon_auth_guard_config_tokenguardconfig_getstoragekey, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
