#! /bin/sh

rm -f *.o
rm -f *.lo
if [ ! -f lemon ]; then
	gcc -g lemon.c -o lemon
fi
re2c -o scanner.c scanner.re && ./lemon -s parser.lemon && cat base.c >> parser.c
sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c