
extern zend_class_entry *phalcon_autoload_exceptions_loadermethodnotcallable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Autoload_Exceptions_LoaderMethodNotCallable);

PHP_METHOD(Phalcon_Autoload_Exceptions_LoaderMethodNotCallable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_autoload_exceptions_loadermethodnotcallable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_autoload_exceptions_loadermethodnotcallable_method_entry) {
PHP_ME(Phalcon_Autoload_Exceptions_LoaderMethodNotCallable, __construct, arginfo_phalcon_autoload_exceptions_loadermethodnotcallable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
