
extern zend_class_entry *phalcon_config_exceptions_groupedadapterrequiresarray_ce;

ZEPHIR_INIT_CLASS(Phalcon_Config_Exceptions_GroupedAdapterRequiresArray);

PHP_METHOD(Phalcon_Config_Exceptions_GroupedAdapterRequiresArray, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_config_exceptions_groupedadapterrequiresarray___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_config_exceptions_groupedadapterrequiresarray_method_entry) {
PHP_ME(Phalcon_Config_Exceptions_GroupedAdapterRequiresArray, __construct, arginfo_phalcon_config_exceptions_groupedadapterrequiresarray___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
