CREATE TABLE "table" (
	"column14" SERIAL NOT NULL,
	"column15" INT DEFAULT 5 NOT NULL,
	"column16" CHARACTER VARYING(10) DEFAULT 'column16' NULL,
	"column17" BOOLEAN DEFAULT false NOT NULL,
	"column18" BOOLEAN DEFAULT true NOT NULL
);
