
extern zend_class_entry *phalcon_contracts_container_ioc_ioccontainer_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Container_Ioc_IocContainer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_container_ioc_ioccontainer_hasservice, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, serviceName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_phalcon_contracts_container_ioc_ioccontainer_getservice, 0, 1, MAY_BE_OBJECT)
	ZEND_ARG_TYPE_INFO(0, serviceName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_container_ioc_ioccontainer_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Container_Ioc_IocContainer, hasService, arginfo_phalcon_contracts_container_ioc_ioccontainer_hasservice)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Container_Ioc_IocContainer, getService, arginfo_phalcon_contracts_container_ioc_ioccontainer_getservice)
	PHP_FE_END
};
