
extern zend_class_entry *phalcon_adr_exceptions_headersalreadysent_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Exceptions_HeadersAlreadySent);

PHP_METHOD(Phalcon_ADR_Exceptions_HeadersAlreadySent, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_adr_exceptions_headersalreadysent___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_exceptions_headersalreadysent_method_entry) {
PHP_ME(Phalcon_ADR_Exceptions_HeadersAlreadySent, __construct, arginfo_phalcon_adr_exceptions_headersalreadysent___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
