
extern zend_class_entry *phalcon_adr_exceptions_outputalreadysent_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Exceptions_OutputAlreadySent);

PHP_METHOD(Phalcon_ADR_Exceptions_OutputAlreadySent, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_adr_exceptions_outputalreadysent___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_exceptions_outputalreadysent_method_entry) {
PHP_ME(Phalcon_ADR_Exceptions_OutputAlreadySent, __construct, arginfo_phalcon_adr_exceptions_outputalreadysent___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
