
extern zend_class_entry *phalcon_adr_exceptions_routenotfound_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Exceptions_RouteNotFound);

PHP_METHOD(Phalcon_ADR_Exceptions_RouteNotFound, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_adr_exceptions_routenotfound___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_exceptions_routenotfound_method_entry) {
PHP_ME(Phalcon_ADR_Exceptions_RouteNotFound, __construct, arginfo_phalcon_adr_exceptions_routenotfound___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
