
extern zend_class_entry *phalcon_contracts_auth_remembertoken_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Auth_RememberToken);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_auth_remembertoken_delete, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_auth_remembertoken_gettoken, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_auth_remembertoken_getuseragent, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_auth_remembertoken_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Auth_RememberToken, delete, arginfo_phalcon_contracts_auth_remembertoken_delete)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Auth_RememberToken, getToken, arginfo_phalcon_contracts_auth_remembertoken_gettoken)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Auth_RememberToken, getUserAgent, arginfo_phalcon_contracts_auth_remembertoken_getuseragent)
	PHP_FE_END
};
