<?php

/**
 * This file is part of the Phalcon Framework.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Tests\Unit\Mvc\Model\Query\Phql\Select;

use Phalcon\Mvc\Model\Query\Lang;
use Phalcon\Tests\AbstractUnitTestCase;

final class HasManyToManyThroughAstTest extends AbstractUnitTestCase
{
    /**
     * The PHQL generated by the Manager for a hasManyToMany getRelated query.
     *
     * @author Phalcon Team <team@phalcon.io>
     * @since  2026-05-30
     */
    public function testMvcModelQueryPhqlSelectHasManyToManyThroughAst(): void
    {
        $source = 'SELECT [Phalcon\Tests\Support\Models\Products].* '
            . 'FROM [Phalcon\Tests\Support\Models\Products] '
            . 'INNER JOIN [Phalcon\Tests\Support\Models\OrdersProductsFieldsOne] '
            . 'ON [Phalcon\Tests\Support\Models\OrdersProductsFieldsOne].[oxp_prd_id] '
            . '= [Phalcon\Tests\Support\Models\Products].[prd_id] '
            . 'WHERE [Phalcon\Tests\Support\Models\OrdersProductsFieldsOne].[oxp_ord_id] = :APR0:';

        $expected = [
            'type'   => 309,
            'select' => [
                'columns' => [
                    0 => [
                        'type'   => 353,
                        'column' => 'Phalcon\Tests\Support\Models\Products',
                    ],
                ],
                'tables'  => [
                    'qualifiedName' => [
                        'type' => 355,
                        'name' => 'Phalcon\Tests\Support\Models\Products',
                    ],
                ],
                'joins'   => [
                    'type'       => 360,
                    'qualified'  => [
                        'type' => 355,
                        'name' => 'Phalcon\Tests\Support\Models\OrdersProductsFieldsOne',
                    ],
                    'conditions' => [
                        'type'  => 61,
                        'left'  => [
                            'type'   => 355,
                            'domain' => 'Phalcon\Tests\Support\Models\OrdersProductsFieldsOne',
                            'name'   => 'oxp_prd_id',
                        ],
                        'right' => [
                            'type'   => 355,
                            'domain' => 'Phalcon\Tests\Support\Models\Products',
                            'name'   => 'prd_id',
                        ],
                    ],
                ],
            ],
            'where'  => [
                'type'  => 61,
                'left'  => [
                    'type'   => 355,
                    'domain' => 'Phalcon\Tests\Support\Models\OrdersProductsFieldsOne',
                    'name'   => 'oxp_ord_id',
                ],
                'right' => [
                    'type'  => 274,
                    'value' => 'APR0',
                ],
            ],
        ];

        $actual = Lang::parsePhql($source);
        unset($actual['id']);
        $this->assertSame($expected, $actual);
    }
}
