
extern zend_class_entry *phalcon_storage_exceptions_databaseselectionfailed_ce;

ZEPHIR_INIT_CLASS(Phalcon_Storage_Exceptions_DatabaseSelectionFailed);

PHP_METHOD(Phalcon_Storage_Exceptions_DatabaseSelectionFailed, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_storage_exceptions_databaseselectionfailed___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_storage_exceptions_databaseselectionfailed_method_entry) {
PHP_ME(Phalcon_Storage_Exceptions_DatabaseSelectionFailed, __construct, arginfo_phalcon_storage_exceptions_databaseselectionfailed___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
