
extern zend_class_entry *phalcon_validation_validator_presenceof_ce;

ZEPHIR_INIT_CLASS(Phalcon_Validation_Validator_PresenceOf);

ZEPHIR_INIT_FUNCS(phalcon_validation_validator_presenceof_method_entry) {
	PHP_FE_END
};
