
extern zend_class_entry *phalcon_mvc_view_exceptions_invalidviewsdirtype_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_View_Exceptions_InvalidViewsDirType);

PHP_METHOD(Phalcon_Mvc_View_Exceptions_InvalidViewsDirType, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_view_exceptions_invalidviewsdirtype___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_view_exceptions_invalidviewsdirtype_method_entry) {
PHP_ME(Phalcon_Mvc_View_Exceptions_InvalidViewsDirType, __construct, arginfo_phalcon_mvc_view_exceptions_invalidviewsdirtype___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
