
extern zend_class_entry *phalcon_traits_support_helper_str_dirfromfiletrait_ce;

ZEPHIR_INIT_CLASS(Phalcon_Traits_Support_Helper_Str_DirFromFileTrait);

PHP_METHOD(Phalcon_Traits_Support_Helper_Str_DirFromFileTrait, toDirFromFile);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_traits_support_helper_str_dirfromfiletrait_todirfromfile, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, file, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, filesystemSafe, _IS_BOOL, 0, "false")
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_traits_support_helper_str_dirfromfiletrait_method_entry) {
	PHP_ME(Phalcon_Traits_Support_Helper_Str_DirFromFileTrait, toDirFromFile, arginfo_phalcon_traits_support_helper_str_dirfromfiletrait_todirfromfile, ZEND_ACC_PROTECTED|ZEND_ACC_STATIC)
	PHP_FE_END
};
