
extern zend_class_entry *phalcon_traits_support_helper_str_dirseparatortrait_ce;

ZEPHIR_INIT_CLASS(Phalcon_Traits_Support_Helper_Str_DirSeparatorTrait);

PHP_METHOD(Phalcon_Traits_Support_Helper_Str_DirSeparatorTrait, toDirSeparator);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_traits_support_helper_str_dirseparatortrait_todirseparator, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, directory, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_traits_support_helper_str_dirseparatortrait_method_entry) {
	PHP_ME(Phalcon_Traits_Support_Helper_Str_DirSeparatorTrait, toDirSeparator, arginfo_phalcon_traits_support_helper_str_dirseparatortrait_todirseparator, ZEND_ACC_PROTECTED|ZEND_ACC_STATIC)
	PHP_FE_END
};
