
extern zend_class_entry *phalcon_contracts_encryption_security_uuid_nodeprovider_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Encryption_Security_Uuid_NodeProvider);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_uuid_nodeprovider_getnode, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_encryption_security_uuid_nodeprovider_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_Uuid_NodeProvider, getNode, arginfo_phalcon_contracts_encryption_security_uuid_nodeprovider_getnode)
	PHP_FE_END
};
