
extern zend_class_entry *phalcon_html_attributes_attributesinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Attributes_AttributesInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_html_attributes_attributesinterface_getattributes, 0, 0, Phalcon\\Html\\Attributes, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_html_attributes_attributesinterface_setattributes, 0, 1, Phalcon\\Html\\Attributes\\AttributesInterface, 0)
	ZEND_ARG_OBJ_INFO(0, attributes, Phalcon\\Html\\Attributes, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_attributes_attributesinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Html_Attributes_AttributesInterface, getAttributes, arginfo_phalcon_html_attributes_attributesinterface_getattributes)
	PHP_ABSTRACT_ME(Phalcon_Html_Attributes_AttributesInterface, setAttributes, arginfo_phalcon_html_attributes_attributesinterface_setattributes)
	PHP_FE_END
};
