
extern zend_class_entry *phalcon_container_definition_processor_objectprocessor_ce;

ZEPHIR_INIT_CLASS(Phalcon_Container_Definition_Processor_ObjectProcessor);

PHP_METHOD(Phalcon_Container_Definition_Processor_ObjectProcessor, canProcess);
PHP_METHOD(Phalcon_Container_Definition_Processor_ObjectProcessor, process);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_container_definition_processor_objectprocessor_canprocess, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, definition)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_container_definition_processor_objectprocessor_process, 0, 3, Phalcon\\Container\\Definition\\ServiceDefinition, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
	ZEND_ARG_INFO(0, definition)
	ZEND_ARG_INFO(0, container)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_container_definition_processor_objectprocessor_method_entry) {
	PHP_ME(Phalcon_Container_Definition_Processor_ObjectProcessor, canProcess, arginfo_phalcon_container_definition_processor_objectprocessor_canprocess, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Container_Definition_Processor_ObjectProcessor, process, arginfo_phalcon_container_definition_processor_objectprocessor_process, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
