
extern zend_class_entry *phalcon_support_collection_exceptions_readonlyviolation_ce;

ZEPHIR_INIT_CLASS(Phalcon_Support_Collection_Exceptions_ReadOnlyViolation);

PHP_METHOD(Phalcon_Support_Collection_Exceptions_ReadOnlyViolation, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_support_collection_exceptions_readonlyviolation___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_support_collection_exceptions_readonlyviolation_method_entry) {
PHP_ME(Phalcon_Support_Collection_Exceptions_ReadOnlyViolation, __construct, arginfo_phalcon_support_collection_exceptions_readonlyviolation___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
