#define PHQL_NOT                             1
#define PHQL_IN                              2
#define PHQL_IS                              3
#define PHQL_PLUS                            4
#define PHQL_MINUS                           5
#define PHQL_DIVIDE                          6
#define PHQL_TIMES                           7
#define PHQL_LIKE                            8
#define PHQL_AND                             9
#define PHQL_OR                             10
#define PHQL_EQUALS                         11
#define PHQL_NOTEQUALS                      12
#define PHQL_LESS                           13
#define PHQL_GREATER                        14
#define PHQL_SELECT                         15
#define PHQL_FROM                           16
#define PHQL_COMMA                          17
#define PHQL_IDENTIFIER                     18
#define PHQL_DOT                            19
#define PHQL_AS                             20
#define PHQL_JOIN                           21
#define PHQL_ON                             22
#define PHQL_INNER                          23
#define PHQL_LEFT                           24
#define PHQL_RIGHT                          25
#define PHQL_INSERT                         26
#define PHQL_INTO                           27
#define PHQL_VALUES                         28
#define PHQL_BRACKEPHQL_T_OPEN              29
#define PHQL_BRACKEPHQL_T_CLOSE             30
#define PHQL_UPDATE                         31
#define PHQL_SET                            32
#define PHQL_DELETE                         33
#define PHQL_WHERE                          34
#define PHQL_ORDER                          35
#define PHQL_BY                             36
#define PHQL_INTEGER                        37
#define PHQL_GROUP                          38
#define PHQL_HAVING                         39
#define PHQL_LIMIT                          40
#define PHQL_NULL                           41
#define PHQL_STRING                         42
#define PHQL_DOUBLE                         43
#define PHQL_NPLACEHOLDER                   44
#define PHQL_SPLACEHOLDER                   45
