
extern zend_class_entry *phalcon_mvc_model_behavior_timestampable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_Behavior_Timestampable);

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_behavior_timestampable_method_entry) {
	PHP_FE_END
};
