
extern zend_class_entry *phalcon_queue_adapter_stream_streamqueue_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Stream_StreamQueue);

PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamQueue, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamQueue, getQueueName);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamqueue___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, queueName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamqueue_getqueuename, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_stream_streamqueue_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamQueue, __construct, arginfo_phalcon_queue_adapter_stream_streamqueue___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamQueue, getQueueName, arginfo_phalcon_queue_adapter_stream_streamqueue_getqueuename, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
