
extern zend_class_entry *phalcon_queue_adapter_stream_streamsubscriptionconsumer_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer);

PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, consume);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, subscribe);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, unsubscribe);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, unsubscribeAll);
PHP_METHOD(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, resolveQueueName);
zend_object *zephir_init_properties_Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer(zend_class_entry *class_type);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer___construct, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, context, Phalcon\\Queue\\Adapter\\Stream\\StreamContext, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_consume, 0, 0, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, timeout, IS_LONG, 0, "0")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_subscribe, 0, 2, IS_VOID, 0)

	ZEND_ARG_OBJ_INFO(0, consumer, Phalcon\\Contracts\\Queue\\Consumer, 0)
	ZEND_ARG_INFO(0, callback)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_unsubscribe, 0, 1, IS_VOID, 0)

	ZEND_ARG_OBJ_INFO(0, consumer, Phalcon\\Contracts\\Queue\\Consumer, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_unsubscribeall, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_resolvequeuename, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, consumer)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_zephir_init_properties_phalcon_queue_adapter_stream_streamsubscriptionconsumer, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_stream_streamsubscriptionconsumer_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, __construct, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, consume, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_consume, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, subscribe, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_subscribe, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, unsubscribe, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_unsubscribe, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, unsubscribeAll, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_unsubscribeall, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Queue_Adapter_Stream_StreamSubscriptionConsumer, resolveQueueName, arginfo_phalcon_queue_adapter_stream_streamsubscriptionconsumer_resolvequeuename, ZEND_ACC_PRIVATE)
	PHP_FE_END
};
