#!/bin/bash

#  Phalcon Framework
#
#  Copyright (c) 2011-2013 Phalcon Team (http://www.phalconphp.com)
#
#  This source file is subject to the New BSD License that is bundled
#  with this package in the file docs/LICENSE.txt.
#
#  If you did not receive a copy of the license and are unable to
#  obtain it through the world-wide-web, please send an email
#  to license@phalconphp.com so we can send you a copy immediately.
#
#  Authors: Andres Gutierrez <andres@phalconphp.com>
#            Eduar Carvajal <eduar@phalconphp.com>

export CC="gcc"
export CFLAGS="-O2 -finline-functions -fno-builtin-memcmp -fvisibility=hidden -fomit-frame-pointer"

#Clean current compilation
if [ -f Makefile ]; then
	make clean
	phpize55 --clean
fi

#Perform the compilation
phpize55 && ./configure --enable-phalcon --with-php-config=/opt/local/bin/php-config55 && make && make install && echo -e "\nThanks for compiling Phalcon!\nBuild succeed: Please restart your web server to complete the installation"
