
/* This file was generated automatically by Zephir do not modify it! */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>

#include "php_ext.h"
#include "phalcon.h"

#include <ext/standard/info.h>

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/globals.h"
#include "kernel/main.h"
#include "kernel/fcall.h"
#include "kernel/memory.h"


#include "phalcon/mvc/model/orm.h"

zend_class_entry *phalcon_di_injectionawareinterface_ce;
zend_class_entry *phalcon_filter_validation_validatorinterface_ce;
zend_class_entry *phalcon_events_eventsawareinterface_ce;
zend_class_entry *phalcon_storage_adapter_adapterinterface_ce;
zend_class_entry *phalcon_support_collection_collectioninterface_ce;
zend_class_entry *phalcon_storage_serializer_serializerinterface_ce;
zend_class_entry *phalcon_forms_element_elementinterface_ce;
zend_class_entry *phalcon_dispatcher_dispatcherinterface_ce;
zend_class_entry *phalcon_encryption_crypt_padding_padinterface_ce;
zend_class_entry *phalcon_assets_assetinterface_ce;
zend_class_entry *phalcon_cache_adapter_adapterinterface_ce;
zend_class_entry *phalcon_config_configinterface_ce;
zend_class_entry *phalcon_mvc_model_metadatainterface_ce;
zend_class_entry *phalcon_db_adapter_adapterinterface_ce;
zend_class_entry *phalcon_annotations_adapter_adapterinterface_ce;
zend_class_entry *phalcon_datamapper_pdo_connection_pdointerface_ce;
zend_class_entry *phalcon_db_dialectinterface_ce;
zend_class_entry *phalcon_html_link_interfaces_linkinterface_ce;
zend_class_entry *phalcon_html_link_interfaces_linkproviderinterface_ce;
zend_class_entry *phalcon_logger_adapter_adapterinterface_ce;
zend_class_entry *phalcon_paginator_adapter_adapterinterface_ce;
zend_class_entry *phalcon_translate_adapter_adapterinterface_ce;
zend_class_entry *phalcon_assets_filterinterface_ce;
zend_class_entry *phalcon_datamapper_pdo_connection_connectioninterface_ce;
zend_class_entry *phalcon_di_diinterface_ce;
zend_class_entry *phalcon_encryption_security_jwt_signer_signerinterface_ce;
zend_class_entry *phalcon_filter_validation_validatorcompositeinterface_ce;
zend_class_entry *phalcon_flash_flashinterface_ce;
zend_class_entry *phalcon_image_adapter_adapterinterface_ce;
zend_class_entry *phalcon_logger_formatter_formatterinterface_ce;
zend_class_entry *phalcon_mvc_model_behaviorinterface_ce;
zend_class_entry *phalcon_mvc_model_resultsetinterface_ce;
zend_class_entry *phalcon_mvc_view_engine_engineinterface_ce;
zend_class_entry *phalcon_mvc_viewbaseinterface_ce;
zend_class_entry *phalcon_acl_adapter_adapterinterface_ce;
zend_class_entry *phalcon_cache_cacheinterface_ce;
zend_class_entry *phalcon_domain_payload_readableinterface_ce;
zend_class_entry *phalcon_domain_payload_writeableinterface_ce;
zend_class_entry *phalcon_logger_loggerinterface_ce;
zend_class_entry *phalcon_mvc_entityinterface_ce;
zend_class_entry *phalcon_mvc_model_metadata_strategy_strategyinterface_ce;
zend_class_entry *phalcon_mvc_model_resultinterface_ce;
zend_class_entry *phalcon_mvc_routerinterface_ce;
zend_class_entry *phalcon_translate_interpolator_interpolatorinterface_ce;
zend_class_entry *phalcon_acl_componentinterface_ce;
zend_class_entry *phalcon_acl_roleinterface_ce;
zend_class_entry *phalcon_annotations_readerinterface_ce;
zend_class_entry *phalcon_cli_dispatcherinterface_ce;
zend_class_entry *phalcon_cli_router_routeinterface_ce;
zend_class_entry *phalcon_cli_routerinterface_ce;
zend_class_entry *phalcon_cli_taskinterface_ce;
zend_class_entry *phalcon_datamapper_pdo_connectionlocatorinterface_ce;
zend_class_entry *phalcon_datamapper_pdo_profiler_profilerinterface_ce;
zend_class_entry *phalcon_db_columninterface_ce;
zend_class_entry *phalcon_db_indexinterface_ce;
zend_class_entry *phalcon_db_referenceinterface_ce;
zend_class_entry *phalcon_db_resultinterface_ce;
zend_class_entry *phalcon_di_serviceinterface_ce;
zend_class_entry *phalcon_domain_payload_payloadinterface_ce;
zend_class_entry *phalcon_encryption_crypt_cryptinterface_ce;
zend_class_entry *phalcon_events_eventinterface_ce;
zend_class_entry *phalcon_events_managerinterface_ce;
zend_class_entry *phalcon_filter_filterinterface_ce;
zend_class_entry *phalcon_filter_validation_validationinterface_ce;
zend_class_entry *phalcon_html_attributes_attributesinterface_ce;
zend_class_entry *phalcon_html_attributes_renderinterface_ce;
zend_class_entry *phalcon_html_escaper_escaperinterface_ce;
zend_class_entry *phalcon_html_link_interfaces_evolvablelinkinterface_ce;
zend_class_entry *phalcon_html_link_interfaces_evolvablelinkproviderinterface_ce;
zend_class_entry *phalcon_html_link_serializer_serializerinterface_ce;
zend_class_entry *phalcon_http_cookie_cookieinterface_ce;
zend_class_entry *phalcon_http_message_requestmethodinterface_ce;
zend_class_entry *phalcon_http_message_responsestatuscodeinterface_ce;
zend_class_entry *phalcon_http_request_fileinterface_ce;
zend_class_entry *phalcon_http_requestinterface_ce;
zend_class_entry *phalcon_http_response_cookiesinterface_ce;
zend_class_entry *phalcon_http_response_headersinterface_ce;
zend_class_entry *phalcon_http_responseinterface_ce;
zend_class_entry *phalcon_messages_messageinterface_ce;
zend_class_entry *phalcon_mvc_controllerinterface_ce;
zend_class_entry *phalcon_mvc_dispatcherinterface_ce;
zend_class_entry *phalcon_mvc_micro_collectioninterface_ce;
zend_class_entry *phalcon_mvc_model_binderinterface_ce;
zend_class_entry *phalcon_mvc_model_criteriainterface_ce;
zend_class_entry *phalcon_mvc_model_managerinterface_ce;
zend_class_entry *phalcon_mvc_model_query_builderinterface_ce;
zend_class_entry *phalcon_mvc_model_query_statusinterface_ce;
zend_class_entry *phalcon_mvc_model_queryinterface_ce;
zend_class_entry *phalcon_mvc_model_relationinterface_ce;
zend_class_entry *phalcon_mvc_model_transaction_managerinterface_ce;
zend_class_entry *phalcon_mvc_model_transactioninterface_ce;
zend_class_entry *phalcon_mvc_modelinterface_ce;
zend_class_entry *phalcon_mvc_router_groupinterface_ce;
zend_class_entry *phalcon_mvc_router_routeinterface_ce;
zend_class_entry *phalcon_mvc_url_urlinterface_ce;
zend_class_entry *phalcon_mvc_viewinterface_ce;
zend_class_entry *phalcon_paginator_repositoryinterface_ce;
zend_class_entry *phalcon_session_baginterface_ce;
zend_class_entry *phalcon_session_managerinterface_ce;
zend_class_entry *phalcon_acl_componentawareinterface_ce;
zend_class_entry *phalcon_acl_roleawareinterface_ce;
zend_class_entry *phalcon_di_initializationawareinterface_ce;
zend_class_entry *phalcon_di_serviceproviderinterface_ce;
zend_class_entry *phalcon_mvc_controller_bindmodelinterface_ce;
zend_class_entry *phalcon_mvc_micro_middlewareinterface_ce;
zend_class_entry *phalcon_mvc_model_binder_bindableinterface_ce;
zend_class_entry *phalcon_mvc_moduledefinitioninterface_ce;
zend_class_entry *phalcon_html_helper_abstracthelper_ce;
zend_class_entry *phalcon_filter_validation_abstractvalidator_ce;
zend_class_entry *phalcon_html_helper_input_abstractinput_ce;
zend_class_entry *phalcon_factory_abstractconfigfactory_ce;
zend_class_entry *phalcon_di_abstractinjectionaware_ce;
zend_class_entry *phalcon_factory_abstractfactory_ce;
zend_class_entry *phalcon_storage_serializer_abstractserializer_ce;
zend_class_entry *phalcon_di_injectable_ce;
zend_class_entry *phalcon_forms_element_abstractelement_ce;
zend_class_entry *phalcon_storage_adapter_abstractadapter_ce;
zend_class_entry *phalcon_support_helper_str_abstractstr_ce;
zend_class_entry *phalcon_support_collection_ce;
zend_class_entry *phalcon_support_helper_arr_abstractarr_ce;
zend_class_entry *phalcon_storage_serializer_none_ce;
zend_class_entry *phalcon_filter_validation_validator_file_abstractfile_ce;
zend_class_entry *phalcon_config_config_ce;
zend_class_entry *phalcon_datamapper_query_abstractquery_ce;
zend_class_entry *phalcon_mvc_model_metadata_ce;
zend_class_entry *phalcon_db_adapter_abstractadapter_ce;
zend_class_entry *phalcon_html_helper_abstractseries_ce;
zend_class_entry *phalcon_annotations_adapter_abstractadapter_ce;
zend_class_entry *phalcon_datamapper_query_abstractconditions_ce;
zend_class_entry *phalcon_db_adapter_pdo_abstractpdo_ce;
zend_class_entry *phalcon_db_dialect_ce;
zend_class_entry *phalcon_events_abstracteventsaware_ce;
zend_class_entry *phalcon_html_helper_abstractlist_ce;
zend_class_entry *phalcon_logger_adapter_abstractadapter_ce;
zend_class_entry *phalcon_mvc_model_exception_ce;
zend_class_entry *phalcon_paginator_adapter_abstractadapter_ce;
zend_class_entry *phalcon_support_helper_str_pascalcase_ce;
zend_class_entry *phalcon_translate_adapter_abstractadapter_ce;
zend_class_entry *phalcon_application_abstractapplication_ce;
zend_class_entry *phalcon_application_exception_ce;
zend_class_entry *phalcon_assets_asset_ce;
zend_class_entry *phalcon_assets_inline_ce;
zend_class_entry *phalcon_datamapper_pdo_connection_abstractconnection_ce;
zend_class_entry *phalcon_datamapper_pdo_exception_exception_ce;
zend_class_entry *phalcon_di_di_ce;
zend_class_entry *phalcon_dispatcher_abstractdispatcher_ce;
zend_class_entry *phalcon_dispatcher_exception_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_abstractitem_ce;
zend_class_entry *phalcon_filter_validation_abstractvalidatorcomposite_ce;
zend_class_entry *phalcon_filter_validation_validator_file_size_equal_ce;
zend_class_entry *phalcon_flash_abstractflash_ce;
zend_class_entry *phalcon_html_link_abstractlink_ce;
zend_class_entry *phalcon_html_link_abstractlinkprovider_ce;
zend_class_entry *phalcon_image_adapter_abstractadapter_ce;
zend_class_entry *phalcon_logger_formatter_abstractformatter_ce;
zend_class_entry *phalcon_mvc_model_behavior_ce;
zend_class_entry *phalcon_mvc_model_resultset_ce;
zend_class_entry *phalcon_mvc_view_engine_abstractengine_ce;
zend_class_entry *phalcon_session_adapter_abstractadapter_ce;
zend_class_entry *phalcon_acl_adapter_abstractadapter_ce;
zend_class_entry *phalcon_cache_abstractcache_ce;
zend_class_entry *phalcon_di_exception_ce;
zend_class_entry *phalcon_di_factorydefault_ce;
zend_class_entry *phalcon_encryption_crypt_exception_exception_ce;
zend_class_entry *phalcon_encryption_security_jwt_signer_abstractsigner_ce;
zend_class_entry *phalcon_filter_validation_abstractcombinedfieldsvalidator_ce;
zend_class_entry *phalcon_html_helper_input_checkbox_ce;
zend_class_entry *phalcon_html_helper_ol_ce;
zend_class_entry *phalcon_html_helper_style_ce;
zend_class_entry *phalcon_html_link_link_ce;
zend_class_entry *phalcon_html_link_linkprovider_ce;
zend_class_entry *phalcon_logger_abstractlogger_ce;
zend_class_entry *phalcon_mvc_model_transaction_exception_ce;
zend_class_entry *phalcon_mvc_router_ce;
zend_class_entry *phalcon_mvc_view_exception_ce;
zend_class_entry *phalcon_session_adapter_noop_ce;
zend_class_entry *phalcon_storage_adapter_apcu_ce;
zend_class_entry *phalcon_storage_adapter_libmemcached_ce;
zend_class_entry *phalcon_storage_adapter_memory_ce;
zend_class_entry *phalcon_storage_adapter_redis_ce;
zend_class_entry *phalcon_storage_adapter_stream_ce;
zend_class_entry *phalcon_storage_adapter_weak_ce;
zend_class_entry *phalcon_storage_serializer_igbinary_ce;
zend_class_entry *phalcon_0__closure_ce;
zend_class_entry *phalcon_10__closure_ce;
zend_class_entry *phalcon_11__closure_ce;
zend_class_entry *phalcon_12__closure_ce;
zend_class_entry *phalcon_13__closure_ce;
zend_class_entry *phalcon_14__closure_ce;
zend_class_entry *phalcon_1__closure_ce;
zend_class_entry *phalcon_2__closure_ce;
zend_class_entry *phalcon_3__closure_ce;
zend_class_entry *phalcon_4__closure_ce;
zend_class_entry *phalcon_5__closure_ce;
zend_class_entry *phalcon_6__closure_ce;
zend_class_entry *phalcon_7__closure_ce;
zend_class_entry *phalcon_8__closure_ce;
zend_class_entry *phalcon_9__closure_ce;
zend_class_entry *phalcon_acl_adapter_memory_ce;
zend_class_entry *phalcon_acl_component_ce;
zend_class_entry *phalcon_acl_enum_ce;
zend_class_entry *phalcon_acl_exception_ce;
zend_class_entry *phalcon_acl_role_ce;
zend_class_entry *phalcon_annotations_adapter_apcu_ce;
zend_class_entry *phalcon_annotations_adapter_memory_ce;
zend_class_entry *phalcon_annotations_adapter_stream_ce;
zend_class_entry *phalcon_annotations_annotation_ce;
zend_class_entry *phalcon_annotations_annotationsfactory_ce;
zend_class_entry *phalcon_annotations_collection_ce;
zend_class_entry *phalcon_annotations_exception_ce;
zend_class_entry *phalcon_annotations_reader_ce;
zend_class_entry *phalcon_annotations_reflection_ce;
zend_class_entry *phalcon_assets_asset_css_ce;
zend_class_entry *phalcon_assets_asset_js_ce;
zend_class_entry *phalcon_assets_collection_ce;
zend_class_entry *phalcon_assets_exception_ce;
zend_class_entry *phalcon_assets_filters_cssmin_ce;
zend_class_entry *phalcon_assets_filters_jsmin_ce;
zend_class_entry *phalcon_assets_filters_none_ce;
zend_class_entry *phalcon_assets_inline_css_ce;
zend_class_entry *phalcon_assets_inline_js_ce;
zend_class_entry *phalcon_assets_manager_ce;
zend_class_entry *phalcon_autoload_exception_ce;
zend_class_entry *phalcon_autoload_loader_ce;
zend_class_entry *phalcon_cache_adapter_apcu_ce;
zend_class_entry *phalcon_cache_adapter_libmemcached_ce;
zend_class_entry *phalcon_cache_adapter_memory_ce;
zend_class_entry *phalcon_cache_adapter_redis_ce;
zend_class_entry *phalcon_cache_adapter_stream_ce;
zend_class_entry *phalcon_cache_adapter_weak_ce;
zend_class_entry *phalcon_cache_adapterfactory_ce;
zend_class_entry *phalcon_cache_cache_ce;
zend_class_entry *phalcon_cache_cachefactory_ce;
zend_class_entry *phalcon_cache_exception_exception_ce;
zend_class_entry *phalcon_cache_exception_invalidargumentexception_ce;
zend_class_entry *phalcon_cli_console_ce;
zend_class_entry *phalcon_cli_console_exception_ce;
zend_class_entry *phalcon_cli_dispatcher_ce;
zend_class_entry *phalcon_cli_dispatcher_exception_ce;
zend_class_entry *phalcon_cli_router_ce;
zend_class_entry *phalcon_cli_router_exception_ce;
zend_class_entry *phalcon_cli_router_route_ce;
zend_class_entry *phalcon_cli_task_ce;
zend_class_entry *phalcon_config_adapter_grouped_ce;
zend_class_entry *phalcon_config_adapter_ini_ce;
zend_class_entry *phalcon_config_adapter_json_ce;
zend_class_entry *phalcon_config_adapter_php_ce;
zend_class_entry *phalcon_config_adapter_yaml_ce;
zend_class_entry *phalcon_config_configfactory_ce;
zend_class_entry *phalcon_config_exception_ce;
zend_class_entry *phalcon_datamapper_pdo_connection_ce;
zend_class_entry *phalcon_datamapper_pdo_connection_decorated_ce;
zend_class_entry *phalcon_datamapper_pdo_connectionlocator_ce;
zend_class_entry *phalcon_datamapper_pdo_exception_cannotdisconnect_ce;
zend_class_entry *phalcon_datamapper_pdo_exception_connectionnotfound_ce;
zend_class_entry *phalcon_datamapper_pdo_profiler_memorylogger_ce;
zend_class_entry *phalcon_datamapper_pdo_profiler_profiler_ce;
zend_class_entry *phalcon_datamapper_query_bind_ce;
zend_class_entry *phalcon_datamapper_query_delete_ce;
zend_class_entry *phalcon_datamapper_query_insert_ce;
zend_class_entry *phalcon_datamapper_query_queryfactory_ce;
zend_class_entry *phalcon_datamapper_query_select_ce;
zend_class_entry *phalcon_datamapper_query_update_ce;
zend_class_entry *phalcon_db_adapter_pdo_mysql_ce;
zend_class_entry *phalcon_db_adapter_pdo_postgresql_ce;
zend_class_entry *phalcon_db_adapter_pdo_sqlite_ce;
zend_class_entry *phalcon_db_adapter_pdofactory_ce;
zend_class_entry *phalcon_db_column_ce;
zend_class_entry *phalcon_db_dialect_mysql_ce;
zend_class_entry *phalcon_db_dialect_postgresql_ce;
zend_class_entry *phalcon_db_dialect_sqlite_ce;
zend_class_entry *phalcon_db_enum_ce;
zend_class_entry *phalcon_db_exception_ce;
zend_class_entry *phalcon_db_index_ce;
zend_class_entry *phalcon_db_profiler_ce;
zend_class_entry *phalcon_db_profiler_item_ce;
zend_class_entry *phalcon_db_rawvalue_ce;
zend_class_entry *phalcon_db_reference_ce;
zend_class_entry *phalcon_db_result_pdoresult_ce;
zend_class_entry *phalcon_di_exception_serviceresolutionexception_ce;
zend_class_entry *phalcon_di_factorydefault_cli_ce;
zend_class_entry *phalcon_di_service_builder_ce;
zend_class_entry *phalcon_di_service_ce;
zend_class_entry *phalcon_domain_payload_payload_ce;
zend_class_entry *phalcon_domain_payload_payloadfactory_ce;
zend_class_entry *phalcon_domain_payload_status_ce;
zend_class_entry *phalcon_encryption_crypt_ce;
zend_class_entry *phalcon_encryption_crypt_exception_mismatch_ce;
zend_class_entry *phalcon_encryption_crypt_padding_ansi_ce;
zend_class_entry *phalcon_encryption_crypt_padding_iso10126_ce;
zend_class_entry *phalcon_encryption_crypt_padding_isoiek_ce;
zend_class_entry *phalcon_encryption_crypt_padding_noop_ce;
zend_class_entry *phalcon_encryption_crypt_padding_pkcs7_ce;
zend_class_entry *phalcon_encryption_crypt_padding_space_ce;
zend_class_entry *phalcon_encryption_crypt_padding_zero_ce;
zend_class_entry *phalcon_encryption_crypt_padfactory_ce;
zend_class_entry *phalcon_encryption_security_ce;
zend_class_entry *phalcon_encryption_security_exception_ce;
zend_class_entry *phalcon_encryption_security_jwt_builder_ce;
zend_class_entry *phalcon_encryption_security_jwt_exceptions_unsupportedalgorithmexception_ce;
zend_class_entry *phalcon_encryption_security_jwt_exceptions_validatorexception_ce;
zend_class_entry *phalcon_encryption_security_jwt_signer_hmac_ce;
zend_class_entry *phalcon_encryption_security_jwt_signer_none_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_enum_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_item_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_parser_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_signature_ce;
zend_class_entry *phalcon_encryption_security_jwt_token_token_ce;
zend_class_entry *phalcon_encryption_security_jwt_validator_ce;
zend_class_entry *phalcon_encryption_security_random_ce;
zend_class_entry *phalcon_events_event_ce;
zend_class_entry *phalcon_events_exception_ce;
zend_class_entry *phalcon_events_manager_ce;
zend_class_entry *phalcon_factory_exception_ce;
zend_class_entry *phalcon_filter_exception_ce;
zend_class_entry *phalcon_filter_filter_ce;
zend_class_entry *phalcon_filter_filterfactory_ce;
zend_class_entry *phalcon_filter_sanitize_absint_ce;
zend_class_entry *phalcon_filter_sanitize_alnum_ce;
zend_class_entry *phalcon_filter_sanitize_alpha_ce;
zend_class_entry *phalcon_filter_sanitize_boolval_ce;
zend_class_entry *phalcon_filter_sanitize_email_ce;
zend_class_entry *phalcon_filter_sanitize_floatval_ce;
zend_class_entry *phalcon_filter_sanitize_intval_ce;
zend_class_entry *phalcon_filter_sanitize_lower_ce;
zend_class_entry *phalcon_filter_sanitize_lowerfirst_ce;
zend_class_entry *phalcon_filter_sanitize_regex_ce;
zend_class_entry *phalcon_filter_sanitize_remove_ce;
zend_class_entry *phalcon_filter_sanitize_replace_ce;
zend_class_entry *phalcon_filter_sanitize_special_ce;
zend_class_entry *phalcon_filter_sanitize_specialfull_ce;
zend_class_entry *phalcon_filter_sanitize_stringval_ce;
zend_class_entry *phalcon_filter_sanitize_stringvallegacy_ce;
zend_class_entry *phalcon_filter_sanitize_striptags_ce;
zend_class_entry *phalcon_filter_sanitize_trim_ce;
zend_class_entry *phalcon_filter_sanitize_upper_ce;
zend_class_entry *phalcon_filter_sanitize_upperfirst_ce;
zend_class_entry *phalcon_filter_sanitize_upperwords_ce;
zend_class_entry *phalcon_filter_sanitize_url_ce;
zend_class_entry *phalcon_filter_validation_ce;
zend_class_entry *phalcon_filter_validation_exception_ce;
zend_class_entry *phalcon_filter_validation_validator_alnum_ce;
zend_class_entry *phalcon_filter_validation_validator_alpha_ce;
zend_class_entry *phalcon_filter_validation_validator_between_ce;
zend_class_entry *phalcon_filter_validation_validator_callback_ce;
zend_class_entry *phalcon_filter_validation_validator_confirmation_ce;
zend_class_entry *phalcon_filter_validation_validator_creditcard_ce;
zend_class_entry *phalcon_filter_validation_validator_date_ce;
zend_class_entry *phalcon_filter_validation_validator_digit_ce;
zend_class_entry *phalcon_filter_validation_validator_email_ce;
zend_class_entry *phalcon_filter_validation_validator_exception_ce;
zend_class_entry *phalcon_filter_validation_validator_exclusionin_ce;
zend_class_entry *phalcon_filter_validation_validator_file_ce;
zend_class_entry *phalcon_filter_validation_validator_file_mimetype_ce;
zend_class_entry *phalcon_filter_validation_validator_file_resolution_equal_ce;
zend_class_entry *phalcon_filter_validation_validator_file_resolution_max_ce;
zend_class_entry *phalcon_filter_validation_validator_file_resolution_min_ce;
zend_class_entry *phalcon_filter_validation_validator_file_size_max_ce;
zend_class_entry *phalcon_filter_validation_validator_file_size_min_ce;
zend_class_entry *phalcon_filter_validation_validator_identical_ce;
zend_class_entry *phalcon_filter_validation_validator_inclusionin_ce;
zend_class_entry *phalcon_filter_validation_validator_ip_ce;
zend_class_entry *phalcon_filter_validation_validator_numericality_ce;
zend_class_entry *phalcon_filter_validation_validator_presenceof_ce;
zend_class_entry *phalcon_filter_validation_validator_regex_ce;
zend_class_entry *phalcon_filter_validation_validator_stringlength_ce;
zend_class_entry *phalcon_filter_validation_validator_stringlength_max_ce;
zend_class_entry *phalcon_filter_validation_validator_stringlength_min_ce;
zend_class_entry *phalcon_filter_validation_validator_uniqueness_ce;
zend_class_entry *phalcon_filter_validation_validator_url_ce;
zend_class_entry *phalcon_filter_validation_validatorfactory_ce;
zend_class_entry *phalcon_flash_direct_ce;
zend_class_entry *phalcon_flash_exception_ce;
zend_class_entry *phalcon_flash_session_ce;
zend_class_entry *phalcon_forms_element_check_ce;
zend_class_entry *phalcon_forms_element_date_ce;
zend_class_entry *phalcon_forms_element_email_ce;
zend_class_entry *phalcon_forms_element_file_ce;
zend_class_entry *phalcon_forms_element_hidden_ce;
zend_class_entry *phalcon_forms_element_numeric_ce;
zend_class_entry *phalcon_forms_element_password_ce;
zend_class_entry *phalcon_forms_element_radio_ce;
zend_class_entry *phalcon_forms_element_select_ce;
zend_class_entry *phalcon_forms_element_submit_ce;
zend_class_entry *phalcon_forms_element_text_ce;
zend_class_entry *phalcon_forms_element_textarea_ce;
zend_class_entry *phalcon_forms_exception_ce;
zend_class_entry *phalcon_forms_form_ce;
zend_class_entry *phalcon_forms_manager_ce;
zend_class_entry *phalcon_html_attributes_ce;
zend_class_entry *phalcon_html_breadcrumbs_ce;
zend_class_entry *phalcon_html_escaper_ce;
zend_class_entry *phalcon_html_escaper_exception_ce;
zend_class_entry *phalcon_html_escaperfactory_ce;
zend_class_entry *phalcon_html_exception_ce;
zend_class_entry *phalcon_html_helper_anchor_ce;
zend_class_entry *phalcon_html_helper_base_ce;
zend_class_entry *phalcon_html_helper_body_ce;
zend_class_entry *phalcon_html_helper_button_ce;
zend_class_entry *phalcon_html_helper_close_ce;
zend_class_entry *phalcon_html_helper_doctype_ce;
zend_class_entry *phalcon_html_helper_element_ce;
zend_class_entry *phalcon_html_helper_form_ce;
zend_class_entry *phalcon_html_helper_img_ce;
zend_class_entry *phalcon_html_helper_input_color_ce;
zend_class_entry *phalcon_html_helper_input_date_ce;
zend_class_entry *phalcon_html_helper_input_datetime_ce;
zend_class_entry *phalcon_html_helper_input_datetimelocal_ce;
zend_class_entry *phalcon_html_helper_input_email_ce;
zend_class_entry *phalcon_html_helper_input_file_ce;
zend_class_entry *phalcon_html_helper_input_hidden_ce;
zend_class_entry *phalcon_html_helper_input_image_ce;
zend_class_entry *phalcon_html_helper_input_input_ce;
zend_class_entry *phalcon_html_helper_input_month_ce;
zend_class_entry *phalcon_html_helper_input_numeric_ce;
zend_class_entry *phalcon_html_helper_input_password_ce;
zend_class_entry *phalcon_html_helper_input_radio_ce;
zend_class_entry *phalcon_html_helper_input_range_ce;
zend_class_entry *phalcon_html_helper_input_search_ce;
zend_class_entry *phalcon_html_helper_input_select_ce;
zend_class_entry *phalcon_html_helper_input_submit_ce;
zend_class_entry *phalcon_html_helper_input_tel_ce;
zend_class_entry *phalcon_html_helper_input_text_ce;
zend_class_entry *phalcon_html_helper_input_textarea_ce;
zend_class_entry *phalcon_html_helper_input_time_ce;
zend_class_entry *phalcon_html_helper_input_url_ce;
zend_class_entry *phalcon_html_helper_input_week_ce;
zend_class_entry *phalcon_html_helper_label_ce;
zend_class_entry *phalcon_html_helper_link_ce;
zend_class_entry *phalcon_html_helper_meta_ce;
zend_class_entry *phalcon_html_helper_script_ce;
zend_class_entry *phalcon_html_helper_title_ce;
zend_class_entry *phalcon_html_helper_ul_ce;
zend_class_entry *phalcon_html_link_evolvablelink_ce;
zend_class_entry *phalcon_html_link_evolvablelinkprovider_ce;
zend_class_entry *phalcon_html_link_serializer_header_ce;
zend_class_entry *phalcon_html_tagfactory_ce;
zend_class_entry *phalcon_http_cookie_ce;
zend_class_entry *phalcon_http_cookie_exception_ce;
zend_class_entry *phalcon_http_request_ce;
zend_class_entry *phalcon_http_request_exception_ce;
zend_class_entry *phalcon_http_request_file_ce;
zend_class_entry *phalcon_http_response_ce;
zend_class_entry *phalcon_http_response_cookies_ce;
zend_class_entry *phalcon_http_response_exception_ce;
zend_class_entry *phalcon_http_response_headers_ce;
zend_class_entry *phalcon_image_adapter_gd_ce;
zend_class_entry *phalcon_image_adapter_imagick_ce;
zend_class_entry *phalcon_image_enum_ce;
zend_class_entry *phalcon_image_exception_ce;
zend_class_entry *phalcon_image_imagefactory_ce;
zend_class_entry *phalcon_logger_adapter_noop_ce;
zend_class_entry *phalcon_logger_adapter_stream_ce;
zend_class_entry *phalcon_logger_adapter_syslog_ce;
zend_class_entry *phalcon_logger_adapterfactory_ce;
zend_class_entry *phalcon_logger_enum_ce;
zend_class_entry *phalcon_logger_exception_ce;
zend_class_entry *phalcon_logger_formatter_json_ce;
zend_class_entry *phalcon_logger_formatter_line_ce;
zend_class_entry *phalcon_logger_item_ce;
zend_class_entry *phalcon_logger_logger_ce;
zend_class_entry *phalcon_logger_loggerfactory_ce;
zend_class_entry *phalcon_messages_exception_ce;
zend_class_entry *phalcon_messages_message_ce;
zend_class_entry *phalcon_messages_messages_ce;
zend_class_entry *phalcon_mvc_application_ce;
zend_class_entry *phalcon_mvc_application_exception_ce;
zend_class_entry *phalcon_mvc_controller_ce;
zend_class_entry *phalcon_mvc_dispatcher_ce;
zend_class_entry *phalcon_mvc_dispatcher_exception_ce;
zend_class_entry *phalcon_mvc_micro_ce;
zend_class_entry *phalcon_mvc_micro_collection_ce;
zend_class_entry *phalcon_mvc_micro_exception_ce;
zend_class_entry *phalcon_mvc_micro_lazyloader_ce;
zend_class_entry *phalcon_mvc_model_behavior_softdelete_ce;
zend_class_entry *phalcon_mvc_model_behavior_timestampable_ce;
zend_class_entry *phalcon_mvc_model_binder_ce;
zend_class_entry *phalcon_mvc_model_ce;
zend_class_entry *phalcon_mvc_model_criteria_ce;
zend_class_entry *phalcon_mvc_model_manager_ce;
zend_class_entry *phalcon_mvc_model_metadata_apcu_ce;
zend_class_entry *phalcon_mvc_model_metadata_libmemcached_ce;
zend_class_entry *phalcon_mvc_model_metadata_memory_ce;
zend_class_entry *phalcon_mvc_model_metadata_redis_ce;
zend_class_entry *phalcon_mvc_model_metadata_strategy_annotations_ce;
zend_class_entry *phalcon_mvc_model_metadata_strategy_introspection_ce;
zend_class_entry *phalcon_mvc_model_metadata_stream_ce;
zend_class_entry *phalcon_mvc_model_query_builder_ce;
zend_class_entry *phalcon_mvc_model_query_ce;
zend_class_entry *phalcon_mvc_model_query_lang_ce;
zend_class_entry *phalcon_mvc_model_query_status_ce;
zend_class_entry *phalcon_mvc_model_relation_ce;
zend_class_entry *phalcon_mvc_model_resultset_complex_ce;
zend_class_entry *phalcon_mvc_model_resultset_simple_ce;
zend_class_entry *phalcon_mvc_model_row_ce;
zend_class_entry *phalcon_mvc_model_transaction_ce;
zend_class_entry *phalcon_mvc_model_transaction_failed_ce;
zend_class_entry *phalcon_mvc_model_transaction_manager_ce;
zend_class_entry *phalcon_mvc_model_validationfailed_ce;
zend_class_entry *phalcon_mvc_router_annotations_ce;
zend_class_entry *phalcon_mvc_router_exception_ce;
zend_class_entry *phalcon_mvc_router_group_ce;
zend_class_entry *phalcon_mvc_router_route_ce;
zend_class_entry *phalcon_mvc_url_ce;
zend_class_entry *phalcon_mvc_url_exception_ce;
zend_class_entry *phalcon_mvc_view_ce;
zend_class_entry *phalcon_mvc_view_engine_php_ce;
zend_class_entry *phalcon_mvc_view_engine_volt_ce;
zend_class_entry *phalcon_mvc_view_engine_volt_compiler_ce;
zend_class_entry *phalcon_mvc_view_engine_volt_exception_ce;
zend_class_entry *phalcon_mvc_view_simple_ce;
zend_class_entry *phalcon_paginator_adapter_model_ce;
zend_class_entry *phalcon_paginator_adapter_nativearray_ce;
zend_class_entry *phalcon_paginator_adapter_querybuilder_ce;
zend_class_entry *phalcon_paginator_exception_ce;
zend_class_entry *phalcon_paginator_paginatorfactory_ce;
zend_class_entry *phalcon_paginator_repository_ce;
zend_class_entry *phalcon_session_adapter_libmemcached_ce;
zend_class_entry *phalcon_session_adapter_redis_ce;
zend_class_entry *phalcon_session_adapter_stream_ce;
zend_class_entry *phalcon_session_bag_ce;
zend_class_entry *phalcon_session_exception_ce;
zend_class_entry *phalcon_session_manager_ce;
zend_class_entry *phalcon_storage_adapterfactory_ce;
zend_class_entry *phalcon_storage_exception_ce;
zend_class_entry *phalcon_storage_serializer_base64_ce;
zend_class_entry *phalcon_storage_serializer_json_ce;
zend_class_entry *phalcon_storage_serializer_memcachedigbinary_ce;
zend_class_entry *phalcon_storage_serializer_memcachedjson_ce;
zend_class_entry *phalcon_storage_serializer_memcachedphp_ce;
zend_class_entry *phalcon_storage_serializer_msgpack_ce;
zend_class_entry *phalcon_storage_serializer_php_ce;
zend_class_entry *phalcon_storage_serializer_redisigbinary_ce;
zend_class_entry *phalcon_storage_serializer_redisjson_ce;
zend_class_entry *phalcon_storage_serializer_redismsgpack_ce;
zend_class_entry *phalcon_storage_serializer_redisnone_ce;
zend_class_entry *phalcon_storage_serializer_redisphp_ce;
zend_class_entry *phalcon_storage_serializerfactory_ce;
zend_class_entry *phalcon_support_collection_exception_ce;
zend_class_entry *phalcon_support_collection_readonlycollection_ce;
zend_class_entry *phalcon_support_debug_ce;
zend_class_entry *phalcon_support_debug_dump_ce;
zend_class_entry *phalcon_support_debug_exception_ce;
zend_class_entry *phalcon_support_exception_ce;
zend_class_entry *phalcon_support_helper_arr_blacklist_ce;
zend_class_entry *phalcon_support_helper_arr_chunk_ce;
zend_class_entry *phalcon_support_helper_arr_filter_ce;
zend_class_entry *phalcon_support_helper_arr_first_ce;
zend_class_entry *phalcon_support_helper_arr_firstkey_ce;
zend_class_entry *phalcon_support_helper_arr_flatten_ce;
zend_class_entry *phalcon_support_helper_arr_get_ce;
zend_class_entry *phalcon_support_helper_arr_group_ce;
zend_class_entry *phalcon_support_helper_arr_has_ce;
zend_class_entry *phalcon_support_helper_arr_isunique_ce;
zend_class_entry *phalcon_support_helper_arr_last_ce;
zend_class_entry *phalcon_support_helper_arr_lastkey_ce;
zend_class_entry *phalcon_support_helper_arr_order_ce;
zend_class_entry *phalcon_support_helper_arr_pluck_ce;
zend_class_entry *phalcon_support_helper_arr_set_ce;
zend_class_entry *phalcon_support_helper_arr_sliceleft_ce;
zend_class_entry *phalcon_support_helper_arr_sliceright_ce;
zend_class_entry *phalcon_support_helper_arr_split_ce;
zend_class_entry *phalcon_support_helper_arr_toobject_ce;
zend_class_entry *phalcon_support_helper_arr_validateall_ce;
zend_class_entry *phalcon_support_helper_arr_validateany_ce;
zend_class_entry *phalcon_support_helper_arr_whitelist_ce;
zend_class_entry *phalcon_support_helper_exception_ce;
zend_class_entry *phalcon_support_helper_file_basename_ce;
zend_class_entry *phalcon_support_helper_json_decode_ce;
zend_class_entry *phalcon_support_helper_json_encode_ce;
zend_class_entry *phalcon_support_helper_number_isbetween_ce;
zend_class_entry *phalcon_support_helper_str_camelize_ce;
zend_class_entry *phalcon_support_helper_str_concat_ce;
zend_class_entry *phalcon_support_helper_str_countvowels_ce;
zend_class_entry *phalcon_support_helper_str_decapitalize_ce;
zend_class_entry *phalcon_support_helper_str_decrement_ce;
zend_class_entry *phalcon_support_helper_str_dirfromfile_ce;
zend_class_entry *phalcon_support_helper_str_dirseparator_ce;
zend_class_entry *phalcon_support_helper_str_dynamic_ce;
zend_class_entry *phalcon_support_helper_str_endswith_ce;
zend_class_entry *phalcon_support_helper_str_firstbetween_ce;
zend_class_entry *phalcon_support_helper_str_friendly_ce;
zend_class_entry *phalcon_support_helper_str_humanize_ce;
zend_class_entry *phalcon_support_helper_str_includes_ce;
zend_class_entry *phalcon_support_helper_str_increment_ce;
zend_class_entry *phalcon_support_helper_str_interpolate_ce;
zend_class_entry *phalcon_support_helper_str_isanagram_ce;
zend_class_entry *phalcon_support_helper_str_islower_ce;
zend_class_entry *phalcon_support_helper_str_ispalindrome_ce;
zend_class_entry *phalcon_support_helper_str_isupper_ce;
zend_class_entry *phalcon_support_helper_str_kebabcase_ce;
zend_class_entry *phalcon_support_helper_str_len_ce;
zend_class_entry *phalcon_support_helper_str_lower_ce;
zend_class_entry *phalcon_support_helper_str_prefix_ce;
zend_class_entry *phalcon_support_helper_str_random_ce;
zend_class_entry *phalcon_support_helper_str_reduceslashes_ce;
zend_class_entry *phalcon_support_helper_str_snakecase_ce;
zend_class_entry *phalcon_support_helper_str_startswith_ce;
zend_class_entry *phalcon_support_helper_str_suffix_ce;
zend_class_entry *phalcon_support_helper_str_ucwords_ce;
zend_class_entry *phalcon_support_helper_str_uncamelize_ce;
zend_class_entry *phalcon_support_helper_str_underscore_ce;
zend_class_entry *phalcon_support_helper_str_upper_ce;
zend_class_entry *phalcon_support_helperfactory_ce;
zend_class_entry *phalcon_support_registry_ce;
zend_class_entry *phalcon_support_version_ce;
zend_class_entry *phalcon_tag_ce;
zend_class_entry *phalcon_tag_exception_ce;
zend_class_entry *phalcon_tag_select_ce;
zend_class_entry *phalcon_translate_adapter_csv_ce;
zend_class_entry *phalcon_translate_adapter_gettext_ce;
zend_class_entry *phalcon_translate_adapter_nativearray_ce;
zend_class_entry *phalcon_translate_exception_ce;
zend_class_entry *phalcon_translate_interpolator_associativearray_ce;
zend_class_entry *phalcon_translate_interpolator_indexedarray_ce;
zend_class_entry *phalcon_translate_interpolatorfactory_ce;
zend_class_entry *phalcon_translate_translatefactory_ce;

ZEND_DECLARE_MODULE_GLOBALS(phalcon)

PHP_INI_BEGIN()
	STD_PHP_INI_BOOLEAN("phalcon.db.escape_identifiers", "1", PHP_INI_ALL, OnUpdateBool, db.escape_identifiers, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.db.force_casting", "0", PHP_INI_ALL, OnUpdateBool, db.force_casting, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.form.strict_entity_property_check", "0", PHP_INI_ALL, OnUpdateBool, form.strict_entity_property_check, zend_phalcon_globals, phalcon_globals)
	
	
	STD_PHP_INI_BOOLEAN("phalcon.orm.case_insensitive_column_map", "0", PHP_INI_ALL, OnUpdateBool, orm.case_insensitive_column_map, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.cast_last_insert_id_to_int", "0", PHP_INI_ALL, OnUpdateBool, orm.cast_last_insert_id_to_int, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.cast_on_hydrate", "0", PHP_INI_ALL, OnUpdateBool, orm.cast_on_hydrate, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.column_renaming", "1", PHP_INI_ALL, OnUpdateBool, orm.column_renaming, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.disable_assign_setters", "0", PHP_INI_ALL, OnUpdateBool, orm.disable_assign_setters, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.enable_implicit_joins", "1", PHP_INI_ALL, OnUpdateBool, orm.enable_implicit_joins, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.enable_literals", "1", PHP_INI_ALL, OnUpdateBool, orm.enable_literals, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.events", "1", PHP_INI_ALL, OnUpdateBool, orm.events, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.exception_on_failed_save", "0", PHP_INI_ALL, OnUpdateBool, orm.exception_on_failed_save, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.exception_on_failed_metadata_save", "1", PHP_INI_ALL, OnUpdateBool, orm.exception_on_failed_metadata_save, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.ignore_unknown_columns", "0", PHP_INI_ALL, OnUpdateBool, orm.ignore_unknown_columns, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.late_state_binding", "0", PHP_INI_ALL, OnUpdateBool, orm.late_state_binding, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.not_null_validations", "1", PHP_INI_ALL, OnUpdateBool, orm.not_null_validations, zend_phalcon_globals, phalcon_globals)
	
	STD_PHP_INI_ENTRY("phalcon.orm.resultset_prefetch_records", "0", PHP_INI_ALL, NULL, orm.resultset_prefetch_records, zend_phalcon_globals, phalcon_globals)
	
	STD_PHP_INI_BOOLEAN("phalcon.orm.update_snapshot_on_save", "1", PHP_INI_ALL, OnUpdateBool, orm.update_snapshot_on_save, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.virtual_foreign_keys", "1", PHP_INI_ALL, OnUpdateBool, orm.virtual_foreign_keys, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.orm.dynamic_update", "1", PHP_INI_ALL, OnUpdateBool, orm.dynamic_update, zend_phalcon_globals, phalcon_globals)
	STD_PHP_INI_BOOLEAN("phalcon.warning.enable", "1", PHP_INI_ALL, OnUpdateBool, warning.enable, zend_phalcon_globals, phalcon_globals)
PHP_INI_END()

static PHP_MINIT_FUNCTION(phalcon)
{
	REGISTER_INI_ENTRIES();
	zephir_module_init();
	ZEPHIR_INIT(Phalcon_Di_InjectionAwareInterface);
	ZEPHIR_INIT(Phalcon_Filter_Validation_ValidatorInterface);
	ZEPHIR_INIT(Phalcon_Events_EventsAwareInterface);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Support_Collection_CollectionInterface);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_SerializerInterface);
	ZEPHIR_INIT(Phalcon_Forms_Element_ElementInterface);
	ZEPHIR_INIT(Phalcon_Dispatcher_DispatcherInterface);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_PadInterface);
	ZEPHIR_INIT(Phalcon_Assets_AssetInterface);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Config_ConfigInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaDataInterface);
	ZEPHIR_INIT(Phalcon_Db_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Annotations_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Connection_PdoInterface);
	ZEPHIR_INIT(Phalcon_Db_DialectInterface);
	ZEPHIR_INIT(Phalcon_Html_Link_Interfaces_LinkInterface);
	ZEPHIR_INIT(Phalcon_Html_Link_Interfaces_LinkProviderInterface);
	ZEPHIR_INIT(Phalcon_Logger_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Paginator_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Translate_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Assets_FilterInterface);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Connection_ConnectionInterface);
	ZEPHIR_INIT(Phalcon_Di_DiInterface);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Signer_SignerInterface);
	ZEPHIR_INIT(Phalcon_Filter_Validation_ValidatorCompositeInterface);
	ZEPHIR_INIT(Phalcon_Flash_FlashInterface);
	ZEPHIR_INIT(Phalcon_Image_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Logger_Formatter_FormatterInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_BehaviorInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_ResultsetInterface);
	ZEPHIR_INIT(Phalcon_Mvc_ViewBaseInterface);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_EngineInterface);
	ZEPHIR_INIT(Phalcon_Acl_Adapter_AdapterInterface);
	ZEPHIR_INIT(Phalcon_Cache_CacheInterface);
	ZEPHIR_INIT(Phalcon_Domain_Payload_ReadableInterface);
	ZEPHIR_INIT(Phalcon_Domain_Payload_WriteableInterface);
	ZEPHIR_INIT(Phalcon_Logger_LoggerInterface);
	ZEPHIR_INIT(Phalcon_Mvc_EntityInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Strategy_StrategyInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_ResultInterface);
	ZEPHIR_INIT(Phalcon_Mvc_RouterInterface);
	ZEPHIR_INIT(Phalcon_Translate_Interpolator_InterpolatorInterface);
	ZEPHIR_INIT(Phalcon_Acl_ComponentInterface);
	ZEPHIR_INIT(Phalcon_Acl_RoleInterface);
	ZEPHIR_INIT(Phalcon_Annotations_ReaderInterface);
	ZEPHIR_INIT(Phalcon_Cli_DispatcherInterface);
	ZEPHIR_INIT(Phalcon_Cli_RouterInterface);
	ZEPHIR_INIT(Phalcon_Cli_Router_RouteInterface);
	ZEPHIR_INIT(Phalcon_Cli_TaskInterface);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_ConnectionLocatorInterface);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Profiler_ProfilerInterface);
	ZEPHIR_INIT(Phalcon_Db_ColumnInterface);
	ZEPHIR_INIT(Phalcon_Db_IndexInterface);
	ZEPHIR_INIT(Phalcon_Db_ReferenceInterface);
	ZEPHIR_INIT(Phalcon_Db_ResultInterface);
	ZEPHIR_INIT(Phalcon_Di_ServiceInterface);
	ZEPHIR_INIT(Phalcon_Domain_Payload_PayloadInterface);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_CryptInterface);
	ZEPHIR_INIT(Phalcon_Events_EventInterface);
	ZEPHIR_INIT(Phalcon_Events_ManagerInterface);
	ZEPHIR_INIT(Phalcon_Filter_FilterInterface);
	ZEPHIR_INIT(Phalcon_Filter_Validation_ValidationInterface);
	ZEPHIR_INIT(Phalcon_Html_Attributes_AttributesInterface);
	ZEPHIR_INIT(Phalcon_Html_Attributes_RenderInterface);
	ZEPHIR_INIT(Phalcon_Html_Escaper_EscaperInterface);
	ZEPHIR_INIT(Phalcon_Html_Link_Interfaces_EvolvableLinkInterface);
	ZEPHIR_INIT(Phalcon_Html_Link_Interfaces_EvolvableLinkProviderInterface);
	ZEPHIR_INIT(Phalcon_Html_Link_Serializer_SerializerInterface);
	ZEPHIR_INIT(Phalcon_Http_Cookie_CookieInterface);
	ZEPHIR_INIT(Phalcon_Http_Message_RequestMethodInterface);
	ZEPHIR_INIT(Phalcon_Http_Message_ResponseStatusCodeInterface);
	ZEPHIR_INIT(Phalcon_Http_RequestInterface);
	ZEPHIR_INIT(Phalcon_Http_Request_FileInterface);
	ZEPHIR_INIT(Phalcon_Http_ResponseInterface);
	ZEPHIR_INIT(Phalcon_Http_Response_CookiesInterface);
	ZEPHIR_INIT(Phalcon_Http_Response_HeadersInterface);
	ZEPHIR_INIT(Phalcon_Messages_MessageInterface);
	ZEPHIR_INIT(Phalcon_Mvc_ControllerInterface);
	ZEPHIR_INIT(Phalcon_Mvc_DispatcherInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Micro_CollectionInterface);
	ZEPHIR_INIT(Phalcon_Mvc_ModelInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_BinderInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_CriteriaInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_ManagerInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_QueryInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query_BuilderInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query_StatusInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_RelationInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_TransactionInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Transaction_ManagerInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Router_GroupInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Router_RouteInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Url_UrlInterface);
	ZEPHIR_INIT(Phalcon_Mvc_ViewInterface);
	ZEPHIR_INIT(Phalcon_Paginator_RepositoryInterface);
	ZEPHIR_INIT(Phalcon_Session_BagInterface);
	ZEPHIR_INIT(Phalcon_Session_ManagerInterface);
	ZEPHIR_INIT(Phalcon_Acl_ComponentAwareInterface);
	ZEPHIR_INIT(Phalcon_Acl_RoleAwareInterface);
	ZEPHIR_INIT(Phalcon_Di_InitializationAwareInterface);
	ZEPHIR_INIT(Phalcon_Di_ServiceProviderInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Controller_BindModelInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Micro_MiddlewareInterface);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Binder_BindableInterface);
	ZEPHIR_INIT(Phalcon_Mvc_ModuleDefinitionInterface);
	ZEPHIR_INIT(Phalcon_Html_Helper_AbstractHelper);
	ZEPHIR_INIT(Phalcon_Filter_Validation_AbstractValidator);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_AbstractInput);
	ZEPHIR_INIT(Phalcon_Factory_AbstractConfigFactory);
	ZEPHIR_INIT(Phalcon_Di_AbstractInjectionAware);
	ZEPHIR_INIT(Phalcon_Factory_AbstractFactory);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_AbstractSerializer);
	ZEPHIR_INIT(Phalcon_Di_Injectable);
	ZEPHIR_INIT(Phalcon_Forms_Element_AbstractElement);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_AbstractStr);
	ZEPHIR_INIT(Phalcon_Support_Collection);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_AbstractArr);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_None);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_AbstractFile);
	ZEPHIR_INIT(Phalcon_Config_Config);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_AbstractQuery);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData);
	ZEPHIR_INIT(Phalcon_Db_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Html_Helper_AbstractSeries);
	ZEPHIR_INIT(Phalcon_Annotations_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_AbstractConditions);
	ZEPHIR_INIT(Phalcon_Db_Adapter_Pdo_AbstractPdo);
	ZEPHIR_INIT(Phalcon_Db_Dialect);
	ZEPHIR_INIT(Phalcon_Events_AbstractEventsAware);
	ZEPHIR_INIT(Phalcon_Html_Helper_AbstractList);
	ZEPHIR_INIT(Phalcon_Logger_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Exception);
	ZEPHIR_INIT(Phalcon_Paginator_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_PascalCase);
	ZEPHIR_INIT(Phalcon_Translate_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Application_AbstractApplication);
	ZEPHIR_INIT(Phalcon_Application_Exception);
	ZEPHIR_INIT(Phalcon_Assets_Asset);
	ZEPHIR_INIT(Phalcon_Assets_Inline);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Connection_AbstractConnection);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Exception_Exception);
	ZEPHIR_INIT(Phalcon_Di_Di);
	ZEPHIR_INIT(Phalcon_Dispatcher_AbstractDispatcher);
	ZEPHIR_INIT(Phalcon_Dispatcher_Exception);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_AbstractItem);
	ZEPHIR_INIT(Phalcon_Filter_Validation_AbstractValidatorComposite);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Size_Equal);
	ZEPHIR_INIT(Phalcon_Flash_AbstractFlash);
	ZEPHIR_INIT(Phalcon_Html_Link_AbstractLink);
	ZEPHIR_INIT(Phalcon_Html_Link_AbstractLinkProvider);
	ZEPHIR_INIT(Phalcon_Image_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Logger_Formatter_AbstractFormatter);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Behavior);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Resultset);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_AbstractEngine);
	ZEPHIR_INIT(Phalcon_Session_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Acl_Adapter_AbstractAdapter);
	ZEPHIR_INIT(Phalcon_Cache_AbstractCache);
	ZEPHIR_INIT(Phalcon_Di_Exception);
	ZEPHIR_INIT(Phalcon_Di_FactoryDefault);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Exception_Exception);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Signer_AbstractSigner);
	ZEPHIR_INIT(Phalcon_Filter_Validation_AbstractCombinedFieldsValidator);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Checkbox);
	ZEPHIR_INIT(Phalcon_Html_Helper_Ol);
	ZEPHIR_INIT(Phalcon_Html_Helper_Style);
	ZEPHIR_INIT(Phalcon_Html_Link_Link);
	ZEPHIR_INIT(Phalcon_Html_Link_LinkProvider);
	ZEPHIR_INIT(Phalcon_Logger_AbstractLogger);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Transaction_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_Router);
	ZEPHIR_INIT(Phalcon_Mvc_View_Exception);
	ZEPHIR_INIT(Phalcon_Session_Adapter_Noop);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Apcu);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Libmemcached);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Memory);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Redis);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Stream);
	ZEPHIR_INIT(Phalcon_Storage_Adapter_Weak);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_Igbinary);
	ZEPHIR_INIT(Phalcon_Acl_Adapter_Memory);
	ZEPHIR_INIT(Phalcon_Acl_Component);
	ZEPHIR_INIT(Phalcon_Acl_Enum);
	ZEPHIR_INIT(Phalcon_Acl_Exception);
	ZEPHIR_INIT(Phalcon_Acl_Role);
	ZEPHIR_INIT(Phalcon_Annotations_Adapter_Apcu);
	ZEPHIR_INIT(Phalcon_Annotations_Adapter_Memory);
	ZEPHIR_INIT(Phalcon_Annotations_Adapter_Stream);
	ZEPHIR_INIT(Phalcon_Annotations_Annotation);
	ZEPHIR_INIT(Phalcon_Annotations_AnnotationsFactory);
	ZEPHIR_INIT(Phalcon_Annotations_Collection);
	ZEPHIR_INIT(Phalcon_Annotations_Exception);
	ZEPHIR_INIT(Phalcon_Annotations_Reader);
	ZEPHIR_INIT(Phalcon_Annotations_Reflection);
	ZEPHIR_INIT(Phalcon_Assets_Asset_Css);
	ZEPHIR_INIT(Phalcon_Assets_Asset_Js);
	ZEPHIR_INIT(Phalcon_Assets_Collection);
	ZEPHIR_INIT(Phalcon_Assets_Exception);
	ZEPHIR_INIT(Phalcon_Assets_Filters_Cssmin);
	ZEPHIR_INIT(Phalcon_Assets_Filters_Jsmin);
	ZEPHIR_INIT(Phalcon_Assets_Filters_None);
	ZEPHIR_INIT(Phalcon_Assets_Inline_Css);
	ZEPHIR_INIT(Phalcon_Assets_Inline_Js);
	ZEPHIR_INIT(Phalcon_Assets_Manager);
	ZEPHIR_INIT(Phalcon_Autoload_Exception);
	ZEPHIR_INIT(Phalcon_Autoload_Loader);
	ZEPHIR_INIT(Phalcon_Cache_AdapterFactory);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Apcu);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Libmemcached);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Memory);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Redis);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Stream);
	ZEPHIR_INIT(Phalcon_Cache_Adapter_Weak);
	ZEPHIR_INIT(Phalcon_Cache_Cache);
	ZEPHIR_INIT(Phalcon_Cache_CacheFactory);
	ZEPHIR_INIT(Phalcon_Cache_Exception_Exception);
	ZEPHIR_INIT(Phalcon_Cache_Exception_InvalidArgumentException);
	ZEPHIR_INIT(Phalcon_Cli_Console);
	ZEPHIR_INIT(Phalcon_Cli_Console_Exception);
	ZEPHIR_INIT(Phalcon_Cli_Dispatcher);
	ZEPHIR_INIT(Phalcon_Cli_Dispatcher_Exception);
	ZEPHIR_INIT(Phalcon_Cli_Router);
	ZEPHIR_INIT(Phalcon_Cli_Router_Exception);
	ZEPHIR_INIT(Phalcon_Cli_Router_Route);
	ZEPHIR_INIT(Phalcon_Cli_Task);
	ZEPHIR_INIT(Phalcon_Config_Adapter_Grouped);
	ZEPHIR_INIT(Phalcon_Config_Adapter_Ini);
	ZEPHIR_INIT(Phalcon_Config_Adapter_Json);
	ZEPHIR_INIT(Phalcon_Config_Adapter_Php);
	ZEPHIR_INIT(Phalcon_Config_Adapter_Yaml);
	ZEPHIR_INIT(Phalcon_Config_ConfigFactory);
	ZEPHIR_INIT(Phalcon_Config_Exception);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Connection);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_ConnectionLocator);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Connection_Decorated);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Exception_CannotDisconnect);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Exception_ConnectionNotFound);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Profiler_MemoryLogger);
	ZEPHIR_INIT(Phalcon_DataMapper_Pdo_Profiler_Profiler);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_Bind);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_Delete);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_Insert);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_QueryFactory);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_Select);
	ZEPHIR_INIT(Phalcon_DataMapper_Query_Update);
	ZEPHIR_INIT(Phalcon_Db_Adapter_PdoFactory);
	ZEPHIR_INIT(Phalcon_Db_Adapter_Pdo_Mysql);
	ZEPHIR_INIT(Phalcon_Db_Adapter_Pdo_Postgresql);
	ZEPHIR_INIT(Phalcon_Db_Adapter_Pdo_Sqlite);
	ZEPHIR_INIT(Phalcon_Db_Column);
	ZEPHIR_INIT(Phalcon_Db_Dialect_Mysql);
	ZEPHIR_INIT(Phalcon_Db_Dialect_Postgresql);
	ZEPHIR_INIT(Phalcon_Db_Dialect_Sqlite);
	ZEPHIR_INIT(Phalcon_Db_Enum);
	ZEPHIR_INIT(Phalcon_Db_Exception);
	ZEPHIR_INIT(Phalcon_Db_Index);
	ZEPHIR_INIT(Phalcon_Db_Profiler);
	ZEPHIR_INIT(Phalcon_Db_Profiler_Item);
	ZEPHIR_INIT(Phalcon_Db_RawValue);
	ZEPHIR_INIT(Phalcon_Db_Reference);
	ZEPHIR_INIT(Phalcon_Db_Result_PdoResult);
	ZEPHIR_INIT(Phalcon_Di_Exception_ServiceResolutionException);
	ZEPHIR_INIT(Phalcon_Di_FactoryDefault_Cli);
	ZEPHIR_INIT(Phalcon_Di_Service);
	ZEPHIR_INIT(Phalcon_Di_Service_Builder);
	ZEPHIR_INIT(Phalcon_Domain_Payload_Payload);
	ZEPHIR_INIT(Phalcon_Domain_Payload_PayloadFactory);
	ZEPHIR_INIT(Phalcon_Domain_Payload_Status);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Exception_Mismatch);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_PadFactory);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Ansi);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Iso10126);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_IsoIek);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Noop);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Pkcs7);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Space);
	ZEPHIR_INIT(Phalcon_Encryption_Crypt_Padding_Zero);
	ZEPHIR_INIT(Phalcon_Encryption_Security);
	ZEPHIR_INIT(Phalcon_Encryption_Security_Exception);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Builder);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Exceptions_UnsupportedAlgorithmException);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Exceptions_ValidatorException);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Signer_Hmac);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Signer_None);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_Enum);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_Item);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_Parser);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_Signature);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Token_Token);
	ZEPHIR_INIT(Phalcon_Encryption_Security_JWT_Validator);
	ZEPHIR_INIT(Phalcon_Encryption_Security_Random);
	ZEPHIR_INIT(Phalcon_Events_Event);
	ZEPHIR_INIT(Phalcon_Events_Exception);
	ZEPHIR_INIT(Phalcon_Events_Manager);
	ZEPHIR_INIT(Phalcon_Factory_Exception);
	ZEPHIR_INIT(Phalcon_Filter_Exception);
	ZEPHIR_INIT(Phalcon_Filter_Filter);
	ZEPHIR_INIT(Phalcon_Filter_FilterFactory);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_AbsInt);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Alnum);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Alpha);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_BoolVal);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Email);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_FloatVal);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_IntVal);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Lower);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_LowerFirst);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Regex);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Remove);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Replace);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Special);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_SpecialFull);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_StringVal);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_StringValLegacy);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Striptags);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Trim);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Upper);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_UpperFirst);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_UpperWords);
	ZEPHIR_INIT(Phalcon_Filter_Sanitize_Url);
	ZEPHIR_INIT(Phalcon_Filter_Validation);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Exception);
	ZEPHIR_INIT(Phalcon_Filter_Validation_ValidatorFactory);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Alnum);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Alpha);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Between);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Callback);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Confirmation);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_CreditCard);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Date);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Digit);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Email);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Exception);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_ExclusionIn);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_MimeType);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Resolution_Equal);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Resolution_Max);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Resolution_Min);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Size_Max);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_File_Size_Min);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Identical);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_InclusionIn);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Ip);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Numericality);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_PresenceOf);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Regex);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_StringLength);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_StringLength_Max);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_StringLength_Min);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Uniqueness);
	ZEPHIR_INIT(Phalcon_Filter_Validation_Validator_Url);
	ZEPHIR_INIT(Phalcon_Flash_Direct);
	ZEPHIR_INIT(Phalcon_Flash_Exception);
	ZEPHIR_INIT(Phalcon_Flash_Session);
	ZEPHIR_INIT(Phalcon_Forms_Element_Check);
	ZEPHIR_INIT(Phalcon_Forms_Element_Date);
	ZEPHIR_INIT(Phalcon_Forms_Element_Email);
	ZEPHIR_INIT(Phalcon_Forms_Element_File);
	ZEPHIR_INIT(Phalcon_Forms_Element_Hidden);
	ZEPHIR_INIT(Phalcon_Forms_Element_Numeric);
	ZEPHIR_INIT(Phalcon_Forms_Element_Password);
	ZEPHIR_INIT(Phalcon_Forms_Element_Radio);
	ZEPHIR_INIT(Phalcon_Forms_Element_Select);
	ZEPHIR_INIT(Phalcon_Forms_Element_Submit);
	ZEPHIR_INIT(Phalcon_Forms_Element_Text);
	ZEPHIR_INIT(Phalcon_Forms_Element_TextArea);
	ZEPHIR_INIT(Phalcon_Forms_Exception);
	ZEPHIR_INIT(Phalcon_Forms_Form);
	ZEPHIR_INIT(Phalcon_Forms_Manager);
	ZEPHIR_INIT(Phalcon_Html_Attributes);
	ZEPHIR_INIT(Phalcon_Html_Breadcrumbs);
	ZEPHIR_INIT(Phalcon_Html_Escaper);
	ZEPHIR_INIT(Phalcon_Html_EscaperFactory);
	ZEPHIR_INIT(Phalcon_Html_Escaper_Exception);
	ZEPHIR_INIT(Phalcon_Html_Exception);
	ZEPHIR_INIT(Phalcon_Html_Helper_Anchor);
	ZEPHIR_INIT(Phalcon_Html_Helper_Base);
	ZEPHIR_INIT(Phalcon_Html_Helper_Body);
	ZEPHIR_INIT(Phalcon_Html_Helper_Button);
	ZEPHIR_INIT(Phalcon_Html_Helper_Close);
	ZEPHIR_INIT(Phalcon_Html_Helper_Doctype);
	ZEPHIR_INIT(Phalcon_Html_Helper_Element);
	ZEPHIR_INIT(Phalcon_Html_Helper_Form);
	ZEPHIR_INIT(Phalcon_Html_Helper_Img);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Color);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Date);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_DateTime);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_DateTimeLocal);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Email);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_File);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Hidden);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Image);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Input);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Month);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Numeric);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Password);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Radio);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Range);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Search);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Select);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Submit);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Tel);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Text);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Textarea);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Time);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Url);
	ZEPHIR_INIT(Phalcon_Html_Helper_Input_Week);
	ZEPHIR_INIT(Phalcon_Html_Helper_Label);
	ZEPHIR_INIT(Phalcon_Html_Helper_Link);
	ZEPHIR_INIT(Phalcon_Html_Helper_Meta);
	ZEPHIR_INIT(Phalcon_Html_Helper_Script);
	ZEPHIR_INIT(Phalcon_Html_Helper_Title);
	ZEPHIR_INIT(Phalcon_Html_Helper_Ul);
	ZEPHIR_INIT(Phalcon_Html_Link_EvolvableLink);
	ZEPHIR_INIT(Phalcon_Html_Link_EvolvableLinkProvider);
	ZEPHIR_INIT(Phalcon_Html_Link_Serializer_Header);
	ZEPHIR_INIT(Phalcon_Html_TagFactory);
	ZEPHIR_INIT(Phalcon_Http_Cookie);
	ZEPHIR_INIT(Phalcon_Http_Cookie_Exception);
	ZEPHIR_INIT(Phalcon_Http_Request);
	ZEPHIR_INIT(Phalcon_Http_Request_Exception);
	ZEPHIR_INIT(Phalcon_Http_Request_File);
	ZEPHIR_INIT(Phalcon_Http_Response);
	ZEPHIR_INIT(Phalcon_Http_Response_Cookies);
	ZEPHIR_INIT(Phalcon_Http_Response_Exception);
	ZEPHIR_INIT(Phalcon_Http_Response_Headers);
	ZEPHIR_INIT(Phalcon_Image_Adapter_Gd);
	ZEPHIR_INIT(Phalcon_Image_Adapter_Imagick);
	ZEPHIR_INIT(Phalcon_Image_Enum);
	ZEPHIR_INIT(Phalcon_Image_Exception);
	ZEPHIR_INIT(Phalcon_Image_ImageFactory);
	ZEPHIR_INIT(Phalcon_Logger_AdapterFactory);
	ZEPHIR_INIT(Phalcon_Logger_Adapter_Noop);
	ZEPHIR_INIT(Phalcon_Logger_Adapter_Stream);
	ZEPHIR_INIT(Phalcon_Logger_Adapter_Syslog);
	ZEPHIR_INIT(Phalcon_Logger_Enum);
	ZEPHIR_INIT(Phalcon_Logger_Exception);
	ZEPHIR_INIT(Phalcon_Logger_Formatter_Json);
	ZEPHIR_INIT(Phalcon_Logger_Formatter_Line);
	ZEPHIR_INIT(Phalcon_Logger_Item);
	ZEPHIR_INIT(Phalcon_Logger_Logger);
	ZEPHIR_INIT(Phalcon_Logger_LoggerFactory);
	ZEPHIR_INIT(Phalcon_Messages_Exception);
	ZEPHIR_INIT(Phalcon_Messages_Message);
	ZEPHIR_INIT(Phalcon_Messages_Messages);
	ZEPHIR_INIT(Phalcon_Mvc_Application);
	ZEPHIR_INIT(Phalcon_Mvc_Application_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_Controller);
	ZEPHIR_INIT(Phalcon_Mvc_Dispatcher);
	ZEPHIR_INIT(Phalcon_Mvc_Dispatcher_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_Micro);
	ZEPHIR_INIT(Phalcon_Mvc_Micro_Collection);
	ZEPHIR_INIT(Phalcon_Mvc_Micro_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_Micro_LazyLoader);
	ZEPHIR_INIT(Phalcon_Mvc_Model);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Behavior_SoftDelete);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Behavior_Timestampable);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Binder);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Criteria);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Manager);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Apcu);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Libmemcached);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Memory);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Redis);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Strategy_Annotations);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Strategy_Introspection);
	ZEPHIR_INIT(Phalcon_Mvc_Model_MetaData_Stream);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query_Builder);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query_Lang);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Query_Status);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Relation);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Resultset_Complex);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Resultset_Simple);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Row);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Transaction);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Transaction_Failed);
	ZEPHIR_INIT(Phalcon_Mvc_Model_Transaction_Manager);
	ZEPHIR_INIT(Phalcon_Mvc_Model_ValidationFailed);
	ZEPHIR_INIT(Phalcon_Mvc_Router_Annotations);
	ZEPHIR_INIT(Phalcon_Mvc_Router_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_Router_Group);
	ZEPHIR_INIT(Phalcon_Mvc_Router_Route);
	ZEPHIR_INIT(Phalcon_Mvc_Url);
	ZEPHIR_INIT(Phalcon_Mvc_Url_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_View);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_Php);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_Volt);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_Volt_Compiler);
	ZEPHIR_INIT(Phalcon_Mvc_View_Engine_Volt_Exception);
	ZEPHIR_INIT(Phalcon_Mvc_View_Simple);
	ZEPHIR_INIT(Phalcon_Paginator_Adapter_Model);
	ZEPHIR_INIT(Phalcon_Paginator_Adapter_NativeArray);
	ZEPHIR_INIT(Phalcon_Paginator_Adapter_QueryBuilder);
	ZEPHIR_INIT(Phalcon_Paginator_Exception);
	ZEPHIR_INIT(Phalcon_Paginator_PaginatorFactory);
	ZEPHIR_INIT(Phalcon_Paginator_Repository);
	ZEPHIR_INIT(Phalcon_Session_Adapter_Libmemcached);
	ZEPHIR_INIT(Phalcon_Session_Adapter_Redis);
	ZEPHIR_INIT(Phalcon_Session_Adapter_Stream);
	ZEPHIR_INIT(Phalcon_Session_Bag);
	ZEPHIR_INIT(Phalcon_Session_Exception);
	ZEPHIR_INIT(Phalcon_Session_Manager);
	ZEPHIR_INIT(Phalcon_Storage_AdapterFactory);
	ZEPHIR_INIT(Phalcon_Storage_Exception);
	ZEPHIR_INIT(Phalcon_Storage_SerializerFactory);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_Base64);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_Json);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_MemcachedIgbinary);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_MemcachedJson);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_MemcachedPhp);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_Msgpack);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_Php);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_RedisIgbinary);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_RedisJson);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_RedisMsgpack);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_RedisNone);
	ZEPHIR_INIT(Phalcon_Storage_Serializer_RedisPhp);
	ZEPHIR_INIT(Phalcon_Support_Collection_Exception);
	ZEPHIR_INIT(Phalcon_Support_Collection_ReadOnlyCollection);
	ZEPHIR_INIT(Phalcon_Support_Debug);
	ZEPHIR_INIT(Phalcon_Support_Debug_Dump);
	ZEPHIR_INIT(Phalcon_Support_Debug_Exception);
	ZEPHIR_INIT(Phalcon_Support_Exception);
	ZEPHIR_INIT(Phalcon_Support_HelperFactory);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Blacklist);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Chunk);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Filter);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_First);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_FirstKey);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Flatten);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Get);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Group);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Has);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_IsUnique);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Last);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_LastKey);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Order);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Pluck);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Set);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_SliceLeft);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_SliceRight);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Split);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_ToObject);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_ValidateAll);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_ValidateAny);
	ZEPHIR_INIT(Phalcon_Support_Helper_Arr_Whitelist);
	ZEPHIR_INIT(Phalcon_Support_Helper_Exception);
	ZEPHIR_INIT(Phalcon_Support_Helper_File_Basename);
	ZEPHIR_INIT(Phalcon_Support_Helper_Json_Decode);
	ZEPHIR_INIT(Phalcon_Support_Helper_Json_Encode);
	ZEPHIR_INIT(Phalcon_Support_Helper_Number_IsBetween);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Camelize);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Concat);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_CountVowels);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Decapitalize);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Decrement);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_DirFromFile);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_DirSeparator);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Dynamic);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_EndsWith);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_FirstBetween);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Friendly);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Humanize);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Includes);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Increment);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Interpolate);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_IsAnagram);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_IsLower);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_IsPalindrome);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_IsUpper);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_KebabCase);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Len);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Lower);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Prefix);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Random);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_ReduceSlashes);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_SnakeCase);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_StartsWith);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Suffix);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Ucwords);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Uncamelize);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Underscore);
	ZEPHIR_INIT(Phalcon_Support_Helper_Str_Upper);
	ZEPHIR_INIT(Phalcon_Support_Registry);
	ZEPHIR_INIT(Phalcon_Support_Version);
	ZEPHIR_INIT(Phalcon_Tag);
	ZEPHIR_INIT(Phalcon_Tag_Exception);
	ZEPHIR_INIT(Phalcon_Tag_Select);
	ZEPHIR_INIT(Phalcon_Translate_Adapter_Csv);
	ZEPHIR_INIT(Phalcon_Translate_Adapter_Gettext);
	ZEPHIR_INIT(Phalcon_Translate_Adapter_NativeArray);
	ZEPHIR_INIT(Phalcon_Translate_Exception);
	ZEPHIR_INIT(Phalcon_Translate_InterpolatorFactory);
	ZEPHIR_INIT(Phalcon_Translate_Interpolator_AssociativeArray);
	ZEPHIR_INIT(Phalcon_Translate_Interpolator_IndexedArray);
	ZEPHIR_INIT(Phalcon_Translate_TranslateFactory);
	ZEPHIR_INIT(phalcon_0__closure);
	ZEPHIR_INIT(phalcon_10__closure);
	ZEPHIR_INIT(phalcon_11__closure);
	ZEPHIR_INIT(phalcon_12__closure);
	ZEPHIR_INIT(phalcon_13__closure);
	ZEPHIR_INIT(phalcon_14__closure);
	ZEPHIR_INIT(phalcon_1__closure);
	ZEPHIR_INIT(phalcon_2__closure);
	ZEPHIR_INIT(phalcon_3__closure);
	ZEPHIR_INIT(phalcon_4__closure);
	ZEPHIR_INIT(phalcon_5__closure);
	ZEPHIR_INIT(phalcon_6__closure);
	ZEPHIR_INIT(phalcon_7__closure);
	ZEPHIR_INIT(phalcon_8__closure);
	ZEPHIR_INIT(phalcon_9__closure);
	
	return SUCCESS;
}

#ifndef ZEPHIR_RELEASE
static PHP_MSHUTDOWN_FUNCTION(phalcon)
{
	
	zephir_deinitialize_memory();
	UNREGISTER_INI_ENTRIES();
	return SUCCESS;
}
#endif

/**
 * Initialize globals on each request or each thread started
 */
static void php_zephir_init_globals(zend_phalcon_globals *phalcon_globals)
{
	phalcon_globals->initialized = 0;

	/* Cache Enabled */
	phalcon_globals->cache_enabled = 1;

	/* Recursive Lock */
	phalcon_globals->recursive_lock = 0;

	/* Static cache */
	memset(phalcon_globals->scache, '\0', sizeof(zephir_fcall_cache_entry*) * ZEPHIR_MAX_CACHE_SLOTS);

	


	phalcon_globals->orm.ast_cache = NULL;
	phalcon_globals->orm.cache_level = 3;













	phalcon_globals->orm.parser_cache = NULL;
	phalcon_globals->orm.resultset_prefetch_records = ZSTR_VAL(zend_string_init(ZEND_STRL("0"), 0));
	phalcon_globals->orm.unique_cache_id = 3;




	
}

/**
 * Initialize globals only on each thread started
 */
static void php_zephir_init_module_globals(zend_phalcon_globals *phalcon_globals)
{
	
}

static PHP_RINIT_FUNCTION(phalcon)
{
	zend_phalcon_globals *phalcon_globals_ptr;
	phalcon_globals_ptr = ZEPHIR_VGLOBAL;

	php_zephir_init_globals(phalcon_globals_ptr);
	zephir_initialize_memory(phalcon_globals_ptr);

	
	return SUCCESS;
}

static PHP_RSHUTDOWN_FUNCTION(phalcon)
{
	phalcon_orm_destroy_cache();
	zephir_deinitialize_memory();
	return SUCCESS;
}



static PHP_MINFO_FUNCTION(phalcon)
{
	php_info_print_box_start(0);
	php_printf("%s", PHP_PHALCON_DESCRIPTION);
	php_info_print_box_end();

	php_info_print_table_start();
	php_info_print_table_header(2, PHP_PHALCON_NAME, "enabled");
	php_info_print_table_row(2, "Author", PHP_PHALCON_AUTHOR);
	php_info_print_table_row(2, "Version", PHP_PHALCON_VERSION);
	php_info_print_table_row(2, "Build Date", __DATE__ " " __TIME__ );
	php_info_print_table_row(2, "Powered by Zephir", "Version " PHP_PHALCON_ZEPVERSION);
	php_info_print_table_end();
	
	DISPLAY_INI_ENTRIES();
}

static PHP_GINIT_FUNCTION(phalcon)
{
#if defined(COMPILE_DL_PHALCON) && defined(ZTS)
	ZEND_TSRMLS_CACHE_UPDATE();
#endif

	php_zephir_init_globals(phalcon_globals);
	php_zephir_init_module_globals(phalcon_globals);
}

static PHP_GSHUTDOWN_FUNCTION(phalcon)
{
	
}


zend_function_entry php_phalcon_functions[] = {
	ZEND_FE_END

};

static const zend_module_dep php_phalcon_deps[] = {
	ZEND_MOD_REQUIRED("pdo")
	ZEND_MOD_REQUIRED("spl")
	ZEND_MOD_REQUIRED("standard")
	ZEND_MOD_REQUIRED("hash")
	ZEND_MOD_REQUIRED("json")
	ZEND_MOD_END
};

zend_module_entry phalcon_module_entry = {
	STANDARD_MODULE_HEADER_EX,
	NULL,
	php_phalcon_deps,
	PHP_PHALCON_EXTNAME,
	php_phalcon_functions,
	PHP_MINIT(phalcon),
#ifndef ZEPHIR_RELEASE
	PHP_MSHUTDOWN(phalcon),
#else
	NULL,
#endif
	PHP_RINIT(phalcon),
	PHP_RSHUTDOWN(phalcon),
	PHP_MINFO(phalcon),
	PHP_PHALCON_VERSION,
	ZEND_MODULE_GLOBALS(phalcon),
	PHP_GINIT(phalcon),
	PHP_GSHUTDOWN(phalcon),
#ifdef ZEPHIR_POST_REQUEST
	PHP_PRSHUTDOWN(phalcon),
#else
	NULL,
#endif
	STANDARD_MODULE_PROPERTIES_EX
};

/* implement standard "stub" routine to introduce ourselves to Zend */
#ifdef COMPILE_DL_PHALCON
# ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
# endif
ZEND_GET_MODULE(phalcon)
#endif
