
/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "forms/elementinterface.h"
#include "mvc/model/validatorinterface.h"
#include "validation/validatorinterface.h"
#include "mvc/model/metadatainterface.h"
#include "logger/adapterinterface.h"
#include "logger/formatterinterface.h"
#include "mvc/view/engineinterface.h"
#include "mvc/model/resultsetinterface.h"
#include "mvc/model/behaviorinterface.h"
#include "mvc/model/resultinterface.h"
#include "mvc/dispatcherinterface.h"
#include "mvc/model/queryinterface.h"
#include "mvc/router/routeinterface.h"
#include "mvc/model/query/statusinterface.h"
#include "mvc/model/query/builderinterface.h"
#include "mvc/collectioninterface.h"
#include "mvc/model/transactioninterface.h"
#include "mvc/urlinterface.h"
#include "mvc/viewinterface.h"
#include "mvc/modelinterface.h"
#include "mvc/micro/collectioninterface.h"
#include "mvc/routerinterface.h"
#include "mvc/model/relationinterface.h"
#include "mvc/model/managerinterface.h"
#include "mvc/model/transaction/managerinterface.h"
#include "mvc/model/criteriainterface.h"
#include "mvc/model/messageinterface.h"
#include "mvc/model/exception.h"
#include "forms/element.h"
#include "validation/validator.h"
#include "mvc/model/validator.h"
#include "mvc/model/metadata.h"
#include "logger/adapter.h"
#include "logger/formatter.h"
#include "mvc/model/resultset.h"
#include "mvc/model/behavior.h"
#include "mvc/view/engine.h"
#include "mvc/model/transaction/exception.h"
#include "mvc/router.h"
#include "validation/message.h"
#include "validation/exception.h"
#include "validation/message/group.h"
#include "validation/validator/regex.h"
#include "validation/validator/email.h"
#include "validation/validator/between.h"
#include "validation/validator/identical.h"
#include "validation/validator/presenceof.h"
#include "validation/validator/inclusionin.h"
#include "validation/validator/stringlength.h"
#include "validation/validator/exclusionin.h"
#include "validation/validator/confirmation.h"
#include "validation/validator/url.h"
#include "logger/item.h"
#include "logger/multiple.h"
#include "logger/exception.h"
#include "logger/formatter/json.h"
#include "logger/formatter/line.h"
#include "logger/formatter/firephp.h"
#include "logger/adapter/stream.h"
#include "logger/adapter/syslog.h"
#include "logger/adapter/file.h"
#include "logger/adapter/firephp.h"
#include "logger/formatter/syslog.h"
#include "forms/form.h"
#include "forms/manager.h"
#include "forms/exception.h"
#include "forms/element/text.h"
#include "forms/element/date.h"
#include "forms/element/file.h"
#include "forms/element/hidden.h"
#include "forms/element/select.h"
#include "forms/element/check.h"
#include "forms/element/numeric.h"
#include "forms/element/email.h"
#include "forms/element/submit.h"
#include "forms/element/password.h"
#include "forms/element/textarea.h"
#include "forms/element/radio.h"
#include "queue/beanstalk.h"
#include "queue/beanstalk/job.h"
#include "mvc/view.h"
#include "mvc/url.h"
#include "mvc/model.h"
#include "mvc/micro.h"
#include "mvc/application.h"
#include "mvc/application/exception.h"
#include "mvc/collection.h"
#include "mvc/controller.h"
#include "mvc/collection/exception.h"
#include "mvc/collection/document.h"
#include "mvc/collection/manager.h"
#include "mvc/collection/managerinterface.h"
#include "mvc/controllerinterface.h"
#include "mvc/dispatcher.h"
#include "mvc/dispatcher/exception.h"
#include "mvc/model/row.h"
#include "mvc/model/query.h"
#include "mvc/micro/collection.h"
#include "mvc/micro/exception.h"
#include "mvc/micro/lazyloader.h"
#include "mvc/micro/middlewareinterface.h"
#include "mvc/model/criteria.h"
#include "mvc/model/manager.h"
#include "mvc/model/message.h"
#include "mvc/model/relation.h"
#include "mvc/model/transaction.h"
#include "mvc/model/query/lang.h"
#include "mvc/model/validator/url.h"
#include "mvc/model/query/status.h"
#include "mvc/model/metadata/apc.h"
#include "mvc/model/metadata/files.h"
#include "mvc/model/query/builder.h"
#include "mvc/model/validator/regex.h"
#include "mvc/model/validationfailed.h"
#include "mvc/model/resultset/simple.h"
#include "mvc/model/resultset/complex.h"
#include "mvc/model/metadata/memory.h"
#include "mvc/model/metadata/xcache.h"
#include "mvc/model/validator/email.h"
#include "mvc/model/metadata/session.h"
#include "mvc/model/validator/uniqueness.h"
#include "mvc/model/validator/presenceof.h"
#include "mvc/model/transaction/failed.h"
#include "mvc/model/behavior/softdelete.h"
#include "mvc/model/transaction/manager.h"
#include "mvc/model/behavior/timestampable.h"
#include "mvc/model/metadata/strategy/annotations.h"
#include "mvc/model/metadata/strategy/introspection.h"
#include "mvc/model/validator/inclusionin.h"
#include "mvc/model/validator/numericality.h"
#include "mvc/model/validator/exclusionin.h"
#include "mvc/model/validator/stringlength.h"
#include "mvc/moduledefinitioninterface.h"
#include "mvc/router/route.h"
#include "mvc/router/group.h"
#include "mvc/router/exception.h"
#include "mvc/router/annotations.h"
#include "mvc/url/exception.h"
#include "mvc/view/simple.h"
#include "mvc/view/exception.h"
#include "mvc/view/engine/volt.h"
#include "mvc/view/engine/pphp.h"
#include "mvc/view/engine/volt/compiler.h"

extern int nusphere_dbg_present;
