
extern zend_class_entry *phalcon_acl_exceptions_circularinheritanceerror_ce;

ZEPHIR_INIT_CLASS(Phalcon_Acl_Exceptions_CircularInheritanceError);

PHP_METHOD(Phalcon_Acl_Exceptions_CircularInheritanceError, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_acl_exceptions_circularinheritanceerror___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, roleName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_acl_exceptions_circularinheritanceerror_method_entry) {
	PHP_ME(Phalcon_Acl_Exceptions_CircularInheritanceError, __construct, arginfo_phalcon_acl_exceptions_circularinheritanceerror___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
