#define PHVOLT_COMMA                           1
#define PHVOLT_SBRACKET_OPEN                   2
#define PHVOLT_RANGE                           3
#define PHVOLT_EQUALS                          4
#define PHVOLT_NOTEQUALS                       5
#define PHVOLT_LESS                            6
#define PHVOLT_GREATER                         7
#define PHVOLT_GREATEREQUAL                    8
#define PHVOLT_LESSEQUAL                       9
#define PHVOLT_IDENTICAL                      10
#define PHVOLT_NOTIDENTICAL                   11
#define PHVOLT_AND                            12
#define PHVOLT_OR                             13
#define PHVOLT_PIPE                           14
#define PHVOLT_DIVIDE                         15
#define PHVOLT_TIMES                          16
#define PHVOLT_MOD                            17
#define PHVOLT_PLUS                           18
#define PHVOLT_MINUS                          19
#define PHVOLT_CONCAT                         20
#define PHVOLT_NOT                            21
#define PHVOLT_DOT                            22
#define PHVOLT_OPEN_DELIMITER                 23
#define PHVOLT_IF                             24
#define PHVOLT_CLOSE_DELIMITER                25
#define PHVOLT_ENDIF                          26
#define PHVOLT_ELSE                           27
#define PHVOLT_FOR                            28
#define PHVOLT_IN                             29
#define PHVOLT_ENDFOR                         30
#define PHVOLT_SET                            31
#define PHVOLT_ASSIGN                         32
#define PHVOLT_OPEN_EDELIMITER                33
#define PHVOLT_CLOSE_EDELIMITER               34
#define PHVOLT_RAW_FRAGMENT                   35
#define PHVOLT_BRACKET_OPEN                   36
#define PHVOLT_BRACKET_CLOSE                  37
#define PHVOLT_SBRACKET_CLOSE                 38
#define PHVOLT_STRING                         39
#define PHVOLT_DOUBLECOLON                    40
#define PHVOLT_IDENTIFIER                     41
#define PHVOLT_INTEGER                        42
#define PHVOLT_DOUBLE                         43
#define PHVOLT_NULL                           44
#define PHVOLT_FALSE                          45
#define PHVOLT_TRUE                           46
