#define PHVOLT_COMMA                           1
#define PHVOLT_DOUBLECOLON                     2
#define PHVOLT_SBRACKET_OPEN                   3
#define PHVOLT_RANGE                           4
#define PHVOLT_AND                             5
#define PHVOLT_OR                              6
#define PHVOLT_IS                              7
#define PHVOLT_EQUALS                          8
#define PHVOLT_NOTEQUALS                       9
#define PHVOLT_LESS                           10
#define PHVOLT_GREATER                        11
#define PHVOLT_GREATEREQUAL                   12
#define PHVOLT_LESSEQUAL                      13
#define PHVOLT_IDENTICAL                      14
#define PHVOLT_NOTIDENTICAL                   15
#define PHVOLT_PIPE                           16
#define PHVOLT_DIVIDE                         17
#define PHVOLT_TIMES                          18
#define PHVOLT_MOD                            19
#define PHVOLT_PLUS                           20
#define PHVOLT_MINUS                          21
#define PHVOLT_CONCAT                         22
#define PHVOLT_BRACKET_OPEN                   23
#define PHVOLT_NOT                            24
#define PHVOLT_DOT                            25
#define PHVOLT_OPEN_DELIMITER                 26
#define PHVOLT_IF                             27
#define PHVOLT_CLOSE_DELIMITER                28
#define PHVOLT_ENDIF                          29
#define PHVOLT_ELSE                           30
#define PHVOLT_FOR                            31
#define PHVOLT_IDENTIFIER                     32
#define PHVOLT_IN                             33
#define PHVOLT_ENDFOR                         34
#define PHVOLT_SET                            35
#define PHVOLT_ASSIGN                         36
#define PHVOLT_OPEN_EDELIMITER                37
#define PHVOLT_CLOSE_EDELIMITER               38
#define PHVOLT_BLOCK                          39
#define PHVOLT_ENDBLOCK                       40
#define PHVOLT_CACHE                          41
#define PHVOLT_ENDCACHE                       42
#define PHVOLT_INTEGER                        43
#define PHVOLT_EXTENDS                        44
#define PHVOLT_STRING                         45
#define PHVOLT_INCLUDE                        46
#define PHVOLT_DO                             47
#define PHVOLT_AUTOESCAPE                     48
#define PHVOLT_FALSE                          49
#define PHVOLT_ENDAUTOESCAPE                  50
#define PHVOLT_TRUE                           51
#define PHVOLT_BREAK                          52
#define PHVOLT_CONTINUE                       53
#define PHVOLT_RAW_FRAGMENT                   54
#define PHVOLT_DEFINED                        55
#define PHVOLT_BRACKET_CLOSE                  56
#define PHVOLT_SBRACKET_CLOSE                 57
#define PHVOLT_DOUBLE                         58
#define PHVOLT_NULL                           59
