
extern zend_class_entry *phalcon_filter_validation_exceptions_filterserviceunavailable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Filter_Validation_Exceptions_FilterServiceUnavailable);

PHP_METHOD(Phalcon_Filter_Validation_Exceptions_FilterServiceUnavailable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_filter_validation_exceptions_filterserviceunavailable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_filter_validation_exceptions_filterserviceunavailable_method_entry) {
PHP_ME(Phalcon_Filter_Validation_Exceptions_FilterServiceUnavailable, __construct, arginfo_phalcon_filter_validation_exceptions_filterserviceunavailable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
