
extern zend_class_entry *phalcon_filter_validation_exceptions_novalidatorsincomposite_ce;

ZEPHIR_INIT_CLASS(Phalcon_Filter_Validation_Exceptions_NoValidatorsInComposite);

PHP_METHOD(Phalcon_Filter_Validation_Exceptions_NoValidatorsInComposite, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_filter_validation_exceptions_novalidatorsincomposite___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, className, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_filter_validation_exceptions_novalidatorsincomposite_method_entry) {
	PHP_ME(Phalcon_Filter_Validation_Exceptions_NoValidatorsInComposite, __construct, arginfo_phalcon_filter_validation_exceptions_novalidatorsincomposite___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
