
extern zend_class_entry *phalcon_cli_router_exceptions_beforematchnotcallable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Cli_Router_Exceptions_BeforeMatchNotCallable);

PHP_METHOD(Phalcon_Cli_Router_Exceptions_BeforeMatchNotCallable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_cli_router_exceptions_beforematchnotcallable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_cli_router_exceptions_beforematchnotcallable_method_entry) {
PHP_ME(Phalcon_Cli_Router_Exceptions_BeforeMatchNotCallable, __construct, arginfo_phalcon_cli_router_exceptions_beforematchnotcallable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
