
extern zend_class_entry *phalcon_cli_router_exceptions_routerargumentsinvalidtype_ce;

ZEPHIR_INIT_CLASS(Phalcon_Cli_Router_Exceptions_RouterArgumentsInvalidType);

PHP_METHOD(Phalcon_Cli_Router_Exceptions_RouterArgumentsInvalidType, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_cli_router_exceptions_routerargumentsinvalidtype___construct, 0, 0, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, type, IS_STRING, 0, "''")
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_cli_router_exceptions_routerargumentsinvalidtype_method_entry) {
	PHP_ME(Phalcon_Cli_Router_Exceptions_RouterArgumentsInvalidType, __construct, arginfo_phalcon_cli_router_exceptions_routerargumentsinvalidtype___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
