#! /bin/sh

if [ ! -f lemon ]; then
	gcc lemon.c -o lemon
fi
rm -f *.o
rm -f *.lo
re2c -o scanner.c scanner.re && ./lemon parser.lemon && cat base.c >> parser.c
sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
sed s/YY/PP/g scanner.c > xx && mv -f xx scanner.c
sed s/yy/pp/g scanner.c > xx && mv -f xx scanner.c
sed s/YY/PP/g parser.c > xx && mv -f xx parser.c
sed s/yy/pp/g parser.c > xx && mv -f xx parser.c
sed s/"define TOKEN"/"define PPTOKEN"/g parser.c > xx && mv -f xx parser.c
