#define PHQL_AGAINST                         1
#define PHQL_BETWEEN                         2
#define PHQL_EQUALS                          3
#define PHQL_NOTEQUALS                       4
#define PHQL_LESS                            5
#define PHQL_GREATER                         6
#define PHQL_GREATEREQUAL                    7
#define PHQL_LESSEQUAL                       8
#define PHQL_AND                             9
#define PHQL_OR                             10
#define PHQL_LIKE                           11
#define PHQL_ILIKE                          12
#define PHQL_BITWISE_AND                    13
#define PHQL_BITWISE_OR                     14
#define PHQL_BITWISE_XOR                    15
#define PHQL_DIVIDE                         16
#define PHQL_TIMES                          17
#define PHQL_MOD                            18
#define PHQL_PLUS                           19
#define PHQL_MINUS                          20
#define PHQL_IS                             21
#define PHQL_IN                             22
#define PHQL_NOT                            23
#define PHQL_BITWISE_NOT                    24
#define PHQL_COMMA                          25
#define PHQL_SELECT                         26
#define PHQL_FROM                           27
#define PHQL_DISTINCT                       28
#define PHQL_ALL                            29
#define PHQL_IDENTIFIER                     30
#define PHQL_DOT                            31
#define PHQL_AS                             32
#define PHQL_INNER                          33
#define PHQL_JOIN                           34
#define PHQL_CROSS                          35
#define PHQL_LEFT                           36
#define PHQL_OUTER                          37
#define PHQL_RIGHT                          38
#define PHQL_FULL                           39
#define PHQL_ON                             40
#define PHQL_INSERT                         41
#define PHQL_INTO                           42
#define PHQL_VALUES                         43
#define PHQL_PARENTHESES_OPEN               44
#define PHQL_PARENTHESES_CLOSE              45
#define PHQL_UPDATE                         46
#define PHQL_SET                            47
#define PHQL_DELETE                         48
#define PHQL_WHERE                          49
#define PHQL_ORDER                          50
#define PHQL_BY                             51
#define PHQL_ASC                            52
#define PHQL_DESC                           53
#define PHQL_GROUP                          54
#define PHQL_HAVING                         55
#define PHQL_LIMIT                          56
#define PHQL_OFFSET                         57
#define PHQL_INTEGER                        58
#define PHQL_NPLACEHOLDER                   59
#define PHQL_SPLACEHOLDER                   60
#define PHQL_EXISTS                         61
#define PHQL_CAST                           62
#define PHQL_CONVERT                        63
#define PHQL_USING                          64
#define PHQL_CASE                           65
#define PHQL_END                            66
#define PHQL_WHEN                           67
#define PHQL_THEN                           68
#define PHQL_ELSE                           69
#define PHQL_NULL                           70
#define PHQL_STRING                         71
#define PHQL_DOUBLE                         72
#define PHQL_TRUE                           73
#define PHQL_FALSE                          74
#define PHQL_NTPLACEHOLDER                  75
#define PHQL_STPLACEHOLDER                  76
