#define PHQL_AGAINST                         1
#define PHQL_BETWEEN                         2
#define PHQL_BETWEEN_NOT                     3
#define PHQL_EQUALS                          4
#define PHQL_NOTEQUALS                       5
#define PHQL_LESS                            6
#define PHQL_GREATER                         7
#define PHQL_GREATEREQUAL                    8
#define PHQL_LESSEQUAL                       9
#define PHQL_OP_MATCHES                     10
#define PHQL_OP_CONTAINS                    11
#define PHQL_OP_CONTAINED                   12
#define PHQL_OP_OVERLAPS                    13
#define PHQL_AND                            14
#define PHQL_OR                             15
#define PHQL_LIKE                           16
#define PHQL_ILIKE                          17
#define PHQL_BITWISE_AND                    18
#define PHQL_BITWISE_OR                     19
#define PHQL_BITWISE_XOR                    20
#define PHQL_DIVIDE                         21
#define PHQL_TIMES                          22
#define PHQL_MOD                            23
#define PHQL_PLUS                           24
#define PHQL_MINUS                          25
#define PHQL_OP_CONCAT                      26
#define PHQL_IS                             27
#define PHQL_IN                             28
#define PHQL_NOT                            29
#define PHQL_BITWISE_NOT                    30
#define PHQL_OP_JSON_GET                    31
#define PHQL_OP_JSON_GET_TEXT               32
#define PHQL_OP_JSON_PATH                   33
#define PHQL_OP_JSON_PATH_TEXT              34
#define PHQL_COMMA                          35
#define PHQL_UNION                          36
#define PHQL_ALL                            37
#define PHQL_SELECT                         38
#define PHQL_FROM                           39
#define PHQL_DISTINCT                       40
#define PHQL_IDENTIFIER                     41
#define PHQL_DOT                            42
#define PHQL_AS                             43
#define PHQL_INNER                          44
#define PHQL_JOIN                           45
#define PHQL_CROSS                          46
#define PHQL_LEFT                           47
#define PHQL_OUTER                          48
#define PHQL_RIGHT                          49
#define PHQL_FULL                           50
#define PHQL_ON                             51
#define PHQL_INSERT                         52
#define PHQL_INTO                           53
#define PHQL_VALUES                         54
#define PHQL_PARENTHESES_OPEN               55
#define PHQL_PARENTHESES_CLOSE              56
#define PHQL_UPDATE                         57
#define PHQL_SET                            58
#define PHQL_DELETE                         59
#define PHQL_WITH                           60
#define PHQL_RECURSIVE                      61
#define PHQL_WHERE                          62
#define PHQL_ORDER                          63
#define PHQL_BY                             64
#define PHQL_ASC                            65
#define PHQL_DESC                           66
#define PHQL_GROUP                          67
#define PHQL_HAVING                         68
#define PHQL_FOR                            69
#define PHQL_LIMIT                          70
#define PHQL_OFFSET                         71
#define PHQL_INTEGER                        72
#define PHQL_HINTEGER                       73
#define PHQL_NPLACEHOLDER                   74
#define PHQL_SPLACEHOLDER                   75
#define PHQL_BPLACEHOLDER                   76
#define PHQL_EXISTS                         77
#define PHQL_CAST                           78
#define PHQL_CONVERT                        79
#define PHQL_USING                          80
#define PHQL_CASE                           81
#define PHQL_END                            82
#define PHQL_WHEN                           83
#define PHQL_THEN                           84
#define PHQL_ELSE                           85
#define PHQL_NULL                           86
#define PHQL_STRING                         87
#define PHQL_DOUBLE                         88
#define PHQL_TRUE                           89
#define PHQL_FALSE                          90
