/* Generated by re2c 4.1 */
/* scanner.re
 * This file is part of the Phalcon Framework.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_phalcon.h"

#include "scanner.h"

#define PPCTYPE unsigned char
#define PPCURSOR (s->start)
#define PPLIMIT (s->end)
#define PPMARKER marker

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = PPCURSOR;
	char *marker = PPCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	
	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
		{
			PPCTYPE ppch;
			unsigned int ppaccept = 0;
			ppch = *PPCURSOR;
			switch (ppch) {
				case 0x00: goto pp1;
				case '\t':
				case '\n':
				case '\r':
				case ' ': goto pp4;
				case '!': goto pp6;
				case '"': goto pp8;
				case '%': goto pp9;
				case '&': goto pp10;
				case '\'': goto pp12;
				case '(': goto pp13;
				case ')': goto pp14;
				case '*': goto pp15;
				case '+': goto pp16;
				case ',': goto pp17;
				case '-': goto pp18;
				case '.': goto pp19;
				case '/': goto pp21;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp22;
				case ':': goto pp24;
				case '<': goto pp26;
				case '=': goto pp28;
				case '>': goto pp29;
				case '?': goto pp31;
				case '@': goto pp32;
				case 'A':
				case 'a': goto pp33;
				case 'B':
				case 'b': goto pp35;
				case 'C':
				case 'c': goto pp36;
				case 'D':
				case 'd': goto pp37;
				case 'E':
				case 'e': goto pp38;
				case 'F':
				case 'f': goto pp39;
				case 'G':
				case 'g': goto pp40;
				case 'H':
				case 'h': goto pp42;
				case 'I':
				case 'i': goto pp43;
				case 'J':
				case 'j': goto pp44;
				case 'K':
				case 'M':
				case 'P':
				case 'Q':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'k':
				case 'm':
				case 'p':
				case 'q':
				case 'y':
				case 'z': goto pp45;
				case 'L':
				case 'l': goto pp47;
				case 'N':
				case 'n': goto pp48;
				case 'O':
				case 'o': goto pp49;
				case 'R':
				case 'r': goto pp50;
				case 'S':
				case 's': goto pp51;
				case 'T':
				case 't': goto pp52;
				case 'U':
				case 'u': goto pp53;
				case 'V':
				case 'v': goto pp54;
				case 'W':
				case 'w': goto pp55;
				case '[': goto pp56;
				case '\\': goto pp57;
				case '^': goto pp58;
				case 'x': goto pp59;
				case '{': goto pp61;
				case '|': goto pp62;
				case '~': goto pp64;
				default: goto pp2;
			}
pp1:
			++PPCURSOR;
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
pp2:
			++PPCURSOR;
pp3:
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
pp4:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '\t':
				case '\n':
				case '\r':
				case ' ': goto pp4;
				default: goto pp5;
			}
pp5:
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
pp6:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '!': goto pp65;
				case '=': goto pp66;
				default: goto pp7;
			}
pp7:
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
pp8:
			ppaccept = 0;
			ppch = *(PPMARKER = ++PPCURSOR);
			if (ppch <= 0x00) goto pp3;
			goto pp68;
pp9:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
pp10:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '&': goto pp72;
				default: goto pp11;
			}
pp11:
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
pp12:
			ppaccept = 0;
			ppch = *(PPMARKER = ++PPCURSOR);
			if (ppch <= 0x00) goto pp3;
			goto pp74;
pp13:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
pp14:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
pp15:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
pp16:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
pp17:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
pp18:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
pp19:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp76;
				default: goto pp20;
			}
pp20:
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
pp21:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
pp22:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '.': goto pp76;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp22;
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'x': goto pp78;
				default: goto pp23;
			}
pp23:
			{
			token->opcode = PHQL_T_INTEGER;
			token->value = estrndup(q, PPCURSOR - q);
			token->len = PPCURSOR - q;
			q = PPCURSOR;
			return 0;
		}
pp24:
			ppaccept = 1;
			ppch = *(PPMARKER = ++PPCURSOR);
			switch (ppch) {
				case '-':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp79;
				default: goto pp25;
			}
pp25:
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
pp26:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '=': goto pp80;
				case '>': goto pp81;
				default: goto pp27;
			}
pp27:
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
pp28:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
pp29:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '=': goto pp82;
				default: goto pp30;
			}
pp30:
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
pp31:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp83;
				default: goto pp3;
			}
pp32:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '>': goto pp85;
				case '@': goto pp86;
				default: goto pp3;
			}
pp33:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'G':
				case 'g': goto pp87;
				case 'L':
				case 'l': goto pp88;
				case 'N':
				case 'n': goto pp89;
				case 'S':
				case 's': goto pp90;
				default: goto pp60;
			}
pp34:
			{
			token->value = estrndup(q, PPCURSOR - q);
			token->len = PPCURSOR - q;
			if (token->len > 2 && !memcmp(token->value, "0x", 2)) {
				token->opcode = PHQL_T_HINTEGER;
			} else {
				int i, alpha = 0;
				for (i = 0; i < token->len; i++) {
					unsigned char ch = token->value[i];
					if (!((ch >= '0') && (ch <= '9'))) {
						alpha = 1;
						break;
					}
				}
				if (alpha) {
					token->opcode = PHQL_T_IDENTIFIER;
				} else {
					token->opcode = PHQL_T_INTEGER;
				}
			}
			q = PPCURSOR;
			return 0;
		}
pp35:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp92;
				case 'Y':
				case 'y': goto pp93;
				default: goto pp60;
			}
pp36:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp95;
				case 'O':
				case 'o': goto pp96;
				case 'R':
				case 'r': goto pp97;
				default: goto pp60;
			}
pp37:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp98;
				case 'I':
				case 'i': goto pp99;
				default: goto pp60;
			}
pp38:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp100;
				case 'N':
				case 'n': goto pp101;
				case 'X': goto pp102;
				case 'x': goto pp103;
				default: goto pp60;
			}
pp39:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp104;
				case 'O':
				case 'o': goto pp105;
				case 'R':
				case 'r': goto pp106;
				case 'U':
				case 'u': goto pp107;
				default: goto pp60;
			}
pp40:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp108;
				default: goto pp46;
			}
pp41:
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((PPCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, PPCURSOR - q - 1);
					token->len = PPCURSOR - q - 1;
				} else {
					token->value = estrndup(q, PPCURSOR - q);
					token->len = PPCURSOR - q;
				}
			} else {
				token->value = estrndup(q, PPCURSOR - q);
				token->len = PPCURSOR - q;
			}
			q = PPCURSOR;
			return 0;
		}
pp42:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp109;
				default: goto pp46;
			}
pp43:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp110;
				case 'N':
				case 'n': goto pp111;
				case 'S':
				case 's': goto pp113;
				default: goto pp46;
			}
pp44:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp115;
				default: goto pp46;
			}
pp45:
			ppch = *++PPCURSOR;
pp46:
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp41;
			}
pp47:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp116;
				case 'I':
				case 'i': goto pp117;
				default: goto pp46;
			}
pp48:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp118;
				case 'U':
				case 'u': goto pp119;
				default: goto pp46;
			}
pp49:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'F':
				case 'f': goto pp120;
				case 'N':
				case 'n': goto pp121;
				case 'R':
				case 'r': goto pp123;
				case 'U':
				case 'u': goto pp125;
				default: goto pp46;
			}
pp50:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp126;
				default: goto pp46;
			}
pp51:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp127;
				default: goto pp46;
			}
pp52:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'H':
				case 'h': goto pp128;
				case 'R':
				case 'r': goto pp129;
				default: goto pp46;
			}
pp53:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'P':
				case 'p': goto pp130;
				case 'S':
				case 's': goto pp131;
				default: goto pp46;
			}
pp54:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp132;
				default: goto pp46;
			}
pp55:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'H':
				case 'h': goto pp133;
				case 'I':
				case 'i': goto pp134;
				default: goto pp46;
			}
pp56:
			ppaccept = 0;
			ppch = *(PPMARKER = ++PPCURSOR);
			switch (ppch) {
				case 0x00:
				case 0x01:
				case 0x02:
				case 0x03:
				case 0x04:
				case 0x05:
				case 0x06:
				case 0x07:
				case 0x08:
				case '\t':
				case '\n':
				case '\v':
				case '\f':
				case '\r':
				case 0x0E:
				case 0x0F:
				case 0x10:
				case 0x11:
				case 0x12:
				case 0x13:
				case 0x14:
				case 0x15:
				case 0x16:
				case 0x17:
				case 0x18:
				case 0x19:
				case 0x1A:
				case 0x1B:
				case 0x1C:
				case 0x1D:
				case 0x1E:
				case 0x1F:
				case '[':
				case 0x7F: goto pp3;
				default: goto pp136;
			}
pp57:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp3;
			}
pp58:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
pp59:
			ppch = *++PPCURSOR;
pp60:
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'x': goto pp59;
				case ':':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'y':
				case 'z': goto pp45;
				default: goto pp34;
			}
pp61:
			ppaccept = 0;
			ppch = *(PPMARKER = ++PPCURSOR);
			switch (ppch) {
				case '-':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp140;
				default: goto pp3;
			}
pp62:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '|': goto pp141;
				default: goto pp63;
			}
pp63:
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
pp64:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
pp65:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
pp66:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
pp67:
			ppch = *++PPCURSOR;
pp68:
			switch (ppch) {
				case 0x00: goto pp69;
				case '"': goto pp70;
				case '\\': goto pp71;
				default: goto pp67;
			}
pp69:
			PPCURSOR = PPMARKER;
			switch (ppaccept) {
				case 0: goto pp3;
				case 1: goto pp25;
				case 2: goto pp177;
				default: goto pp139;
			}
pp70:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q + 1, PPCURSOR - q - 2);
			token->len = PPCURSOR - q - 2;
			q = PPCURSOR;
			return 0;
		}
pp71:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '\n': goto pp69;
				default: goto pp67;
			}
pp72:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
pp73:
			ppch = *++PPCURSOR;
pp74:
			switch (ppch) {
				case 0x00: goto pp69;
				case '\'': goto pp70;
				case '\\': goto pp75;
				default: goto pp73;
			}
pp75:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '\n': goto pp69;
				default: goto pp73;
			}
pp76:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp76;
				default: goto pp77;
			}
pp77:
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, PPCURSOR - q);
			token->len = PPCURSOR - q;
			q = PPCURSOR;
			return 0;
		}
pp78:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'x': goto pp78;
				default: goto pp34;
			}
pp79:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '-':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp79;
				case ':': goto pp142;
				default: goto pp69;
			}
pp80:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
pp81:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
pp82:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
pp83:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9': goto pp83;
				default: goto pp84;
			}
pp84:
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, PPCURSOR - q);
			token->len = PPCURSOR - q;
			q = PPCURSOR;
			return 0;
		}
pp85:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
pp86:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
pp87:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp143;
				default: goto pp46;
			}
pp88:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp144;
				default: goto pp46;
			}
pp89:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'D':
				case 'd': goto pp146;
				default: goto pp46;
			}
pp90:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				case 'C':
				case 'c': goto pp148;
				default: goto pp91;
			}
pp91:
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
pp92:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp150;
				default: goto pp60;
			}
pp93:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp94;
			}
pp94:
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
pp95:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp151;
				default: goto pp60;
			}
pp96:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp152;
				default: goto pp46;
			}
pp97:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp153;
				default: goto pp46;
			}
pp98:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp154;
				case 'S':
				case 's': goto pp155;
				default: goto pp60;
			}
pp99:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp156;
				default: goto pp46;
			}
pp100:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp157;
				default: goto pp46;
			}
pp101:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'D':
				case 'd': goto pp158;
				default: goto pp46;
			}
pp102:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp160;
				default: goto pp46;
			}
pp103:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp160;
				default: goto pp60;
			}
pp104:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp161;
				default: goto pp60;
			}
pp105:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp162;
				default: goto pp46;
			}
pp106:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp164;
				default: goto pp46;
			}
pp107:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp165;
				default: goto pp46;
			}
pp108:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp166;
				default: goto pp46;
			}
pp109:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'V':
				case 'v': goto pp167;
				default: goto pp46;
			}
pp110:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp168;
				default: goto pp46;
			}
pp111:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				case 'N':
				case 'n': goto pp169;
				case 'S':
				case 's': goto pp170;
				case 'T':
				case 't': goto pp171;
				default: goto pp112;
			}
pp112:
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
pp113:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp114;
			}
pp114:
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
pp115:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp172;
				default: goto pp46;
			}
pp116:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'F':
				case 'f': goto pp173;
				default: goto pp46;
			}
pp117:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'K':
				case 'k': goto pp174;
				case 'M':
				case 'm': goto pp175;
				default: goto pp46;
			}
pp118:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp176;
				default: goto pp46;
			}
pp119:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp178;
				default: goto pp46;
			}
pp120:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'F':
				case 'f': goto pp179;
				default: goto pp46;
			}
pp121:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp122;
			}
pp122:
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
pp123:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				case 'D':
				case 'd': goto pp180;
				default: goto pp124;
			}
pp124:
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
pp125:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp181;
				default: goto pp46;
			}
pp126:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'G':
				case 'g': goto pp182;
				default: goto pp46;
			}
pp127:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp183;
				case 'T':
				case 't': goto pp184;
				default: goto pp46;
			}
pp128:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp186;
				default: goto pp46;
			}
pp129:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'U':
				case 'u': goto pp187;
				default: goto pp46;
			}
pp130:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'D':
				case 'd': goto pp188;
				default: goto pp46;
			}
pp131:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp189;
				default: goto pp46;
			}
pp132:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp190;
				default: goto pp46;
			}
pp133:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp191;
				default: goto pp46;
			}
pp134:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp192;
				default: goto pp46;
			}
pp135:
			ppch = *++PPCURSOR;
pp136:
			switch (ppch) {
				case 0x00:
				case 0x01:
				case 0x02:
				case 0x03:
				case 0x04:
				case 0x05:
				case 0x06:
				case 0x07:
				case 0x08:
				case '\t':
				case '\n':
				case '\v':
				case '\f':
				case '\r':
				case 0x0E:
				case 0x0F:
				case 0x10:
				case 0x11:
				case 0x12:
				case 0x13:
				case 0x14:
				case 0x15:
				case 0x16:
				case 0x17:
				case 0x18:
				case 0x19:
				case 0x1A:
				case 0x1B:
				case 0x1C:
				case 0x1D:
				case 0x1E:
				case 0x1F:
				case '[':
				case 0x7F: goto pp69;
				case '\\': goto pp137;
				case ']': goto pp138;
				default: goto pp135;
			}
pp137:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 0x00:
				case 0x01:
				case 0x02:
				case 0x03:
				case 0x04:
				case 0x05:
				case 0x06:
				case 0x07:
				case 0x08:
				case '\t':
				case '\n':
				case '\v':
				case '\f':
				case '\r':
				case 0x0E:
				case 0x0F:
				case 0x10:
				case 0x11:
				case 0x12:
				case 0x13:
				case 0x14:
				case 0x15:
				case 0x16:
				case 0x17:
				case 0x18:
				case 0x19:
				case 0x1A:
				case 0x1B:
				case 0x1C:
				case 0x1D:
				case 0x1E:
				case 0x1F:
				case 0x7F: goto pp69;
				case '\\': goto pp137;
				case ']': goto pp193;
				default: goto pp135;
			}
pp138:
			++PPCURSOR;
pp139:
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q + 1, PPCURSOR - q - 2);
			token->len = PPCURSOR - q - 2;
			q = PPCURSOR;
			return 0;
		}
pp140:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '-':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp140;
				case '}': goto pp194;
				default: goto pp69;
			}
pp141:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
pp142:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q + 1, PPCURSOR - q - 2);
			token->len = PPCURSOR - q - 2;
			q = PPCURSOR;
			return 0;
		}
pp143:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp195;
				default: goto pp46;
			}
pp144:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp145;
			}
pp145:
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
pp146:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp147;
			}
pp147:
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
pp148:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp149;
			}
pp149:
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
pp150:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'W':
				case 'w': goto pp196;
				default: goto pp46;
			}
pp151:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp197;
				case 'T':
				case 't': goto pp199;
				default: goto pp46;
			}
pp152:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'V':
				case 'v': goto pp201;
				default: goto pp46;
			}
pp153:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp202;
				default: goto pp46;
			}
pp154:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp203;
				default: goto pp46;
			}
pp155:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'C':
				case 'c': goto pp204;
				default: goto pp46;
			}
pp156:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp206;
				default: goto pp46;
			}
pp157:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp207;
				default: goto pp46;
			}
pp158:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp159;
			}
pp159:
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
pp160:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp209;
				default: goto pp46;
			}
pp161:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp210;
				default: goto pp46;
			}
pp162:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp163;
			}
pp163:
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
pp164:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'M':
				case 'm': goto pp211;
				default: goto pp46;
			}
pp165:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp213;
				default: goto pp46;
			}
pp166:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'U':
				case 'u': goto pp215;
				default: goto pp46;
			}
pp167:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp216;
				default: goto pp46;
			}
pp168:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'K':
				case 'k': goto pp217;
				default: goto pp46;
			}
pp169:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp218;
				default: goto pp46;
			}
pp170:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp219;
				default: goto pp46;
			}
pp171:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'O':
				case 'o': goto pp220;
				default: goto pp46;
			}
pp172:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp222;
				default: goto pp46;
			}
pp173:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp224;
				default: goto pp46;
			}
pp174:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp226;
				default: goto pp46;
			}
pp175:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp228;
				default: goto pp46;
			}
pp176:
			ppaccept = 2;
			ppch = *(PPMARKER = ++PPCURSOR);
			switch (ppch) {
				case ' ': goto pp229;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp177;
			}
pp177:
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
pp178:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'L':
				case 'l': goto pp230;
				default: goto pp46;
			}
pp179:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp232;
				default: goto pp46;
			}
pp180:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp233;
				default: goto pp46;
			}
pp181:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp234;
				default: goto pp46;
			}
pp182:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'H':
				case 'h': goto pp235;
				default: goto pp46;
			}
pp183:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp236;
				default: goto pp46;
			}
pp184:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp185;
			}
pp185:
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
pp186:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp237;
				default: goto pp46;
			}
pp187:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp239;
				default: goto pp46;
			}
pp188:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'A':
				case 'a': goto pp241;
				default: goto pp46;
			}
pp189:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp242;
				default: goto pp46;
			}
pp190:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'U':
				case 'u': goto pp243;
				default: goto pp46;
			}
pp191:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp244;
				case 'R':
				case 'r': goto pp246;
				default: goto pp46;
			}
pp192:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'H':
				case 'h': goto pp247;
				default: goto pp46;
			}
pp193:
			ppaccept = 3;
			ppch = *(PPMARKER = ++PPCURSOR);
			switch (ppch) {
				case 0x00:
				case 0x01:
				case 0x02:
				case 0x03:
				case 0x04:
				case 0x05:
				case 0x06:
				case 0x07:
				case 0x08:
				case '\t':
				case '\n':
				case '\v':
				case '\f':
				case '\r':
				case 0x0E:
				case 0x0F:
				case 0x10:
				case 0x11:
				case 0x12:
				case 0x13:
				case 0x14:
				case 0x15:
				case 0x16:
				case 0x17:
				case 0x18:
				case 0x19:
				case 0x1A:
				case 0x1B:
				case 0x1C:
				case 0x1D:
				case 0x1E:
				case 0x1F:
				case '[':
				case 0x7F: goto pp139;
				case '\\': goto pp137;
				case ']': goto pp138;
				default: goto pp135;
			}
pp194:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_BPLACEHOLDER;
			token->value = estrndup(q + 1, PPCURSOR - q - 2);
			token->len = PPCURSOR - q - 2;
			q = PPCURSOR;
			return 0;
		}
pp195:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp249;
				default: goto pp46;
			}
pp196:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp250;
				default: goto pp46;
			}
pp197:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp198;
			}
pp198:
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
pp199:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp200;
			}
pp200:
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
pp201:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp251;
				default: goto pp46;
			}
pp202:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp252;
				default: goto pp46;
			}
pp203:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp254;
				default: goto pp46;
			}
pp204:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp205;
			}
pp205:
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
pp206:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'I':
				case 'i': goto pp255;
				default: goto pp46;
			}
pp207:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp208;
			}
pp208:
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
pp209:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp256;
				default: goto pp46;
			}
pp210:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp257;
				default: goto pp46;
			}
pp211:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp212;
			}
pp212:
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
pp213:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp214;
			}
pp214:
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
pp215:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'P':
				case 'p': goto pp259;
				default: goto pp46;
			}
pp216:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp261;
				default: goto pp46;
			}
pp217:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp262;
				default: goto pp46;
			}
pp218:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp264;
				default: goto pp46;
			}
pp219:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp266;
				default: goto pp46;
			}
pp220:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp221;
			}
pp221:
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
pp222:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp223;
			}
pp223:
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
pp224:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp225;
			}
pp225:
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
pp226:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp227;
			}
pp227:
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
pp228:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp267;
				default: goto pp46;
			}
pp229:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'B':
				case 'b': goto pp269;
				default: goto pp69;
			}
pp230:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp231;
			}
pp231:
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
pp232:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp270;
				default: goto pp46;
			}
pp233:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp271;
				default: goto pp46;
			}
pp234:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp273;
				default: goto pp46;
			}
pp235:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp275;
				default: goto pp46;
			}
pp236:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'C':
				case 'c': goto pp277;
				default: goto pp46;
			}
pp237:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp238;
			}
pp238:
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
pp239:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp240;
			}
pp240:
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
pp241:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp278;
				default: goto pp46;
			}
pp242:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'G':
				case 'g': goto pp279;
				default: goto pp46;
			}
pp243:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp281;
				default: goto pp46;
			}
pp244:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp245;
			}
pp245:
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
pp246:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp282;
				default: goto pp46;
			}
pp247:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp248;
			}
pp248:
			{
			token->opcode = PHQL_T_WITH;
			return 0;
		}
pp249:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp284;
				default: goto pp46;
			}
pp250:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp285;
				default: goto pp46;
			}
pp251:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'R':
				case 'r': goto pp286;
				default: goto pp46;
			}
pp252:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp253;
			}
pp253:
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
pp254:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp287;
				default: goto pp46;
			}
pp255:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp289;
				default: goto pp46;
			}
pp256:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp290;
				default: goto pp46;
			}
pp257:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp258;
			}
pp258:
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
pp259:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp260;
			}
pp260:
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
pp261:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'G':
				case 'g': goto pp292;
				default: goto pp46;
			}
pp262:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp263;
			}
pp263:
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
pp264:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp265;
			}
pp265:
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
pp266:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp294;
				default: goto pp46;
			}
pp267:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp268;
			}
pp268:
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
pp269:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp296;
				default: goto pp69;
			}
pp270:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp297;
				default: goto pp46;
			}
pp271:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp272;
			}
pp272:
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
pp273:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp274;
			}
pp274:
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
pp275:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp276;
			}
pp276:
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
pp277:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp299;
				default: goto pp46;
			}
pp278:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp301;
				default: goto pp46;
			}
pp279:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp280;
			}
pp280:
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
pp281:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'S':
				case 's': goto pp303;
				default: goto pp46;
			}
pp282:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp283;
			}
pp283:
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
pp284:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp305;
				default: goto pp46;
			}
pp285:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp307;
				default: goto pp46;
			}
pp286:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp309;
				default: goto pp46;
			}
pp287:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp288;
			}
pp288:
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
pp289:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'C':
				case 'c': goto pp311;
				default: goto pp46;
			}
pp290:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp291;
			}
pp291:
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
pp292:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp293;
			}
pp293:
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
pp294:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp295;
			}
pp295:
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
pp296:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp312;
				default: goto pp69;
			}
pp297:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp298;
			}
pp298:
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
pp299:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp300;
			}
pp300:
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
pp301:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp302;
			}
pp302:
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
pp303:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp304;
			}
pp304:
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
pp305:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp306;
			}
pp306:
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
pp307:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp308;
			}
pp308:
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
pp309:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp310;
			}
pp310:
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
pp311:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'T':
				case 't': goto pp313;
				default: goto pp46;
			}
pp312:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'W':
				case 'w': goto pp315;
				default: goto pp69;
			}
pp313:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z': goto pp45;
				default: goto pp314;
			}
pp314:
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
pp315:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp316;
				default: goto pp69;
			}
pp316:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'E':
				case 'e': goto pp317;
				default: goto pp69;
			}
pp317:
			ppch = *++PPCURSOR;
			switch (ppch) {
				case 'N':
				case 'n': goto pp318;
				default: goto pp69;
			}
pp318:
			++PPCURSOR;
			{
			token->opcode = PHQL_T_BETWEEN_NOT;
			return 0;
		}
		}

	}

	return status;
}
