
extern zend_class_entry *phalcon_http_request_exceptions_missingfilters_ce;

ZEPHIR_INIT_CLASS(Phalcon_Http_Request_Exceptions_MissingFilters);

PHP_METHOD(Phalcon_Http_Request_Exceptions_MissingFilters, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_http_request_exceptions_missingfilters___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_http_request_exceptions_missingfilters_method_entry) {
	PHP_ME(Phalcon_Http_Request_Exceptions_MissingFilters, __construct, arginfo_phalcon_http_request_exceptions_missingfilters___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
