
extern zend_class_entry *phalcon_http_request_exceptions_sanitizernotfound_ce;

ZEPHIR_INIT_CLASS(Phalcon_Http_Request_Exceptions_SanitizerNotFound);

PHP_METHOD(Phalcon_Http_Request_Exceptions_SanitizerNotFound, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_http_request_exceptions_sanitizernotfound___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, sanitizer, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_http_request_exceptions_sanitizernotfound_method_entry) {
	PHP_ME(Phalcon_Http_Request_Exceptions_SanitizerNotFound, __construct, arginfo_phalcon_http_request_exceptions_sanitizernotfound___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
