
extern zend_class_entry *phalcon_encryption_security_uuid_version1_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_Uuid_Version1);

PHP_METHOD(Phalcon_Encryption_Security_Uuid_Version1, __construct);
PHP_METHOD(Phalcon_Encryption_Security_Uuid_Version1, getDateTime);
PHP_METHOD(Phalcon_Encryption_Security_Uuid_Version1, getNode);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_security_uuid_version1___construct, 0, 0, 0)
	ZEND_ARG_OBJ_TYPE_MASK(0, dateTime, DateTimeInterface, MAY_BE_NULL, "null")
	ZEND_ARG_INFO(0, node)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_encryption_security_uuid_version1_getdatetime, 0, 0, DateTimeImmutable, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_encryption_security_uuid_version1_getnode, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_uuid_version1_method_entry) {
	PHP_ME(Phalcon_Encryption_Security_Uuid_Version1, __construct, arginfo_phalcon_encryption_security_uuid_version1___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Encryption_Security_Uuid_Version1, getDateTime, arginfo_phalcon_encryption_security_uuid_version1_getdatetime, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Encryption_Security_Uuid_Version1, getNode, arginfo_phalcon_encryption_security_uuid_version1_getnode, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
