
extern zend_class_entry *phalcon_contracts_acl_component_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Acl_Component);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_acl_component___tostring, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_acl_component_getdescription, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_acl_component_getname, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_acl_component_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Acl_Component, __toString, arginfo_phalcon_contracts_acl_component___tostring)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Acl_Component, getDescription, arginfo_phalcon_contracts_acl_component_getdescription)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Acl_Component, getName, arginfo_phalcon_contracts_acl_component_getname)
	PHP_FE_END
};
