
extern zend_class_entry *phalcon_logger_adapter_exceptions_invalidstreammode_ce;

ZEPHIR_INIT_CLASS(Phalcon_Logger_Adapter_Exceptions_InvalidStreamMode);

PHP_METHOD(Phalcon_Logger_Adapter_Exceptions_InvalidStreamMode, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_logger_adapter_exceptions_invalidstreammode___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_logger_adapter_exceptions_invalidstreammode_method_entry) {
PHP_ME(Phalcon_Logger_Adapter_Exceptions_InvalidStreamMode, __construct, arginfo_phalcon_logger_adapter_exceptions_invalidstreammode___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
