
extern zend_class_entry *phalcon_queue_adapter_memory_memoryqueue_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Memory_MemoryQueue);

PHP_METHOD(Phalcon_Queue_Adapter_Memory_MemoryQueue, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Memory_MemoryQueue, getQueueName);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_memory_memoryqueue___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, queueName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_queue_adapter_memory_memoryqueue_getqueuename, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_memory_memoryqueue_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Memory_MemoryQueue, __construct, arginfo_phalcon_queue_adapter_memory_memoryqueue___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Memory_MemoryQueue, getQueueName, arginfo_phalcon_queue_adapter_memory_memoryqueue_getqueuename, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
