
extern zend_class_entry *phalcon_queue_adapter_memory_memoryconnectionfactory_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Adapter_Memory_MemoryConnectionFactory);

PHP_METHOD(Phalcon_Queue_Adapter_Memory_MemoryConnectionFactory, __construct);
PHP_METHOD(Phalcon_Queue_Adapter_Memory_MemoryConnectionFactory, createContext);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_adapter_memory_memoryconnectionfactory___construct, 0, 0, 0)
ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, options, IS_ARRAY, 0, "[]")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_queue_adapter_memory_memoryconnectionfactory_createcontext, 0, 0, Phalcon\\Contracts\\Queue\\Context, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_adapter_memory_memoryconnectionfactory_method_entry) {
	PHP_ME(Phalcon_Queue_Adapter_Memory_MemoryConnectionFactory, __construct, arginfo_phalcon_queue_adapter_memory_memoryconnectionfactory___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Phalcon_Queue_Adapter_Memory_MemoryConnectionFactory, createContext, arginfo_phalcon_queue_adapter_memory_memoryconnectionfactory_createcontext, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
