
extern zend_class_entry *phalcon_mvc_model_metadata_exceptions_corruptedmetadata_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_MetaData_Exceptions_CorruptedMetaData);

PHP_METHOD(Phalcon_Mvc_Model_MetaData_Exceptions_CorruptedMetaData, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_model_metadata_exceptions_corruptedmetadata___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_metadata_exceptions_corruptedmetadata_method_entry) {
PHP_ME(Phalcon_Mvc_Model_MetaData_Exceptions_CorruptedMetaData, __construct, arginfo_phalcon_mvc_model_metadata_exceptions_corruptedmetadata___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
