
extern zend_class_entry *phalcon_mvc_model_metadata_exceptions_noannotationsforclass_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Model_MetaData_Exceptions_NoAnnotationsForClass);

PHP_METHOD(Phalcon_Mvc_Model_MetaData_Exceptions_NoAnnotationsForClass, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_model_metadata_exceptions_noannotationsforclass___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, className, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_model_metadata_exceptions_noannotationsforclass_method_entry) {
	PHP_ME(Phalcon_Mvc_Model_MetaData_Exceptions_NoAnnotationsForClass, __construct, arginfo_phalcon_mvc_model_metadata_exceptions_noannotationsforclass___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
