
extern zend_class_entry *phalcon_session_exceptions_sessionmodificationdenied_ce;

ZEPHIR_INIT_CLASS(Phalcon_Session_Exceptions_SessionModificationDenied);

PHP_METHOD(Phalcon_Session_Exceptions_SessionModificationDenied, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_session_exceptions_sessionmodificationdenied___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_session_exceptions_sessionmodificationdenied_method_entry) {
PHP_ME(Phalcon_Session_Exceptions_SessionModificationDenied, __construct, arginfo_phalcon_session_exceptions_sessionmodificationdenied___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
