
extern zend_class_entry *phalcon_paginator_exceptions_buildermodelnotdefined_ce;

ZEPHIR_INIT_CLASS(Phalcon_Paginator_Exceptions_BuilderModelNotDefined);

PHP_METHOD(Phalcon_Paginator_Exceptions_BuilderModelNotDefined, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_paginator_exceptions_buildermodelnotdefined___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_paginator_exceptions_buildermodelnotdefined_method_entry) {
PHP_ME(Phalcon_Paginator_Exceptions_BuilderModelNotDefined, __construct, arginfo_phalcon_paginator_exceptions_buildermodelnotdefined___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
