
extern zend_class_entry *phalcon_cli_console_exceptions_consolemodulenotregistered_ce;

ZEPHIR_INIT_CLASS(Phalcon_Cli_Console_Exceptions_ConsoleModuleNotRegistered);

PHP_METHOD(Phalcon_Cli_Console_Exceptions_ConsoleModuleNotRegistered, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_cli_console_exceptions_consolemodulenotregistered___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, moduleName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_cli_console_exceptions_consolemodulenotregistered_method_entry) {
	PHP_ME(Phalcon_Cli_Console_Exceptions_ConsoleModuleNotRegistered, __construct, arginfo_phalcon_cli_console_exceptions_consolemodulenotregistered___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
