
extern zend_class_entry *phalcon_auth_exceptions_defaultguardnotregistered_ce;

ZEPHIR_INIT_CLASS(Phalcon_Auth_Exceptions_DefaultGuardNotRegistered);

PHP_METHOD(Phalcon_Auth_Exceptions_DefaultGuardNotRegistered, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_auth_exceptions_defaultguardnotregistered___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_auth_exceptions_defaultguardnotregistered_method_entry) {
PHP_ME(Phalcon_Auth_Exceptions_DefaultGuardNotRegistered, __construct, arginfo_phalcon_auth_exceptions_defaultguardnotregistered___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
