
extern zend_class_entry *phalcon_di_exceptions_setterparametersmustbearray_ce;

ZEPHIR_INIT_CLASS(Phalcon_Di_Exceptions_SetterParametersMustBeArray);

PHP_METHOD(Phalcon_Di_Exceptions_SetterParametersMustBeArray, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_di_exceptions_setterparametersmustbearray___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_di_exceptions_setterparametersmustbearray_method_entry) {
PHP_ME(Phalcon_Di_Exceptions_SetterParametersMustBeArray, __construct, arginfo_phalcon_di_exceptions_setterparametersmustbearray___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
