
extern zend_class_entry *phalcon_encryption_security_exceptions_unknownhashalgorithm_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_Exceptions_UnknownHashAlgorithm);

PHP_METHOD(Phalcon_Encryption_Security_Exceptions_UnknownHashAlgorithm, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_encryption_security_exceptions_unknownhashalgorithm___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, algo, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_exceptions_unknownhashalgorithm_method_entry) {
	PHP_ME(Phalcon_Encryption_Security_Exceptions_UnknownHashAlgorithm, __construct, arginfo_phalcon_encryption_security_exceptions_unknownhashalgorithm___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
