
extern zend_class_entry *phalcon_contracts_encryption_security_csrfprotection_ce;

ZEPHIR_INIT_CLASS(Phalcon_Contracts_Encryption_Security_CsrfProtection);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_gettoken, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_gettokenkey, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_checktoken, 0, 0, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, tokenKey, IS_STRING, 1, "null")
	ZEND_ARG_INFO(0, tokenValue)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, destroyIfValid, _IS_BOOL, 0, "true")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_destroytoken, 0, 0, Phalcon\\Contracts\\Encryption\\Security\\Security, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_getrequesttoken, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_contracts_encryption_security_csrfprotection_getsessiontoken, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_contracts_encryption_security_csrfprotection_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, getToken, arginfo_phalcon_contracts_encryption_security_csrfprotection_gettoken)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, getTokenKey, arginfo_phalcon_contracts_encryption_security_csrfprotection_gettokenkey)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, checkToken, arginfo_phalcon_contracts_encryption_security_csrfprotection_checktoken)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, destroyToken, arginfo_phalcon_contracts_encryption_security_csrfprotection_destroytoken)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, getRequestToken, arginfo_phalcon_contracts_encryption_security_csrfprotection_getrequesttoken)
	PHP_ABSTRACT_ME(Phalcon_Contracts_Encryption_Security_CsrfProtection, getSessionToken, arginfo_phalcon_contracts_encryption_security_csrfprotection_getsessiontoken)
	PHP_FE_END
};
