
extern zend_class_entry *phalcon_filter_validation_validator_file_mimetype_ce;

ZEPHIR_INIT_CLASS(Phalcon_Filter_Validation_Validator_File_MimeType);

PHP_METHOD(Phalcon_Filter_Validation_Validator_File_MimeType, validate);
PHP_METHOD(Phalcon_Filter_Validation_Validator_File_MimeType, phpExtensionLoaded);
PHP_METHOD(Phalcon_Filter_Validation_Validator_File_MimeType, phpFunctionExists);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_filter_validation_validator_file_mimetype_validate, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, validation, Phalcon\\Filter\\Validation, 0)
	ZEND_ARG_INFO(0, field)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_filter_validation_validator_file_mimetype_phpextensionloaded, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_filter_validation_validator_file_mimetype_phpfunctionexists, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, functionName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_filter_validation_validator_file_mimetype_method_entry) {
	PHP_ME(Phalcon_Filter_Validation_Validator_File_MimeType, validate, arginfo_phalcon_filter_validation_validator_file_mimetype_validate, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Filter_Validation_Validator_File_MimeType, phpExtensionLoaded, arginfo_phalcon_filter_validation_validator_file_mimetype_phpextensionloaded, ZEND_ACC_PROTECTED)
	PHP_ME(Phalcon_Filter_Validation_Validator_File_MimeType, phpFunctionExists, arginfo_phalcon_filter_validation_validator_file_mimetype_phpfunctionexists, ZEND_ACC_PROTECTED)
	PHP_FE_END
};
