
extern zend_class_entry *phalcon_queue_exceptions_temporaryqueuenotsupportedexception_ce;

ZEPHIR_INIT_CLASS(Phalcon_Queue_Exceptions_TemporaryQueueNotSupportedException);

PHP_METHOD(Phalcon_Queue_Exceptions_TemporaryQueueNotSupportedException, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_queue_exceptions_temporaryqueuenotsupportedexception___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_queue_exceptions_temporaryqueuenotsupportedexception_method_entry) {
PHP_ME(Phalcon_Queue_Exceptions_TemporaryQueueNotSupportedException, __construct, arginfo_phalcon_queue_exceptions_temporaryqueuenotsupportedexception___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
