
extern zend_class_entry *phalcon_db_exceptions_checkexpressionrequired_ce;

ZEPHIR_INIT_CLASS(Phalcon_Db_Exceptions_CheckExpressionRequired);

PHP_METHOD(Phalcon_Db_Exceptions_CheckExpressionRequired, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_db_exceptions_checkexpressionrequired___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_db_exceptions_checkexpressionrequired_method_entry) {
PHP_ME(Phalcon_Db_Exceptions_CheckExpressionRequired, __construct, arginfo_phalcon_db_exceptions_checkexpressionrequired___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
