
extern zend_class_entry *phalcon_db_exceptions_referencedtablerequired_ce;

ZEPHIR_INIT_CLASS(Phalcon_Db_Exceptions_ReferencedTableRequired);

PHP_METHOD(Phalcon_Db_Exceptions_ReferencedTableRequired, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_db_exceptions_referencedtablerequired___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_db_exceptions_referencedtablerequired_method_entry) {
PHP_ME(Phalcon_Db_Exceptions_ReferencedTableRequired, __construct, arginfo_phalcon_db_exceptions_referencedtablerequired___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
