
extern zend_class_entry *phalcon_http_cookie_exceptions_cryptinterfacerequired_ce;

ZEPHIR_INIT_CLASS(Phalcon_Http_Cookie_Exceptions_CryptInterfaceRequired);

PHP_METHOD(Phalcon_Http_Cookie_Exceptions_CryptInterfaceRequired, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_http_cookie_exceptions_cryptinterfacerequired___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_http_cookie_exceptions_cryptinterfacerequired_method_entry) {
PHP_ME(Phalcon_Http_Cookie_Exceptions_CryptInterfaceRequired, __construct, arginfo_phalcon_http_cookie_exceptions_cryptinterfacerequired___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
