DROP TABLE IF EXISTS `co_dialect`;

create table co_dialect
(
  field_primary            int auto_increment primary key                   comment 'field_primary field',
  field_blob               blob                                        null comment 'field_blob field',
  field_binary             binary(10)                                  null comment 'field_binary field',
  field_bit                bit(10)                                     null comment 'field_bit field',
  field_bit_default        bit(10)       default b'1'                  null comment 'field_bit_default field',
  field_bigint             bigint        unsigned                      null comment 'field_bigint field',
  field_bigint_default     bigint        default 1                     null comment 'field_bigint_default field',
  field_boolean            tinyint(1)    unsigned                      null comment 'field_boolean field',
  field_boolean_default    tinyint(1)    default 1                     null comment 'field_boolean_default field',
  field_char               char(10)                                    null comment 'field_char field',
  field_char_default       char(10)      default 'ABC'                 null comment 'field_char_default field',
  field_decimal            decimal(10,4)                               null comment 'field_decimal field',
  field_decimal_default    decimal(10,4) default 14.5678               null comment 'field_decimal_default field',
  field_enum               enum('xs', 's', 'm', 'l', 'xl', 'internal') null comment 'field_enum field',
  field_integer            int(10)                                     null comment 'field_integer field',
  field_integer_default    int(10)       default 1                     null comment 'field_integer_default field',
  field_json               json                                        null comment 'field_json field',
  field_float              float(10,4)                                 null comment 'field_float field',
  field_float_default      float(10,4)   default 14.5678               null comment 'field_float_default field',
  field_date               date                                        null comment 'field_date field',
  field_date_default       date          default '2018-10-01'          null comment 'field_date_default field',
  field_datetime           datetime                                    null comment 'field_datetime field',
  field_datetime_default   datetime      default '2018-10-01 12:34:56' null comment 'field_datetime_default field',
  field_time               time                                        null comment 'field_time field',
  field_time_default       time          default '12:34:56'            null comment 'field_time_default field',
  field_timestamp          timestamp                                   null comment 'field_timestamp field',
  field_timestamp_default  timestamp     default '2018-10-01 12:34:56' null comment 'field_timestamp_default field',
  field_mediumint          mediumint(10) unsigned                      null comment 'field_mediumint field',
  field_mediumint_default  mediumint(10) default 1                     null comment 'field_mediumint_default field',
  field_smallint           smallint(10)  unsigned                      null comment 'field_smallint field',
  field_smallint_default   smallint(10)  default 1                     null comment 'field_smallint_default field',
  field_tinyint            tinyint(10)   unsigned                      null comment 'field_tinyint field',
  field_tinyint_default    tinyint(10)   default 1                     null comment 'field_tinyint_default field',
  field_longtext           longtext                                    null comment 'field_longtext field',
  field_mediumtext         mediumtext                                  null comment 'field_mediumtext field',
  field_tinytext           tinytext                                    null comment 'field_tinytext field',
  field_text               text                                        null comment 'field_text field',
  field_varbinary          varbinary(10)                               null comment 'field_varbinary field',
  field_varchar            varchar(10)                                 null comment 'field_varchar field',
  field_varchar_default    varchar(10)   default 'D'                   null comment 'field_varchar_default field',
  unique key dialect_table_unique (field_integer),
  key dialect_table_index (field_bigint),
  key dialect_table_two_fields (field_char, field_char_default)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
