
extern zend_class_entry *phalcon_assets_traits_attributestrait_ce;

ZEPHIR_INIT_CLASS(Phalcon_Assets_Traits_AttributesTrait);

PHP_METHOD(Phalcon_Assets_Traits_AttributesTrait, getAttributes);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_assets_traits_attributestrait_getattributes, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_assets_traits_attributestrait_method_entry) {
	PHP_ME(Phalcon_Assets_Traits_AttributesTrait, getAttributes, arginfo_phalcon_assets_traits_attributestrait_getattributes, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
