
extern zend_class_entry *phalcon_translate_exceptions_immutableobject_ce;

ZEPHIR_INIT_CLASS(Phalcon_Translate_Exceptions_ImmutableObject);

PHP_METHOD(Phalcon_Translate_Exceptions_ImmutableObject, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_translate_exceptions_immutableobject___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_translate_exceptions_immutableobject_method_entry) {
PHP_ME(Phalcon_Translate_Exceptions_ImmutableObject, __construct, arginfo_phalcon_translate_exceptions_immutableobject___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
