
extern zend_class_entry *phalcon_translate_exceptions_missinggettextextension_ce;

ZEPHIR_INIT_CLASS(Phalcon_Translate_Exceptions_MissingGettextExtension);

PHP_METHOD(Phalcon_Translate_Exceptions_MissingGettextExtension, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_translate_exceptions_missinggettextextension___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_translate_exceptions_missinggettextextension_method_entry) {
PHP_ME(Phalcon_Translate_Exceptions_MissingGettextExtension, __construct, arginfo_phalcon_translate_exceptions_missinggettextextension___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
