
extern zend_class_entry *phalcon_mvc_view_engine_volt_exceptions_macroalreadydefined_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_View_Engine_Volt_Exceptions_MacroAlreadyDefined);

PHP_METHOD(Phalcon_Mvc_View_Engine_Volt_Exceptions_MacroAlreadyDefined, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_view_engine_volt_exceptions_macroalreadydefined___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_view_engine_volt_exceptions_macroalreadydefined_method_entry) {
	PHP_ME(Phalcon_Mvc_View_Engine_Volt_Exceptions_MacroAlreadyDefined, __construct, arginfo_phalcon_mvc_view_engine_volt_exceptions_macroalreadydefined___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
