
extern zend_class_entry *phalcon_mvc_view_engine_volt_exceptions_voltdirectorynotwritable_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_View_Engine_Volt_Exceptions_VoltDirectoryNotWritable);

PHP_METHOD(Phalcon_Mvc_View_Engine_Volt_Exceptions_VoltDirectoryNotWritable, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_view_engine_volt_exceptions_voltdirectorynotwritable___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_view_engine_volt_exceptions_voltdirectorynotwritable_method_entry) {
PHP_ME(Phalcon_Mvc_View_Engine_Volt_Exceptions_VoltDirectoryNotWritable, __construct, arginfo_phalcon_mvc_view_engine_volt_exceptions_voltdirectorynotwritable___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
