
extern zend_class_entry *phalcon_adr_responder_formatter_jsonformatter_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Responder_Formatter_JsonFormatter);

PHP_METHOD(Phalcon_ADR_Responder_Formatter_JsonFormatter, accepts);
PHP_METHOD(Phalcon_ADR_Responder_Formatter_JsonFormatter, contentType);
PHP_METHOD(Phalcon_ADR_Responder_Formatter_JsonFormatter, format);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_adr_responder_formatter_jsonformatter_accepts, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, acceptHeader, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_adr_responder_formatter_jsonformatter_contenttype, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_adr_responder_formatter_jsonformatter_format, 0, 1, IS_STRING, 0)
	ZEND_ARG_OBJ_INFO(0, payload, Phalcon\\Contracts\\ADR\\Payload\\Payload, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_responder_formatter_jsonformatter_method_entry) {
	PHP_ME(Phalcon_ADR_Responder_Formatter_JsonFormatter, accepts, arginfo_phalcon_adr_responder_formatter_jsonformatter_accepts, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_ADR_Responder_Formatter_JsonFormatter, contentType, arginfo_phalcon_adr_responder_formatter_jsonformatter_contenttype, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_ADR_Responder_Formatter_JsonFormatter, format, arginfo_phalcon_adr_responder_formatter_jsonformatter_format, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
