
extern zend_class_entry *phalcon_mvc_micro_exceptions_lazyhandlernotfound_ce;

ZEPHIR_INIT_CLASS(Phalcon_Mvc_Micro_Exceptions_LazyHandlerNotFound);

PHP_METHOD(Phalcon_Mvc_Micro_Exceptions_LazyHandlerNotFound, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_mvc_micro_exceptions_lazyhandlernotfound___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, definition, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_mvc_micro_exceptions_lazyhandlernotfound_method_entry) {
	PHP_ME(Phalcon_Mvc_Micro_Exceptions_LazyHandlerNotFound, __construct, arginfo_phalcon_mvc_micro_exceptions_lazyhandlernotfound___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
