
extern zend_class_entry *phalcon_image_exceptions_compositefailed_ce;

ZEPHIR_INIT_CLASS(Phalcon_Image_Exceptions_CompositeFailed);

PHP_METHOD(Phalcon_Image_Exceptions_CompositeFailed, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_image_exceptions_compositefailed___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_image_exceptions_compositefailed_method_entry) {
PHP_ME(Phalcon_Image_Exceptions_CompositeFailed, __construct, arginfo_phalcon_image_exceptions_compositefailed___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
