
extern zend_class_entry *phalcon_image_exceptions_missingdimensions_ce;

ZEPHIR_INIT_CLASS(Phalcon_Image_Exceptions_MissingDimensions);

PHP_METHOD(Phalcon_Image_Exceptions_MissingDimensions, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_image_exceptions_missingdimensions___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_image_exceptions_missingdimensions_method_entry) {
PHP_ME(Phalcon_Image_Exceptions_MissingDimensions, __construct, arginfo_phalcon_image_exceptions_missingdimensions___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
