
extern zend_class_entry *phalcon_html_link_interfaces_evolvablelinkproviderinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Link_Interfaces_EvolvableLinkProviderInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_html_link_interfaces_evolvablelinkproviderinterface_withlink, 0, 1, Phalcon\\Html\\Link\\Interfaces\\EvolvableLinkProviderInterface, 0)
	ZEND_ARG_OBJ_INFO(0, link, Phalcon\\Html\\Link\\Interfaces\\LinkInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_html_link_interfaces_evolvablelinkproviderinterface_withoutlink, 0, 1, Phalcon\\Html\\Link\\Interfaces\\EvolvableLinkProviderInterface, 0)
	ZEND_ARG_OBJ_INFO(0, link, Phalcon\\Html\\Link\\Interfaces\\LinkInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_link_interfaces_evolvablelinkproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Html_Link_Interfaces_EvolvableLinkProviderInterface, withLink, arginfo_phalcon_html_link_interfaces_evolvablelinkproviderinterface_withlink)
	PHP_ABSTRACT_ME(Phalcon_Html_Link_Interfaces_EvolvableLinkProviderInterface, withoutLink, arginfo_phalcon_html_link_interfaces_evolvablelinkproviderinterface_withoutlink)
	PHP_FE_END
};
