
extern zend_class_entry *phalcon_html_link_interfaces_linkproviderinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Html_Link_Interfaces_LinkProviderInterface);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_html_link_interfaces_linkproviderinterface_getlinks, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_html_link_interfaces_linkproviderinterface_getlinksbyrel, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, rel, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_html_link_interfaces_linkproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Html_Link_Interfaces_LinkProviderInterface, getLinks, arginfo_phalcon_html_link_interfaces_linkproviderinterface_getlinks)
	PHP_ABSTRACT_ME(Phalcon_Html_Link_Interfaces_LinkProviderInterface, getLinksByRel, arginfo_phalcon_html_link_interfaces_linkproviderinterface_getlinksbyrel)
	PHP_FE_END
};
