
extern zend_class_entry *phalcon_storage_serializer_exceptions_invalidserializationinput_ce;

ZEPHIR_INIT_CLASS(Phalcon_Storage_Serializer_Exceptions_InvalidSerializationInput);

PHP_METHOD(Phalcon_Storage_Serializer_Exceptions_InvalidSerializationInput, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_storage_serializer_exceptions_invalidserializationinput___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_storage_serializer_exceptions_invalidserializationinput_method_entry) {
PHP_ME(Phalcon_Storage_Serializer_Exceptions_InvalidSerializationInput, __construct, arginfo_phalcon_storage_serializer_exceptions_invalidserializationinput___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
