
extern zend_class_entry *phalcon_storage_serializer_exceptions_invalidunserializationinput_ce;

ZEPHIR_INIT_CLASS(Phalcon_Storage_Serializer_Exceptions_InvalidUnserializationInput);

PHP_METHOD(Phalcon_Storage_Serializer_Exceptions_InvalidUnserializationInput, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_storage_serializer_exceptions_invalidunserializationinput___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_storage_serializer_exceptions_invalidunserializationinput_method_entry) {
PHP_ME(Phalcon_Storage_Serializer_Exceptions_InvalidUnserializationInput, __construct, arginfo_phalcon_storage_serializer_exceptions_invalidunserializationinput___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
