name: "[Windows] Build Phalcon"

on:
  - push
  - pull_request

env:
  # All versions should be declared here
  PHALCON_VERSION: '7.0.0'
  PHP_VERSION_LIST: '8.3, 8.4, 8.5'
  ARCH_LIST: 'x64, x86'
  TS_LIST: 'nts, ts'

jobs:
  get-extension-matrix:
    runs-on: ubuntu-latest
    name: "Generate Extension Matrix"
    outputs:
      matrix: ${{ steps.extension-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get the extension matrix
        id: extension-matrix
        uses: php/php-windows-builder/extension-matrix@v1
        with:
          extension-url: https://github.com/phalcon/cphalcon
          extension-ref: ${{ env.PHALCON_VERSION }}
          php-version-list: ${{ env.PHP_VERSION_LIST }}
          arch-list: ${{ env.ARCH_LIST }}
          ts-list: ${{ env.TS_LIST }}

  build:
    needs: get-extension-matrix
    runs-on: ${{ matrix.os }}
    name: "Build Phalcon (PHP ${{ matrix.php-version }}-${{ matrix.ts }}-${{ matrix.arch }})"
    strategy:
      matrix: ${{ fromJson(needs.get-extension-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate build folder
        run: |
          cd build/
          php gen-build.php
          cd ../
          pwd
          cp -v build/phalcon/*.* .

      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          args: --enable-phalcon
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
