
extern zend_class_entry *phalcon_adr_responder_jsonresponder_ce;

ZEPHIR_INIT_CLASS(Phalcon_ADR_Responder_JsonResponder);

PHP_METHOD(Phalcon_ADR_Responder_JsonResponder, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_phalcon_adr_responder_jsonresponder___construct, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_adr_responder_jsonresponder_method_entry) {
PHP_ME(Phalcon_ADR_Responder_JsonResponder, __construct, arginfo_phalcon_adr_responder_jsonresponder___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
